### ISSUE TITLE
question: curious about value chosen for max_frame_count

### ISSUE THREAD

**Issue by zsiec** [kaltura/nginx-vod-module#1081]
Greetings, and thanks for this wonderful project! I was hoping someone could better help me understand the underlying reason for this issue: https://github.com/kaltura/nginx-vod-module/issues/853 - I see a static value for max_frame_count here: https://github.com/kaltura/nginx-vod-module/blob/f453ef8ba7ae5a467fbd10a4ce0d3a9e28630813/ngx_http_vod_module.c#L52 I assume this was chosen and set for performance reasons?

**Comment by erankor** [comment]
Yes, in general, I think it's a good idea to have hard limits on numbers that come from input (in this case - it's a function of the configuration + MP4 file). It's usually better to start strict and later loosen some limitations if needed, than to go the other way around...
This specific limit was added both to -
1. Cap CPU time - there are multiple loops in the module that run in O(number-of-frames)
2. Cap memory utilization - each frame consumes 24 bytes, if we have a request that approaches the limit, that's 24MB, which is quite a lot for a single HTTP request...
In order to have tighter bounds, the module uses two different limits - one for segment requests (limited to 64k frames) and one for manifest requests (limited to 1m frames).
If your question was - 'can I increase this number?' then in this case - yes, it will probably work fine with 2m as well, for example.

**Comment by zsiec** [comment]
Thanks @erankor for the detailed answer, makes perfect sense. Thanks again for all your work on this project!
