### ISSUE TITLE
Live (or VOD) in mapped mode with local playlist.json 

### ISSUE THREAD

**Issue by rafuck** [kaltura/nginx-vod-module#1083]
I have configured vod module as:

```
location /History/ {
		vod dash;
		vod_mode mapped;
		alias /archive/video/History/;
		add_header Access-Control-Allow-Origin *;
}
```

And http-queries 
http://MY_URL/History/MY_PATH/playlist.json/manifest.mpd
works like a charm.
But this playlists (playlist.json) files are updated every 5-10 minutes by daemon outside nginx and VOD module do not reread files, and manifest.mpd does not updated. How can I fix it?

**Comment by erankor** [comment]
In general, updating the JSON in place is not recommended - users pulling the stream while the JSON changes will most likely experience errors, because the module will produce an inconsistent stream. A better approach IMHO is to use some kind of versioning scheme, this way, users who start watching version 1, will have all their segment requests served using version 1, and not some mix of version 1 & 2.
If you still want to update it in place, you will need to disable vod_mapping_cache & vod_response_cache, and possibly Nginx's open_file_cache.

**Comment by rafuck** [comment]
Yes. Now I not update playlists in place, I generate different playlists every time, and http request to mpd points to wrapper, which redirect to actual playlist.
