### ISSUE TITLE
Slow data transfer rate using nginx VOD

### ISSUE THREAD

**Issue by julioesperilla** [kaltura/nginx-vod-module#1105]
Done!

**Comment by Alexdrr** [comment]
hi, did you watch the load on the disks?

**Comment by julioesperilla** [comment]
Hi Alexdrr I've record with my phone the I/O disk  [](https://streamable.com/hzpc2) while playing the video (by the way the video were played at the lowest resolution all the time). I also show you my internet connection speed about 22 Mbit/s (enough to watch any video at 1080p Full Hd)

It seems that this is not a load issue. @erankor do you have any ideas? Thank you in advance :)

**Comment by erankor** [comment]
I suggest you try to pull the segments from localhost on the nginx server itself. If you get good results, it means the problem is outside the server, if you get bad results, it's either something in the config or the storage. You can also compare the request processing time from the nginx access log to what you see from the client.
Other than that, make sure to check all standard server metrics while streaming - CPU, network, disk, memory (is it swapping?) etc.

A couple of things I noticed when looking at the config -
1. You have fallback enabled in your conf, this means that if the file is not found locally, the module will proxy the request to the configured upstream, I suggest you test without fallback first, as it can just add noise...
2. vod_metadata_cache is set to a very small value (as a reference, we are using 4GB). If you don't have much memory, you can reduce vod_response_cache, it can be smaller.

**Comment by erankor** [comment]
@julioesperilla, did you find what the issue was? 
Too bad you removed the comments, it may have helped someone...

**Comment by julioesperilla** [comment]
Hi @erankor Sorry this was because of a non-disclosure agreement I signed with my client! The thing is that everything was fine! The problem was the ISP, I had to use a VPN service to bypass the ISP limitations and the streaming worked like a charm! Thanks!
