### ISSUE TITLE
Audio Renditions Not Working in Adaptive Bitrate

### ISSUE THREAD

**Issue by Offek** [kaltura/nginx-vod-module#1110]
Hello,
I'm using this great module to serve mp4 files in adaptive HLS.
I'm using this link structure to play:
http://example.com/hls/test_,low,hi,.mp4.urlset/master.m3u8

Both test_hi.mp4 and test_low.mp4 are the same except for the resolution/bitrate (made with ffmpeg). 
Each of them have 2-3 audio renditions. The audio is the same on both. I've noticed that when playing in adaptive mode, only the first audio file is supported by players. Thus multi-audio is not working in adaptive mode.

Help would be much appreciated.
Thanks in advance!

**Comment by erankor** [comment]
If all audio renditions have the same codec + language, the module will not output them, because by default it muxes the audio with the video, and it can't mux multiple audio renditions...
You can try to set `vod_hls_force_unmuxed_segments on` in nginx.conf, then you'd probably get all audio renditions as `#EXT-X-MEDIA` tags.

**Comment by Offek** [comment]
Thanks for the help!
I can confirm that after correcting the language metadata in the video files the module detects and maps them correctly.
