### ISSUE TITLE
No EXT-X-I-FRAME-STREAM-INF when use  mixFilter

### ISSUE THREAD

**Issue by Bragaman** [kaltura/nginx-vod-module#1128]
I have  no **EXT-X-I-FRAME-STREAM-INF** in HLS master manifest, when use json like this
```json
{
  "sequences": [
      {
           "clips": [
                           {
                               "path": "/path/to/video1.mp4",
                               "type": "source",
                               "tracks": "v1-a1"
                          }
                       ]
    },
    {
           "clips": [
                          {
                          "type": "mixFilter",
                          "sources": [
                          {
                               "type": "source",
                               "path": "/path/to/video1.mp4",
                               "tracks": "v1"
                           },
                           {
                               "type": "source",
                               "path": "/path/to/video2.mp4",
                               "tracks": "a1"
                            }
                            ]
                           }
             ]
     }
   ]
}
```

How can I solve it?

**Comment by erankor** [comment]
Short answer: it is not supported. 
Longer answer: the iframe list generated by the module references ranges from the actual video segments. This is done in order to improve CDN caching - a user seeking forward can benefit from the segments that were already pulled to CDN by another user who is just watching. 
This means that when building the iframe list, the module has to know exactly were each frame will be located in the TS segment.
If you use some kind of filter on the audio, it won't know the size of the audio frames in advance (it doesn't make sense to run the filter on the entire video when the iframe list is requested...), and therefore it can't do it.

**Comment by Bragaman** [comment]
Thank you for your answer. Can you show me the another way to use video and audio from different mp4 and have in manifest EXT-X-I-FRAME-STREAM-INF?

And one more moment, I tried  to get iframe playlist in next way:
```
curl http://192.168.1.11:3030/hls/source.json/master.m3u8                                                                                                                                                  ─╯
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=11749763,RESOLUTION=3840x2160,FRAME-RATE=24.000,CODECS="hvc1.2.4.H150.90,mp4a.40.2"
index-f1-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=19453147,RESOLUTION=3840x2160,FRAME-RATE=24.000,CODECS="hvc1.2.4.H150.90,mp4a.40.2"
index-f2-v1-a1.m3u8
```
No Iframe playlist as was expected, but i can do so:
```
curl http://192.168.1.11:3030/hls/source.json/iframes-f2-v1.m3u8  
```
and its work, so can I modify manifest manually?
