### ISSUE TITLE
vod_segment_duration <10 vs 10 (default)

### ISSUE THREAD

**Issue by sergiyshutov** [kaltura/nginx-vod-module#116]
Segment 6 seconds is useful for hls? Like web-server performance and client happy? :) In vod module default duration is 10 seconds. But i have read this article https://www.dash-player.com/blog/2015/04/using-the-optimal-segment-length-for-adaptive-streaming-formats-like-mpeg-dash-hls/ wich says shorten is better.

**Comment by erankor** [comment]
Last time I checked Apple's recommendation is around 10 sec, which is the reason for the default value. We are currently working with 10 sec segments but with shorter segments at the beginning of the video. This enables the adaptive streaming logic of the player to kick in faster without having a larger manifest due to small segments.

**Comment by sergiyshutov** [comment]
Thank you very much :)

**Comment by sergiyshutov** [comment]
One more question about vod_bootstrap_segment_durations. Can i make like that?

vod_hls_segments.conf
vod_bootstrap_segment_durations 4000;
vod_bootstrap_segment_durations 4000;
vod_bootstrap_segment_durations 10000;
vod_bootstrap_segment_durations 4000;
vod_bootstrap_segment_durations 4000;
vod_bootstrap_segment_durations 10000;
-------- 1000 lines :)

nginx.conf
/hls/ {
    include "vod_hls_segments.conf";
}
It's very useful when you play video from middle, example. How you think, i can use that or this is not right?
Thanks.

**Comment by erankor** [comment]
Not sure I understand, you want the segment durations to be 4,4,10,4,4,10 in a loop ?
I don't understand how that's supposed to help when you seek, because you can drop on a segment that is 10 sec or on a segment that is 4 seconds, might as well have all segments at 4 seconds.
Anyway, I expect this parameter to work fine with a large number of values, there is some performance penalty to it since the server has to loop through these durations instead of just doing video_duration / segment_duration for example, but I think the difference in response time will be negligible.

**Comment by sergiyshutov** [comment]
Yes, in loop. 
But anyway thank you very much.
