### ISSUE TITLE
FLV repackaging

### ISSUE THREAD

**Issue by KuroNeko-san** [kaltura/nginx-vod-module#119]
It is possible to use FLV files as source for this module ? If not, can you make it possible ?

This needed for complex use with nginx-rtmp-module.

**Comment by erankor** [comment]
1. No
2. No, sorry. This is a not a small feature, and since I believe FLV will disappear from the face of the earth in a few years (along with flash player altogether), I prefer to invest my time on other tasks.
In our platform, for example, we changed the default container for transcoded videos from FLV to MP4 about 2-3 years ago.

**Comment by KuroNeko-san** [comment]
Thanks for answer, i respect your position.
