### ISSUE TITLE
Multi track audio m3u8

### ISSUE THREAD

**Issue by SlainTrue** [kaltura/nginx-vod-module#121]
Hello, 
I need generate a multi track audio playlist.m3u8. And also i need to get `trak.udta.name` atom.
How do I do, please tell me. 
Thx.

**Comment by erankor** [comment]
nginx-vod-module does not currently support the creation of a multi audio track master m3u8, it may be added in the future. But, since it does offer the ability to select tracks, it can support this use case if you create the master m3u8 yourself.
For example, if you have an mp4 file with 2 audio tracks, English and German, you could create a master manifest that looks like this:
`#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="eng",NAME="English",AUTOSELECT=YES,DEFAULT=YES,URI="http://nginx-host/path-to-mp4/index-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="ger",NAME="German",AUTOSELECT=NO,DEFAULT=NO,URI="http://nginx-host/path-to-mp4/index-a2.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=628837,RESOLUTION=688x320,CODECS="avc1.42c01e",AUDIO="audio"
http://nginx-host/path-to-mp4/index-v1.m3u8`

the a1 suffix means 'the first audio track' while a2 means 'the second audio track'. To get the correct values for bandwidth, codecs etc. you can just copy them from the master.m3u8 generated by nginx-vod-module.
The module does not process the udta atom, but if you have such a sample file, I'd love to have a look at it, please send me a link to eran.kornblau at kaltura dot com.

**Comment by SlainTrue** [comment]
Well, thank you.

**Comment by erankor** [comment]
Support for alternative audio representations was merged to master
