### ISSUE TITLE
DASH Manifest Template contain 0 duration segments

### ISSUE THREAD

**Issue by mlevkov** [kaltura/nginx-vod-module#1210]
Hello Eran,

We've recently stumbled upon an issue where the manifest for DASH is generated with the segment duration of `0` time. 

As such, a snippet from the DASH manifest:  
```text
 <SegmentTimeline>
                <S d="2169" r="11"/>
                <S d="0"/>
                <S d="2169" r="11"/>
                <S d="0"/>
                <S d="2169" r="11"/>
                <S d="0"/>
                <S d="2169" r="11"/>
                <S d="0"/>
                <S d="2169" r="11"/>
                <S d="0"/>
                <S d="2169" r="11"/>
                <S d="0"/>
                <S d="2169" r="11"/>
                <S d="0"/>
... < omitted for length >
</SegmentTimeline>
```
Here you find the complete DASH manifest -> (https://gist.github.com/mlevkov/268587e7b97aed5427f5a71558763e0f)
On the contrary, the HLS output is as expected with no segments with 0 duration. 

This breaks in various players that do not handle this issue well. PS4 and some versions of Shaka players are sensitive to the containment of the issue, in our findings.

**Comment by mlevkov** [comment]
@erankor Do you have any thoughts on this?

**Comment by erankor** [comment]
Zero duration segments are nearly always due to a mismatch between the GOP size and the segment duration.
For example, in your case, I assume you are using segment_duration = 2 sec (didn’t see the nginx.conf)
The GOP is slightly larger – 2.169, so after 12 segments, we get to 12 x 2.169 = 26.028 which is segment #14,
and segment #13 is empty.
In HLS, since the packager outputs a URL for each segment, it can omit those zero length segments (check the
manifest, you probably have there a URL for segment 12 followed by a URL for segment 14). However, in DASH, 
the segments are referenced by a running number, so it can’t really do that…

**Comment by mlevkov** [comment]
@erankor This issue, though still relevant, can be closed. It was resolved by targeting duration above 2 seconds, more like 4 seconds while keeping an accurate estimate and forcing GOP to start with the key frame.
