### ISSUE TITLE
Request to master manifest init open and parse all the subtitles

### ISSUE THREAD

**Issue by interlark** [kaltura/nginx-vod-module#1225]
In out case we got a lot of subtitles for a video, and request to master manifest initialize open and parse all of them. That's why the request(master.m3u8) to our server takes about 350-400 ms which is pretty long for 1 request. Is that possible to avoid parse all the subtitles files on request to master.m3u8?

PS:
Request to master.m3u8 cause open each subtitle and call media_format_t->parse_metadata(webvtt_parse). There's no need in it, isn't it? @erankor, gimme a hint, please, what direction to dig this issue?

**Comment by erankor** [comment]
The parsing is probably negligible, but reading many files can indeed take time, depending on the storage. The problem is that the module doesn't even know these are caption files, so it can't just skip it... 
What you can try, if you are using the mapping JSON, instead of passing a real path to the subtitles, send the string `empty` (https://github.com/kaltura/nginx-vod-module#source-clip). When the module sees this string, it treats it like an empty SRT file. This feature was initially added for playlists, in which not all videos may have all subtitles. 
If this will indeed work faster, you can configure a separate location in nginx.conf for master requests, and have it send some flag to the upstream that will make it return `empty` instead of real paths.

**Comment by interlark** [comment]
Thank you, you've been very helpful. Now we have separate configuration for master manifest and subtitles reads only when they're needed. I'm closing the issue.
