### ISSUE TITLE
Changing encryption mode, CTR, CBCS

### ISSUE THREAD

**Issue by qchroman** [kaltura/nginx-vod-module#1238]
Hello all,

I presume that by default when the DRM is enabled, the DASH is encrypted using AES-128 in CTR mode, and HLS (if sample-aes is used), uses AES-128 in CBC mode. Is it possible to define the encryption mode for the DASH so that it would output CBC encrypted fragments?

This would allow using the same fragments for DASH and HLS supporting different platforms with DASH + WV/PR and HLS + FP in the same CBC mode considering that all three now support CBCS.

I see there is a similar question asked (https://github.com/kaltura/nginx-vod-module/issues/985) and there is an answer about how to make the VOD module output segments in the same manner for DASH and HLS for better caching. But no comments on the DRM part.

It would be interesting to hear your thoughts and if this feature is somewhere on a roadmap?

Thank you.

**Comment by erankor** [comment]
I think it makes sense to add such a feature, but I have no plans to add it in the near future. 
But if you are going to use a config like the one in the ticket you mentioned, it probably doesn't matter, because you have two locations anyway (hls/dash), and you can choose from which one to pull the segments.

**Comment by qchroman** [comment]
True. Thank you. I think we can close this for now.
