### ISSUE TITLE
multiple source streaming

### ISSUE THREAD

**Issue by KuroNeko-san** [kaltura/nginx-vod-module#124]
Hello developers, thanks for this module.
I have a question - can i read multiple files to one stream?

Something like this:
http://example.com/vod-hls/file-1.mp4|file-2.mp4|file-3.mp4/index.m3u8

Or another way to create seamless stream from multiple files.
Thanks.

**Comment by erankor** [comment]
@KuroNeko-san , did you mean that these files will play as an adaptive streaming set ? In other words, that these mp4 files represent the same video rendered in different parameters (different bitrates, resolution, etc) ?
If so then the answer is yes, it's documented here https://github.com/kaltura/nginx-vod-module/#multi-url-structure.
If you meant that the videos should play in sequence (first file-1, then file-2 etc.) then this feature is currently not supported, we may add it in the future.

**Comment by KuroNeko-san** [comment]
Sequential play, yes. Like a seamless playlist.

Thanks for answer, @erankor

**Comment by erankor** [comment]
It shouldn't be too hard to add, however the way the module works, it will have to read the metadata (moov atom) of all the videos in order to generate the manifest, if the sequence is long this can become inefficient. 
Another similar feature that may be added at some point is what we call "simulated live", in which you have a playlist of a few mp4 files, and the server generates a live stream from it. So that all users that watch at the same time, get the same content, like a linear TV channel. 
Anyway, both features are currently not on our road map, but we may get to it at some point, I'm closing this issue for now.

**Comment by Classsic** [comment]
+1 for this feature, I can make a donation when this feature is enabled.

**Comment by erankor** [comment]
This feature is now supported - https://github.com/kaltura/nginx-vod-module/#playlist

**Comment by KuroNeko-san** [comment]
Oh, thanks! You are best!
