### ISSUE TITLE
How can I use nginx-vod-module behind a reverse proxy with re-written URLs?

### ISSUE THREAD

**Issue by benwilber** [kaltura/nginx-vod-module#133]
Example configuration:

VOD server:
```
server {
  listen 9000;

  location /hls {
    vod hls;
    vod_mode local;
    alias /var/www/html/vods;
  }
}
```

Web server:
```
server {
  listen 80;
  server_name example.com;

  location /video/hls {
    proxy_set_header Host $http_host;
    proxy_pass http://127.0.0.1:9000/hls;
  }
}
```

Requests to the VOD server directly work as expected:
```
# wget -q -O- http://127.0.0.1:9000/hls/bunny_med.mp4/index.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
http://127.0.0.1:9000/hls/bunny_med.mp4/seg-1-a1.ts
#EXTINF:10.000,
http://127.0.0.1:9000/hls/bunny_med.mp4/seg-2-a1.ts
...
#EXT-X-ENDLIST
```

However, requests through the public-facing reverse proxy do not contain the correct URL path:
```
# wget -q -O- http://example.com/video/hls/bunny_med.mp4/index.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
http://example.com/hls/bunny_med.mp4/seg-1-a1.ts
#EXTINF:10.000,
http://example.com/hls/bunny_med.mp4/seg-2-a1.ts
...
#EXT-X-ENDLIST
```

Notice that the path prefix is still `/hls` instead of `/video/hls`.  How would it be possible to ensure that the requested path is also reflected in the playlist paths?

Btw, this module is amazing.  Thank you so much for this!

**Comment by erankor** [comment]
To make sure I understand - you want it to work both directly against the VOD server and against the proxy server, right ? (because if all the access is through the proxy then you could have just changed the VOD server path to be /video/hls...)

If so, 2 solutions I can think of:
1. Disable absolute URLs on the VOD server - vod_hls_absolute_index_urls off
2. Configure the proxy server to replace example.com/hls with example.com/video/hls by using https://github.com/openresty/replace-filter-nginx-module
