### ISSUE TITLE
Prefetch whole movie (Or part of it)

### ISSUE THREAD

**Issue by shaharmor** [kaltura/nginx-vod-module#135]
Hi,

Were seeing low latency when using this module (With remote mode), obviously because the server has to query the origin and wait for its response.

I was thinking if its possible to add a config for prefetching X # of HLS segments when one is requested.
For example:
If a user requests seg-1-v1-a1.ts, the module will (behind the scenes) request the next X segments from the origin and cache it locally, so when the user requests seg-2-v1-a1.ts, it will already have it cached and the response will be quicker.

Is that possible?

**Comment by erankor** [comment]
Hi,

Sorry, we won't be adding this feature soon. Either way, I don't think such a feature should be part of nginx-vod-module, it had better be handled by some external module.

I think you can accomplish what you want without writing any native nginx code, by setting up another nginx server (or another nginx location on the same server) that will use proxy_pass to pull the segments from nginx-vod-module, and use proxy_cache to cache the segments. Once you do that, I'm quite sure you can set it up to perform prefetching by writing some nginx-lua code. The Lua script could see that seg-1-...ts is being pulled and issue a pull for seg-2-...ts. Once seg-2...ts is pulled, it will automatically enter the nginx cache and be available for download. The advantage of this approach over prefetching ranges of the mp4 files is that the packaging will be prepared in advance as well.
If you manage to set it up using this approach, please share the resulting nginx.conf here, so that it is available in case other people will want the same functionality

Thanks,

Eran

**Comment by hjone72** [comment]
Hi @shaharmor,
Wondering if you ever managed to get this going?
I am trying to achieve something similar and was hoping for a few pointers.

I apologize for opening such a dated issue.

Thanks,

**Comment by erankor** [comment]
We created it at some point with ngx_lua, here you go -
[prefetcher.zip](https://github.com/kaltura/nginx-vod-module/files/854196/prefetcher.zip)

**Comment by hjone72** [comment]
@erankor, this was very helpful! Thank you!
