### ISSUE TITLE
vod_base_url without host+scheme

### ISSUE THREAD

**Issue by doublex** [kaltura/nginx-vod-module#1353]
Question:
Is it possible to deliver absolute URLs without `host`+`scheme`?
E.g.: `/path/filename.mp4/index-v1-a1.m3u8`

My problem:
If `vod_base_url` is empty: Only `index-v1-a1-m3u8` is returned
If `vod_base_url` is `/`: Double-slash is returned:  `//path/filename.mp4/index-v1-a1.m3u8`

**Comment by doublex** [comment]
Thanks for the help. 
Best wishes!

**Comment by doublex** [comment]
The problem is that these two are equal:
````
vod_base_url '';
vod_base_url scheme://$http_host;
````

**Comment by erankor** [comment]
These are not the same, `vod_base_url ''` means relative URL, the second one is roughly equivalent to no vod_base_url at all.
But, looking at the code again, I think the fix is simply this - 
https://github.com/kaltura/nginx-vod-module/pull/1354
With this fix, you should be able to do something like this -
```
map $uri $base_uri {
        ~^(?<result>.*/)[^/]+$   $result;
        default                   '';
}

vod_base_url $base_uri;
```

**Comment by doublex** [comment]
@erankor 
I have applied you patch! Works like a charm!
````
vod_base_url  /;
````
Thanks a lot!!

**Comment by erankor** [comment]
Merged, thanks

**Comment by doublex** [comment]
No, I have to say thank you!
