### ISSUE TITLE
Serving dynamically generated mp4 files

### ISSUE THREAD

**Issue by bharathsekar** [kaltura/nginx-vod-module#1369]
Is there a way to serve a snapshot of a mp4 while a source is generating the video?

I get the following error when I try to access it via the vod url

http_vod_handle_read_completed: bytes read is zero while reading media header, client: XX.XX.XX.XX, server: , request: "GET /hls/LiveVideo/LiveVideo.mp4/index.m3u8 HTTP/1.1", host: "YY.YY.YY.YY"

Here's my configuration 

```
   # vod settings
   vod_mode local;

   # vod_fallback_upstream_location /fallback;
   vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
   vod_last_modified_types *;
   vod_base_url "https://YY.YY.YY.YY/";

   # vod caches
   vod_metadata_cache metadata_cache 512m;
   vod_response_cache response_cache 128m;

   # gzip manifests
   gzip on;
   gzip_types application/vnd.apple.mpegurl;

   # file handle caching / aio
   open_file_cache          max=1000 inactive=5m;
   open_file_cache_valid    2m;
   open_file_cache_min_uses 1;
   open_file_cache_errors   on;
   aio on;
```

**Comment by erankor** [comment]
No... in high level, there are two types of MP4s - regular and fragmented. 
In regular MP4, there's an atom of metadata and an atom with the actual compressed audio/video. If you append more frames, you have to rewrite the entire metadata atom. So, normally, encoders write the metadata atom only when they finish. Therefore, I would guess that your MP4 doesn't have this atom when you make the call, and that's the reason it fails.
Fragmented MP4, on the other hand, can be appended, but it's not supported by this module. The reason is that in fMP4 the metadata is spread across the file. The only way to seek efficiently is using some index table atom, and most fMP4s that I saw don't have it... (the index also has the same problem as the metadata atom in normal MP4 - the encoder will only write it when it finishes).

**Comment by bharathsekar** [comment]
Thanks for the clarification and the clean explanation of what an MP4 is. This helps. 
By the way. This is a great module. Kudos to the developers and maintainers.
