### ISSUE TITLE
Performance Data 

### ISSUE THREAD

**Issue by sridhard** [kaltura/nginx-vod-module#1400]
Hi,

I am testing the performance of ngnix-vod-module. 

Environment details:
1. Mapped Mode
2. Remote (Taking files from S3)
3. DRM enabled + DASH

I have tested a normal video play with DASH+DRM. From the browser network trace I have taken the segment urls.

In our current design we have pre-packaged the DASH files and  stored in AWS S3. In our current design S3 is serving approx 1.2 Gbps of data per sec. I want to achieve the same throughput with nginx-vod-module

For performance testing I am fetching a single segment from nginx-vod-module. I am using https://github.com/wg/wrk tool for performance test. Below is the command and results:
 
```javascript
./wrk -t12 -c400 -d30s  https://d3ls38oe6azegx.cloudfront.net/dash/sdrm/test28.json/fragment-10-f1-v1-x3.m4s
Running 30s test @ https://d3ls38oe6azegx.cloudfront.net/dash/sdrm/test28.json/fragment-10-f1-v1-x3.m4s
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   202.58ms   71.10ms   1.04s    64.08%
    Req/Sec   163.36     63.12   373.00     79.85%
  58686 requests in 30.10s, 795.21MB read
Requests/sec:   1949.94
Transfer/sec:     26.42MB
```

This is a 4 core machine on AWS. Both the server and the performance client are on AWS.

As per the results we are able to achieve 26MB/sec throughput. CPU usage is more than 90%.
I have disabled nginx access logs. Only error logs are enabled.

Can you please tell me whether this is the correct performance data for nginx-vod-module? I fell I am doing some mistake because 10MB/sec is very less throughput. With 10MB/sec we need to run more than 100 4-cpu machines to achieve 1.2gbps throughput.

Thanks

**Comment by sridhard** [comment]
I have checked this https://github.com/kaltura/nginx-vod-module/issues/491#issuecomment-267036606

As per this the performance is encrypt/decrypt 256MB/sec on a single core. But I am not able to get this performance

**Comment by erankor** [comment]
A few thoughts -
1. Enabling keepalive to s3 would probably provide a significant boost - need to:
    1. add an upstream for s3
    2. set keepalive on it
    3. set `proxy_http_version 1.1`
    4. set `proxy_set_header Connection ""`
2. You can try increasing `vod_cache_buffer_size`, since you don't use `vod_min_single_nalu_per_frame_segment`, the entire request will be calculated in memory before it starts being served to the client. A larger buffer can reduce the number of requests to S3
3. Worth adding a location with `vod_status`, you can use it to make sure the caches are working as expected in your setup & see what consumes most time

**Comment by sridhard** [comment]
@erankor thanks. I will try your suggestions.

Do you have any performance data? Can you pls give me some rough performance data?

**Comment by erankor** [comment]
Not really, it's been a long since I worked on this stuff... overall we are happy with the performance we get, but in our case only some of the content is encrypted, so it may not be comparable.
Btw, another thought - worth checking what speed/cpu usage you get on your server when you AES-encrypt using openssl.

**Comment by mlevkov** [comment]
@sridhard May I suggest that you put your packager behind the CDN and service your content from CDN? The packager will be facing the load balancer and CDN will hit the load balancer. This way you can get maximum throughput without much of an issue.

**Comment by sridhard** [comment]
@mlevkov yes I have already tried it with CDN. But we need 2 gpbs throughput without cdn

**Comment by mlevkov** [comment]
Fair enough, please post here what you come up with.
