### ISSUE TITLE
Try files howto?

### ISSUE THREAD

**Issue by mesouug** [kaltura/nginx-vod-module#143]
Good day.

First of all huge thank you for awesome module.
I have small question. Current setup includes NFS server with vod files in /media/nas1 /media/nas2 /media/nas3 etc...

So how do I instruct vod module to search for specific video file in multiple root locations?

Thanks,
Mikhail.

**Comment by erankor** [comment]
Unfortunately, try_files will not work in this case, since it will lose the original file name of the URI (e.g. for HLS can be index.m3u8 or seg-1.ts). I believe the only way to accomplish what you asked for with the current code base is to use nginx's if statement. You may have already bumped into articles that discourage the use of if in nginx, but since try_files won't work here, don't think there's any other solution.

I tried it now and got it to work with the following config - 
file 1 - /usr/local/nginx/html/test/1/1.mp4
file 2 - /usr/local/nginx/html/test/2/2.mp4

nginx.conf:
```
                location ~ ^/testtry/(.+)/(.+)$ {
                        if (-e /usr/local/nginx/html/test/1/$1) {
                           rewrite ^/testtry/(.+) /testtryint/1/$1 last;
                        }
                        if (-e /usr/local/nginx/html/test/2/$1) {
                           rewrite ^/testtry/(.+) /testtryint/2/$1 last;
                        }
                        return 404;
                }

                location ^~ /testtryint/ {
                        internal;
                        vod hls;
                        vod_mode local;
                        alias /usr/local/nginx/html/test/;
                }
```

hitting /testtry/1.mp4/index.m3u8 serves the first file and /testtry/2.mp4/index.m3u8 serves the second file. 
The way it works is that the /testtry/ location uses regular expression to split the URI into path+basename, and then checks all possible prefixes (in this case only 1 & 2) until it finds the file in one of them. It then rewrites the URI to testtryint with the corresponding prefix. testtryint simply serves the file, as it already got the right prefix.

**Comment by erankor** [comment]
One small correction, when working with absolute URLs (the default) the second location cannot have the 'internal' directive, since the URLs to the TS segments will reference it directly. They won't go through the first location, which has a bonus of better performance

**Comment by erankor** [comment]
Hi @mesouug, did you try it out ? can we close this issue ?

**Comment by mesouug** [comment]
Good day.

Thank you for explanation. We discussed and decided to go with Mapped variant. Because we have more then 10 drives and > 10 IF in nginx is too much.
I think this ticket will help other people. :)

Thanks,
Mikhail.
