### ISSUE TITLE
Weird Time skip when using vod module dash in combination with shaka player

### ISSUE THREAD

**Issue by thankarezos** [kaltura/nginx-vod-module#1467]
When i play dash videos from shaka i get time skips on specific parts (although it doesn't happen on vlc). I realized that how I am encoding the file with ffmpeg because if I do it with kmc.kaltura.com it doesn't have the problem. The thing is that whatever I tried with ffmpeg I cant seem to make it work. Is there a specific parameter I should use?. What's the correct ffmpeg command to not have these weird problems?

**Comment by erankor** [comment]
The problem is most likely related to key frame positions, in our system we are forcing key frames every 2 seconds, using `-force_key_frames expr:'gte(t,n_forced*2)'`. When forcing a key frame every 2 sec, you can set the segment duration to 4/6 (or any other number that is a multiple of 2 seconds), and each segment will start with a key frame.

**Comment by thankarezos** [comment]
I think that did the job thank you.
