### ISSUE TITLE
backward shift

### ISSUE THREAD

**Issue by kuznetcoff777** [kaltura/nginx-vod-module#1469]
According to manual:

`shift - can be used to apply a timing shift to one or more streams. The structure of the parameter is: v<vshift>-a<ashift>-s<sshift> For example, .../shift/v100/... will apply a forward shift of 100ms to the video timestamps.`

How to implement backward shift? A attempted to make /shift/-s5000/ and /shift/s-5000/ - i get 400 error ...

**Comment by kuznetcoff777** [comment]
@erankor, can you, please, explain?

**Comment by erankor** [comment]
Backward shift is not supported, the reason is that it will most likely generate negative timestamps at the beginning of the stream, and many players choke on it. However,, since the absolute values of the timestamps are usually irrelevant, what you can do is instead of applying a negative shift to track X, apply a positive shift to all tracks except track X.
