### ISSUE TITLE
HLS encryption key over HTTPS?

### ISSUE THREAD

**Issue by Zilog8** [kaltura/nginx-vod-module#147]
I've gotten HLS working with encryption with the following config:

```
worker_processes 1;
events {
    worker_connections 1024;
}
    
http {
    include           mime.types;
    default_type   application/octet-stream;

    sendfile   on;

    keepalive_timeout   65;

    server {
        listen    80;
        server_name    localhost;

        location / {
            root   html;
            index   index.html index.htm;
        }

        location /vod {
            vod hls;
            vod_mode local;
            vod_secret_key password;
            root /home/ngx/video;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
```

However, I can't seem to find any information on how I'd go about having the AES key served through HTTPS (Not much point in encrypting the stream if you're going to send the key along in cleartext).

**Comment by benwilber** [comment]
you can just serve it over ssl like you would normally:

```
server {
  listen 443 ssl;
  ssl_certificate <path>;
  ssl_ssl_certificate_key <path>;

  location /vod {
    vod hls;
    vod_mode local;
    vod_secret_key password;
    root /home/ngx/video;
  }

  ...

}
```

**Comment by Zilog8** [comment]
Hmm.., that is true, but if you're going to serve the segments over SSL anyway it kind of defeats the purpose of using HLS AES-128 encryption in the first place. From my (granted, quite limited) understanding, the purpose of the HLS AES-128 scheme is to allow the client to use the slower-but-secure HTTPS only once (to obtain the segment encryption key), and then afterwards obtain the encrypted media segments over faster HTTP.

**Comment by erankor** [comment]
Currently, sending the key over HTTP and the segments over HTTPS is not supported, but it's a relatively small effort to add support for this. 
We are making a different use of the encryption - we are using it to implement authorization with static URLs. The idea is that the manifest URL and the encryption key URL require an expiring security token, but the segments do not. Since the segments are encrypted, even if someone fetches them, he won't be able to do anything with it. This enables transparent caching of the segments by proxies, the manifest and key won't be cached, but they compose only a small fraction of the traffic.
There is a sample config for this here: https://github.com/kaltura/nginx-secure-token-module/#encrypted-hls-with-token-security-on-the-encryption-key

**Comment by Zilog8** [comment]
Ok. Honestly, most of that went over my head :-)     In that case, I'll just do everything over HTTPS and disable the AES-128 encryption. I just figured I'd ask, in case there was way of doing it and I had missed it. Anyway, thanks for this awesome module!
