### ISSUE TITLE
Enable multi bitrate streaming

### ISSUE THREAD

**Issue by ksrigo** [kaltura/nginx-vod-module#153]
Hi,

I just come to install kaltura-nginx vod module. I'm using the local mode, it seems to work fine but I'm trying to enable the multiple bitrate for the adaptive streaming through HLS, I can't find anywhere the details to activate it. 
In the feature list of this module, it says that Adaptive bitrate is supported.

Thank you

**Comment by erankor** [comment]
You need to have several renditions of the same video, and then generate a single URL for the whole set as documented here: https://github.com/kaltura/nginx-vod-module/#multi-url-structure.
Basically if the HLS URL of the first video is:
http://domain/vod/1.mp4/index.m3u8
And the HLS URL of the second video is:
http://domain/vod/2.mp4/index.m3u8
Then the following URL will return a stream containing both as an adaptive set:
http://domain/vod/,1,2,.mp4.urlset/master.m3u8

**Comment by ksrigo** [comment]
If I understant, to have multiple bitrate for the same video, I have to rencode my self the video (e.g: using ffmpeg) to different quality then use the "multi-url-structure" to build master playlist. Is it right?

**Comment by erankor** [comment]
Correct, although unless you are a video expert, I would recommend using our platform to do that, since it's not trivial to do it correctly. You can either use the commercial Kaltura SaaS platform (we offer a limited free trial) or the free Community Edition Kaltura platform

**Comment by ksrigo** [comment]
Thank you. I ll ck it

**Comment by Classsic** [comment]
Hi, this works for dash?? I try with the same structure for dash, but doesn't work, is .../master.mpd? Thanks in advance.

**Comment by erankor** [comment]
it's manifest.mpd, see https://github.com/kaltura/nginx-vod-module/#filename-structure

**Comment by Classsic** [comment]
Ok, thanks. This, work, but the change bitrate is really slow, I did try test on lan enviroment with the player shaka, and the program wondershaper for limit the bandwith. All works as expected, but the change between the qualities take so long. This is because cache, cpu limit, I-Frame, or length of chunks? It's ok post here, or open another issue.?
Thanks.

**Comment by erankor** [comment]
In general, better open separate issues for separate topics. 
Regarding your specific question, the server does not control the bitrate switches, the player does. The only thing the server can do that may affect it is the size of the segments. The default in nginx-vod-module is 10 sec which is the recommended value for HLS, in DASH you'll probably want to reduce it to 4 sec (using vod_segment_duration). 
Note that whatever segment size you chose, it's highly recommended that it will be a multiple of the GOP size of your video files, so that segments will start with a key frame. All the videos we transcode in our system have a 2 sec GOP, this enables us to use 4 sec segments in DASH and 10 sec segments in HLS and still have all segments aligned to key frames.

**Comment by Classsic** [comment]
Ok,I 'll try different gop-sizes. I wanna talk with you about #124. Tellme how can contact you.
Thanks.

**Comment by erankor** [comment]
you can email me at eran.kornblau at kaltura dot com

**Comment by quydox** [comment]
Hello,

Means I must generate real file mp4 for 1080p, 720p first, then use multi bitrate url structure?

Thanks,

**Comment by erankor** [comment]
Yes
