### ISSUE TITLE
Playback on native android device doesn't go beyond 7s

### ISSUE THREAD

**Issue by soufrk** [kaltura/nginx-vod-module#158]
Just like before, the configuration remains simple and straight forward,
```
# VOD Module Configurations
    location /content {
        vod hls;
        vod_mode local;
	vod_moov_cache moov_cache 512m;
	types {
	    application/vnd.apple.mpegurl m3u8;
	    video/mp2t ts;
	}
       root /var;
       #gzip on;
       #gzip_types application/vnd.apple.mpegurl;
    }
```
This configuration delivers correct playback in Web-based players (on Windows). However, playback on native android browser won't go beyond 7s.
Any clues, on what might be wrong?
Just to keep things clear HLS published through nginx-rtmp module works fine on the android device.

**Comment by erankor** [comment]
As far as I know, HLS support in Android is limited, some devices don't support it at all, some devices don't play it well. For this reason, we are using our own Android HLS player instead of relying on what the operating system has. That project is open-source as well - https://github.com/kaltura/player-sdk-native-android

Btw, on which device did you see this behavior ?

**Comment by soufrk** [comment]
Is HLS support Andriod limited? I saw it "supports", in HLS page on Wikipedia.
Anyhow, it seems to be working fine in newer device. Initially, I was using a XOLO A1000 running Andriod 4.1.1, Kernel 3.4.0. You might not have heard of it.
