### ISSUE TITLE
Multicore support

### ISSUE THREAD

**Issue by shaharmor** [kaltura/nginx-vod-module#183]
Hi,

Does this module support multicore for the transmuxing step?

**Comment by erankor** [comment]
A request always runs in a single thread, so no. 
However, I don't really see the point in doing this, the packaging is very light weight in terms of CPU, there are no heavy calculations there. The bottleneck will practically always be the IO (in case of local files) or the network. We have servers that push 2Gbps of packaged HLS/HDS content and their CPU doesn't cross the 5% utilization. 
The only two operations in this module that are more CPU intensive are:
1. Audio filtering (for example when using the playback rate control) - the filtering requires the decoding and re-encoding of the audio. In this case, it actually does use multiple threads, thanks to support by libavcodec
2. Encryption (for DRM / HLS encryption) - since openssl supports AES-NI this operation is very fast. On my test server, I managed to encrypt ~250 MB/s with a single thread

**Comment by anirut** [comment]
Hi erankor,

I would like to see you config that you can re-package HLS at 2Gbps.

**Comment by erankor** [comment]
The optimizations we employed are documented here: https://github.com/kaltura/nginx-vod-module/#performance-recommendations
