### ISSUE TITLE
Example server config for mapped mode

### ISSUE THREAD

**Issue by KuroNeko-san** [kaltura/nginx-vod-module#216]
Dear all,
can any one give me simple nginx.conf and example url for testing "mapped mode" ?
For example, a have local files on /data/kaltura/video[1,2,3].mp4 and i want to play them using feature "playlist" from mapped mode.

I read README.md and prepare playlist.php from /test/ folder, this file produce json string like a

```
{"discontinuity":true,"playlistType":"vod","durations":[21790,557129,306411],"sequences":[{"clips":[{"type":"source","path":"\/data\/kaltura\/video1.mp4"},{"type":"source","path":"\/data\/kaltura\/video2.mp4"},{"type":"source","path":"\/data\/kaltura\/video3.mp4"}]}]}
```

but i have no idea what i'm must doing with it.
Thanks.

**Comment by erankor** [comment]
There is a sample config here: https://github.com/kaltura/nginx-vod-module/#mapped-configuration
Note that in mapped mode, nginx-vod performs an HTTP request in order to get the JSON, so you have to configure some web server to serve your JSON file. In the case of this sample config, any request to the `vod hls` location will trigger a request with the same uri to the kalapi upstream, this request should return the JSON. 
If what you want is to work with static JSON files, you simply need to point the kalapi upstream so that the request will hit back the same nginx server on some other location that is serving the JSON file.

**Comment by erankor** [comment]
Hi @KuroNeko-san, did you get it working ? can this issue be closed ?

**Comment by KuroNeko-san** [comment]
Sorry for silence, i was kinda busy with other things.
You're software is great, all works fine. Thanks!

Issue closed.

**Comment by erankor** [comment]
Glad to hear, thanks for the update
