### ISSUE TITLE
mp4 MEDIA_ERR_SRC_NOT_SUPPORTED in Chrome with codecs="avc1.4d401e"

### ISSUE THREAD

**Issue by GoodGame** [kaltura/nginx-vod-module#246]
Hello!

We have MEDIA_ERR_SRC_NOT_SUPPORTED with mp4 in Chrome (50.0.2657.0 dev-m (64-bit)) with codecs="avc1.4d401e" in manifest.mpd.

Same manifest.mpd plays fine in Safari and FireFox.

If we use "old" codecs="avc1.42c015" all works fine.

In chrome://media-internals/ we have:
00:00:00 382	error	Media segment did not begin with key frame. Support for such segments will be available in a future version. Please see https://crbug.com/229412.
00:00:00 382	error	media::MediaSourceState::Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=1.#INF

We tested at:
http://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/
url is:
http://91.230.60.159/vod/C3/LQ.mp4/manifest.mpd

ps. Latests nginx/1.9.12 and nginx-vod-module from git.

Any help?

**Comment by nknighter** [comment]
+1

**Comment by GoodGame** [comment]
Additional information of source mp4:
```
$ ffprobe LQ.mp4
ffprobe version 2.8.git Copyright (c) 2007-2015 the FFmpeg developers
  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-16)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --mandir=/usr/share/man --enable-shared --disable-static --enable-gpl --enable-version3 --enable-libmp3lame --enable-libx264 --enable-libfaac --enable-libmp3lame --enable-librtmp --enable-nonfree --enable-libvpx --enable-libvorbis --enable-libtheora --enable-gpl
  libavutil      55.  2.100 / 55.  2.100
  libavcodec     57.  3.100 / 57.  3.100
  libavformat    57.  2.100 / 57.  2.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6.  8.100 /  6.  8.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'LQ.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2011-08-13 05:49:20
    encoder         : Lavf54.63.104
  Duration: 00:22:33.77, start: 0.000000, bitrate: 345 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 309 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      creation_time   : 2011-08-13 05:49:20
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 22050 Hz, mono, fltp, 31 kb/s (default)
    Metadata:
      creation_time   : 2011-08-13 05:49:20
      handler_name    : SoundHandler

```

**Comment by erankor** [comment]
From what I can see, the second fragment indeed does not begin with a keyframe, as the error message says. There are two ways to solve it:
1. Add the setting `-force_key_frames "expr:gte(t,n_forced*2)"` to the ffmpeg command line. This will force a keyframe exactly every 2 seconds. Btw, I see you currently use the default 10 sec fragments,  if that is intentional (usually in DASH smaller fragments are used), you can replace the value 2 in that expression with something higher (e.g. 5 or 10)
2. Add the setting `vod_align_segments_to_key_frames on` to nginx conf, this will make nginx-vod align the fragment boundaries to key frame positions.
I would recommend doing both, if you only do 2 and the keyframes are far apart it can cause a large discrepancy between the fragment duration that is reported in the manifest and the actual duration. In normal playback this will probably not cause any noticeable effect, but it may cause issues with seek.

**Comment by GoodGame** [comment]
Many thanks `vod_align_segments_to_key_frames on` was what we need.
