### ISSUE TITLE
dash and HLS with adaptive bitrate in kaltura

### ISSUE THREAD

**Issue by anurag-dixit** [kaltura/nginx-vod-module#247]
Hi,

Firstly congrats and thanks for an awesome module works beautifully.

Can anyone give example for dash and HLS with adaptive bitrate URL in kaltura
Single bitrate is working perfect.
http://<domain>:88/dash/p/103/sp/10300/serveFlavor/entryId/0_mimph5ki/v/2/flavorId/0_4xsnyc1f/forceproxy/true/name/a.mp4/manifest.mpd

Best
Anurag

**Comment by erankor** [comment]
Adaptive bitrate for your sample URL would like something like this:
```
http://domain:88/dash/p/103/sp/10300/serveFlavor/entryId/0_mimph5ki/v/2/flavorId/0_,4xsnyc1f,abcd1234,/forceproxy/true/name/a.mp4.urlset/manifest.mpd
```

(assuming the second flavor id is 0_abcd1234)
You can of course add more flavors this way as needed. Also, this sample assumes the version of all URLs is the same (2 in this case), if that is not the case you have to move the commas to cover the v/xx part as well.
But since you are using Kaltura, you don't have to bother with all this, you can just use the playManifest API which will redirect to the correct URL, should be something like:
```
http://domain:88/dash/p/103/sp/10300/playManifest/entryId/0_mimph5ki/format/mpegdash/a.mpd
```

**Comment by anurag-dixit** [comment]
Thanks, this solves my problem.
