### ISSUE TITLE
Dash delivery -  language information missing in the manifest

### ISSUE THREAD

**Issue by marzipi** [kaltura/nginx-vod-module#248]
Dear Erankor,

Your module extracts from the mp4 containers all needed information to build on the fly the mpd manifest,  but the language is not extracted in the Representation's tag.

In my case, Nginx manifest URL is built automatically by Kaltura according to the contentId and its flavorIds.

Will you add this feature?  or I may miss something in Kaltura.

Thank you for all.
Pierre

You can find an example below where  lang="en" and  lang="fr"  are missing for the 2 audio tracks.
 
`
<?xml version="1.0"?>
<MPD
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
    type="static"
    mediaPresentationDuration="PT6208.277S"
    minBufferTime="PT4S"
    profiles="urn:mpeg:dash:profile:isoff-main:2011">
  <Period>
    <AdaptationSet
        id="1"
        segmentAlignment="true"
        maxWidth="720"
        maxHeight="304"
        maxFrameRate="23.976">
        <SegmentTemplate
            timescale="1000"
            media="http://10.x.x.x:8080/content/media/20160303/0/0_zd8uau8p_0_,du35s26p,4eswrg1s,wlrf2v7z,8pjqn74c,_2.mp4.urlset/fragment-$Number$-$RepresentationID$.m4s"
            initialization="http://10.x.x.x:8080/content/media/20160303/0/0_zd8uau8p_0_,du35s26p,4eswrg1s,wlrf2v7z,8pjqn74c,_2.mp4.urlset/init-$RepresentationID$.mp4"
            startNumber="1">
            <SegmentTimeline>
                <S d="3500"/>
                <S d="4000" r="1550"/>
                <S d="625"/>
            </SegmentTimeline>
        </SegmentTemplate>
      <Representation
          id="f3-v1"
          mimeType="video/mp4"
          codecs="avc1.42c01e"
          width="480"
          height="208"
          frameRate="23.976"
          sar="1:1"
          startWithSAP="1"
          bandwidth="598759">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"/>
        <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95"/>
      </Representation>
      <Representation
          id="f4-v1"
          mimeType="video/mp4"
          codecs="avc1.42c01e"
          width="720"
          height="304"
          frameRate="23.976"
          sar="1:1"
          startWithSAP="1"
          bandwidth="798194">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"/>
        <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95"/>
      </Representation>
    </AdaptationSet>
    <AdaptationSet
        id="2"
        segmentAlignment="true">
      <AudioChannelConfiguration
          schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
          value="1"/>
        <SegmentTemplate
            timescale="1000"
            media="http://10.x.x.x:8080/content/media/20160303/0/0_zd8uau8p_0_,du35s26p,4eswrg1s,wlrf2v7z,8pjqn74c,_2.mp4.urlset/fragment-$Number$-$RepresentationID$.m4s"
            initialization="http://10.x.x.x:8080/content/media/20160303/0/0_zd8uau8p_0_,du35s26p,4eswrg1s,wlrf2v7z,8pjqn74c,_2.mp4.urlset/init-$RepresentationID$.mp4"
            startNumber="1">
            <SegmentTimeline>
                <S d="3500"/>
                <S d="4000" r="1550"/>
                <S d="777"/>
            </SegmentTimeline>
        </SegmentTemplate>
      <Representation
          id="f1-a1"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="48000"
          startWithSAP="1"
          bandwidth="111782">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"/>
        <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95"/>
      </Representation>
      <Representation
          id="f2-a1"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="48000"
          startWithSAP="1"
          bandwidth="131234">
        <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
        <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"/>
        <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95"/>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
`

**Comment by erankor** [comment]
Hi,

Multiple audio tracks are indeed currently not supported, we will probably add it at some point, but I don't have an ETA for that. We don't have a design for it yet, but I think it will most likely build on the mapping JSON - we will add the ability to specify the language of each sequence in the JSON. We may also add some code to take it by default from the MP4, which is in my understanding what you're asking for, but the JSON offers more flexibility (e.g. the languages can be in separate files).
Btw, as I recall, it's not just about outputting the language in the MPD, we also need to change it so that each language gets its own `AdaptationSet` (currently each audio track is a `Representation`)

Eran

**Comment by marzipi** [comment]
Thank you Eran,

You are totally right each language should have its own AdaptationSet.
But in our case, the audio  and the video tracks are in a separate MP4 file and Kaltura generates the manifest url according to. (audio bit rate has to be a bit different between each other otherwise Kaltura doesn't include all audio 's flavorid in the manifest...)

Extracting the language from the mp4 metadata file would be the "easiest" solution as it needn't to be managed by a third party service (a Json in the key server you mentioned).

Thank you again for your support
Pierre

**Comment by erankor** [comment]
For most of our use cases, the JSON approach makes more sense, since it will enable users to upload several different files and just tell our system (using our API) which one is English, Spanish etc. If we take it from the MP4 we need to ask the users to make sure the MP4 files have the correct language indicators on their tracks, which may be more complicated for them.
But anyway, both options are currently not supported. I assume we will add at least the JSON support some time in the near future, but don't have an ETA for that.
Closing this issue for now.

Btw, regarding what you wrote about the need for a different bitrate, it's configurable, you can set `vod_duplicate_bitrate_threshold` to 0 to disable it. Once the module will "know" that the different audio tracks represent different languages, we will also change it so that it won't remove duplicate bitrates across languages.

**Comment by erankor** [comment]
Support for alternative audio representations was merged to master

**Comment by marzipi** [comment]
Dear Eran,

Thank you for your notification and for adding this feature.

Kind regards
Pierre
