### ISSUE TITLE
HLS video secure

### ISSUE THREAD

**Issue by xXxSPYxXx** [kaltura/nginx-vod-module#258]
Hi! I have nicely installed nginx-vod-module. Now my video has played, but i want protect it by DRM or AES. How i can make it?I am need step-by-step guide.

**Comment by erankor** [comment]
To enable AES, you need to add to your configuration:
```
vod_secret_key "SomeSecret$vod_filepath";
vod_hls_encryption_method aes-128;
```
Just change `SomeSecret` to some random string, this is used as a seed to generate the encryption key.

DRM is not so simple, you will need to write some code for it, it's explained here: https://github.com/kaltura/nginx-vod-module/#drm.

**Comment by xXxSPYxXx** [comment]
Its work, but only for new video. Old videos has index.m3u8 files whis out AES string. How i can regenerate index.m3u8 files for disable/enable encryption?

**Comment by erankor** [comment]
If you have caching enabled, you can restart nginx to clear the cache

**Comment by erankor** [comment]
@xXxSPYxXx, can I close this issue ?

**Comment by hmoraes** [comment]
I have a question. If my files (mp4) are already encrypted, how can I use them to generate the encrypted hls without having to decrypt them?

Because I saw on this link (https://ffmpeg.org/pipermail/ffmpeg-devel/2015-December/185220.html) it would be possible to do this

**Comment by erankor** [comment]
It is not possible with HLS since the encryption scheme is different - HLS uses AES-128 or SAMPLE-AES, while the MP4 encryption uses AES-CTR.
With DASH/MSS it will happen automatically - if the decryptionKey passed to nginx-vod-module matches the encryption key returned from the DRM server, the module will "passthrough" the encrypted data

**Comment by erankor** [comment]
Just noticed my answer may have not been clear - the module does support automatically decrypting + encrypting the media, you don't have to do it manually, but it can't use the already encrypted media as is in the case of HLS

**Comment by hmoraes** [comment]
Hi @erankor 

I get it, I thought it would work with HLS as well. Another question: 

Is there any way to configure vod_secret_key to change over time? Using some time variable (date, time, etc.)

Thanks for your reply

**Comment by erankor** [comment]
Technically, you can use any nginx variable you want, but consider that if it changes then a user who is watching the stream will get an error - he pulls encryption key A and then a segment encrypted with encryption key B. Also, if there caching in your setup (e.g. CDN) it becomes an even greater mess, since the errors are not limited to the time the encryption key changes, they can continue for a long time until the cache expires.
It would be better to protect the URLs with expiring tokens, but have the encryption key constant

**Comment by hmoraes** [comment]
I see. I will take a look in expiring tokens.

Thanks again!
