### ISSUE TITLE
could not build the variables_hash

### ISSUE THREAD

**Issue by Boburjon** [kaltura/nginx-vod-module#259]
> nginx: [emerg] could not build the variables_hash, you should increase either variables_hash_max_size: 512 or variables_hash_bucket_size: 64
nginx: configuration file /etc/nginx/nginx.conf test faile

Hello!
What could be the problem?

**Comment by erankor** [comment]
See this: http://nginx.org/en/docs/hash.html
In short, you probably have too many variables (due to custom modules that you installed) for the default values of variables_hash_max_size / variables_hash_bucket_size, so you need to increase one of these values. I would recommend increasing the max_size (e.g. to 1024), and leave the bucket size at its default value, so that the hash values would fit into a single processor cache line

**Comment by Boburjon** [comment]
Thanks you)) it work's!!
