### ISSUE TITLE
remote mode - change location

### ISSUE THREAD

**Issue by sdannyb** [kaltura/nginx-vod-module#287]
Hi,

We are using VOD module, remote mode to stream audio in MPEG-DASH. The original audio files are on the remote server.

When the client is calling NginX, the URL is in the format http://machine/streamer/filename.mp4/manifest.mpd

The VOD module then calls the upstream server:
http://upstream server/streamer/filename.mp4/manifest.mpd.

The problem is that the upstream server is 3rd party, and does not have endpoint "streamer".
So we want the VOD module to call something like:
http://upstream server/otherLocation/filename.mp4/manifest.mpd

We cannot have NginX url with "otherLocation".

Can this be achieved using the VOD configuration?

below parts of the confg file:

   upstream streamer {
        server CSServer:29333;
    }

	vod_child_request_path /child_request/;

location ~ /streamer { 
        set $em_method http;
        set $em_port 80;
        set $em_localServerName 127.0.0.1;

        sub_filter 'http://$host/'  '$em_method://$em_localServerName:$em_port/';
        sub_filter 'http://$host:$server_port/'  '$em_method://$em_localServerName:$em_port/';
        sub_filter_once off;
        sub_filter_types "application/dash+xml";
		
        vod dash;
        vod_mode remote;
        vod_upstream streamer;

        expires 100d;
        add_header Cache-Control "no-cache, no-store";
        add_header Access-Control-Allow-Origin "*";
	
    }

location ^~ /child_request/ {
        internal;
        vod_child_request;
    }		
	

Thanks.

**Comment by erankor** [comment]
I can see from the config that you pasted that you're using an old version, e.g. `vod_child_request` was removed several months ago. In the recent versions, the module uses a standard nginx proxy_pass to issue the upstream requests, this makes it possible to configure what you need.
In order to upgrade your configuration, have a look here: https://github.com/kaltura/nginx-vod-module/blob/master/CHANGELOG.md#20151215---removed-the-upstream-module-implementation there's a list of the directives that were removed along with the replacement

**Comment by erankor** [comment]
Hi @sdannyb, did you upgrade to the latest version ? can this be closed ?

**Comment by sdannyb** [comment]
yes thanks alot
