### ISSUE TITLE
Live streaming is possible ? 

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#320]
By using this Nginx-vod-module, live streaming can be done for hls/dash ? As i read that, the mp4 files we are giving as input to module as to be a complete file and module used to read mp4 atom data at first itself. So is it possible to do live streaming

**Comment by Natarajan92** [comment]
Live streaming is possible with this module ?

**Comment by erankor** [comment]
It is possible to generate simulated live streams, i.e. a live stream from a series of vod files. There are a few JSON samples in the readme, and this sample PHP file: https://github.com/kaltura/nginx-vod-module/blob/master/test/playlist.php

**Comment by Natarajan92** [comment]
Thank you

**Comment by Natarajan92** [comment]
For us, the input be real time live streaming of live channels, with those live channel as input it is possible to do on-the-fly conversion ?

**Comment by erankor** [comment]
We have a separate project that pulls HLS live streams and feeds them into this module in order to:
1. Add support for DVR
2. Repackage to all other protocols, DRM etc.
This work is currently in progress, it is not production ready yet.

**Comment by Natarajan92** [comment]
Ok!, It's great to hear on live streaming progress for production level.

**Comment by Natarajan92** [comment]
As of now closing this issue, Once the live streaming is ready for production level will reopen it.

**Comment by Natarajan92** [comment]
Hi Eran,

Is the project is production ready for doing real time live streaming along with DRM encryption ?

**Comment by erankor** [comment]
it is for HLS, not for DASH yet

**Comment by Natarajan92** [comment]
HLS with PlayReady DRM ? and is the project is available in github

**Comment by erankor** [comment]
nginx-vod-module does not support PlayReady HLS (btw, afaik there are 4 different standards for how to package PlayReady HLS) but it does support FairPlay HLS, which is probably much better since it works natively in Safari /iOS without plugins/3rd party SDKs. 
We didn't test the combination of live with HLS FairPlay yet, but it should work (we tested regular HLS and HLS AES)
The project is here: https://github.com/kaltura/livedvr, but unfortunately from what I see it is lacking some documentation...

**Comment by Natarajan92** [comment]
Oh! Thnak you Eran, I will check on that project page. And at the mean time can you say me those 4 different standards (afaik there are 4 different standards for how to package PlayReady HLS) so i will try to know about it, which might be useful for me at present

**Comment by erankor** [comment]
IIRC they are:
1. Microsoft
2. Discretix
3. Inside secure
4. Buy DRM

In my understanding, in the early days, DRM required the use of some secure player provided by one of these vendors. Since Apple requires that HLS will be used to deliver the media (otherwise they don't approve the app) these vendors had to invent some way to package PlayReady content in HLS, to be consumed by their players. Now, either because the standard that Microsoft defined costed money, or because it arrived at a later time, what happened was that each vendor invented its own.
But anyway, now that FairPlay is available, I think that is best solution for Apple devices.

**Comment by Natarajan92** [comment]
Yes Eran you are right, Its the best solution for apple devices but for Set-Top-Boxes Fairplay is not supported so we are forced to use Playready DRM and we are waiting for FairPlay License to use

**Comment by Natarajan92** [comment]
Hi Eran, 

Is there any update on the project for doing real time live streaming along with DRM encryption (For Mpeg-Dash)?

**Comment by erankor** [comment]
no update, still in the works

**Comment by Natarajan92** [comment]
Hi Eran, 

We are trying for continuous live stream. 

Inputs :  Live udp stream is transcoded and segmented as 4sec mp4 files 
output : Live stream in HLS/DASH with cenc encryption

We are executing set-up in mapped mode configuration. The JSON file will be updated every 4sec by using your sample playlist.php.

Files on server : 
Inside Test folder, there will be segmented mp4 files, Test.json and Test.js. Mp4 files will keep on growing (s001.mp4,s002.mp4,s003.mp4 and so on). Test.json file will be updated every 4sec 

Nginx config as below 

location ~ ^/enc/([^-]+)-.* {
vod dash;
vod_mode mapped;
vod_media_set_map_uri enc/$1.json;

Issues we face :  

Access Log - "GET /enc/Test/Test-/fragment-4-v1-x3.m4s HTTP/1.1" 404

Debug Log - 
2017/12/27 14:54:36 [error] 17016#17016: *1052 ngx_http_vod_validate_streams: no matching streams were found, probably invalid segment index while sending to client, client: x.x.x.x, server: localhost, request: "GET /enc/Test/Test-/fragment-4-v1-x3.m4s HTTP/1.1", host: "y.y.y.y:8005" 


URL for client - http://localhost:8005/enc/Test/Test-/manifest.mpd


Can you help us for live stream generation ? We are happy to share additional details also, if required
