### ISSUE TITLE
HLS segments exceed target duration

### ISSUE THREAD

**Issue by bson** [kaltura/nginx-vod-module#323]
We do encodes with variable GOP sizes of up to 5 seconds.  They generally vary between 4.2 and 4.9 seconds.  When we generate an HLS media playlist for these files with a target duration of 10 seconds we see segments that exceed 10 seconds.

Here's our config:

            vod hls;
            vod_mode remote;
            vod_initial_read_size 32k;
            vod_metadata_cache moov_cache 512m;
            vod_response_cache response_cache 256m;
            vod_bootstrap_segment_durations 2000;
            vod_bootstrap_segment_durations 2000;
            vod_bootstrap_segment_durations 2000;
            vod_bootstrap_segment_durations 4000;
            vod_segment_count_policy last_rounded;
            gzip_types application/vnd.apple.mpegurl;
            vod_segment_duration 10000;
            vod_align_segments_to_key_frames on;
            vod_manifest_segment_durations_mode accurate;
            vod_segment_count_policy last_short;
            vod_segments_base_url "http://localhost";
            #            vod_hls_encryption_method "aes-128";
            vod_secret_key "xxxxxxxxxxxxxxx";
            vod_upstream_location /__proxy__;
            aio on;

Encryption was removed to investigate the resulting ts segments.

This yields a playlist along the lines of (indented for cosmetic purposes):

	#EXTM3U
	#EXT-X-TARGETDURATION:10
	#EXT-X-ALLOW-CACHE:YES
	#EXT-X-PLAYLIST-TYPE:VOD
	#EXT-X-VERSION:3
	#EXT-X-MEDIA-SEQUENCE:1
	#EXTINF:2.544,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-1-v1-a1.ts
	#EXTINF:4.463,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-2-v1-a1.ts
	#EXTINF:0.000,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-3-v1-a1.ts
	#EXTINF:3.921,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-4-v1-a1.ts
	#EXTINF:10.010,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-5-v1-a1.ts
	#EXTINF:10.010,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-6-v1-a1.ts
	#EXTINF:9.968,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-7-v1-a1.ts
	#EXTINF:11.011,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-8-v1-a1.ts
	#EXTINF:8.759,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-9-v1-a1.ts
	#EXTINF:11.512,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-10-v1-a1.ts
	#EXTINF:11.011,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-11-v1-a1.ts
	#EXTINF:9.009,
	http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-12-v1-a1.ts

The bootstrap segments clearly are... off, but that's a minor problem.  Although, I'd prefer if a segment exceeding the bootstrap duration was output instead of a zero-length one.  But the real problem is that some segments exceed the target duration.  This will e.g. fail apple's HLS validator.

The worst offender:

	#EXTINF:13.597,
        http://localhost/evs/assets/xhogua0dnhl4r37_2683601.mp4/seg-75-v1-a1.ts

**Comment by erankor** [comment]
The way the segmentation works is that module calculates the start and end offsets of the segment according to the configuration, and then aligns both offsets to the next key frame. So, for example, if the segment duration is 10 (and there are no bootstrap segments) the start and end offsets for segment 10 will be 90 and 100 respectively, and these values will later be pushed forward to the next keyframe.
The reason it works this way is that the segmentation is done on-the-fly and without any state, and this is much more efficient than calculating all segments from the start (which could have provided you with more constant durations of 8-10 secs)
This behavior is probably not going to change soon, but what I can fairly easily do is to simply report a larger target duration, so that target duration will be `round(max(actual segment duration))` instead of the current `round(max(configured segment duration))`. This will only work for `accurate` mode (which I see you are already using), `estimate` will not be affected.

**Comment by bitbytebit-cr** [comment]
Here is a quick thought I have on how to possibly get this value accurately on the fly.  Seems like this is zero cost for the most part since it is C, maybe an option would be needed if it is any overhead or for larger duration videos with 1000s of segments?

https://github.com/bitbytebit-cr/nginx-vod-module/commit/512530b17961ae7b01281461890d940f0a29bd8b

Thanks, it was a quick stab this morning without testing yet, mainly outlines / shows the main way I see that this could be done (if not a working fix).

**Comment by erankor** [comment]
Yes, this is roughly what I had in mind, although the actual implementation has a few issues:
1. scale is not defined at this point
2. If scale is somehow 1 (this is not possible with the current code, but I may decide to make the m3u8 version configurable at some point) the target duration will be wrong. The scaling from millis to seconds will have to be skipped in this case
3. The rescale should be performed outside the loop, as it would be more efficient. Or, to put it differently `max(rescale(duration)) == rescale(max(duration))`
4. The conventions do not accurately match the rest of the code

If you want, you can fix those issues and submit a pull, if not, I'll probably get to it in a few days.

**Comment by bson** [comment]
I assume the algorithm is to some extent constrained by the cost of keyframe lookups... And the lookup code returns the next keyframe for a particular time index, right?  In that case it might be better to just adjust the reported target duration.

A thought is that when adjusting a segment's start/stop times forward, also adjust all future start/stop times accordingly.  In effect, an adjustment at one point would push all future time indexes forward.  This would likely get rid of zero-length and runt segments in general and make them more uniform.

**Comment by erankor** [comment]
The thing is that the module does not have any state, this has many advantages, like supporting the deployment of multiple servers in parallel for performance / availability reasons.
But this also means that your suggestion can't work, the module cannot "remember" that it moved some previous segment. It has to perform the calculation from scratch, and at this point I prefer not to pay this performance penalty.

**Comment by bson** [comment]
In that case it sounds like adjusting the target duration in the playlist during generation is the only realistic solution.

**Comment by mdale** [comment]
Hi Eran :) For reference the "apple's HLS validator" in question is listed here:  https://developer.apple.com/library/ios/technotes/tn2235/_index.html

**Comment by erankor** [comment]
Thanks Michael ! glad to see you are still in business ;-)

**Comment by erankor** [comment]
Fixed here: https://github.com/kaltura/nginx-vod-module/pull/329
