### ISSUE TITLE
DASH: Support of SegmentBase in MPD

### ISSUE THREAD

**Issue by madmaz** [kaltura/nginx-vod-module#336]
Hi,
analyzing the source code, it seems to me that SegmentBase MPD format is currently not supported in the module. Am I right? Is there any forecast to implement it?
What I mean is something like this:

`<Representation bandwidth="1188602" codecs="avc1.4d401e" frameRate="25" height="480" id="1" mimeType="video/mp4" sar="1:1" startWithSAP="1" width="854">
    <BaseURL>movie_track1_dashinit.mp4</BaseURL>
        <SegmentBase indexRange="2144-9063" indexRangeExact="true">
      <Initialization range="0-2143"/>
    </SegmentBase>
  </Representation>`

Thanks in advance.
Cheers.

**Comment by erankor** [comment]
It seems the sample didn't go through, I only see some name of mp4 file...
If you are referring to the use a single URL per audio/video bitrate with byte ranges, then it's not supported because there is no way to implement it efficiently on-the-fly. When someone asks for range X-Y the module will have to calculate the layout of everything that comes before offset X.

**Comment by madmaz** [comment]
(I corrected the message) 
Yes I was referring to that.

**Comment by erankor** [comment]
Ok, so as I replied, this is not currently planned

**Comment by madmaz** [comment]
Sorry if I ask even if you closed: but if one would implement it, what could be the difficulties in respect of other formats? I suppose that on first Mpd request the sidx box is calculated and put in cache. 
I don't understand when you say "When someone asks for range X-Y the module will have to calculate the layout of everything that comes before offset X." because I think segments / possible byte ranges are precalculated at the first request as in other formats and clients can't ask for arbitrary ranges...  
Thanks in advance.

**Comment by erankor** [comment]
1. IMHO a good implementation should handle arbitrary ranges, it should not assume the client asks for the accurate ranges specified in the sidx box. For example, a client may want to download the whole stream, and in this case it may download with some fixed size ranges, or it can ask for the whole file in a single request.
2. It is true that the entire layout can be calculated on the first request and cached. While the module is using caches for certain tasks, in general, the principle I'm trying to follow is that each request performs the minimum amount of work needed to build the response. The reason is that this approach scales better - when the number of servers grow, the cache hit ratio decreases (yes, there are solutions for that too, like using centralized caching, but that has a price as well...)
3. Another thing to take in account is that other than just packaging, this module has more advanced features, like stitching (playlist), playback rate control etc. and in these cases, pre-calculating the whole layout can be even more painful (can involve reading several mp4 files, or for playback rate control - transcoding a long stream of audio)
4. One last point - in our setup, we have a CDN in front of this module, since we need to serve a large number of users spread around the world. Many CDNs do not handle range requests nicely, for example, some CDNs only serve range requests from cache after they download the whole file (btw, this is also another reason for my answer to 1 - while a client may always ask for the sidx ranges, the CDN may issue different requests to the origin)

But why do you need it anyway ?
