### ISSUE TITLE
No http-range in request if proxy_cache is set

### ISSUE THREAD

**Issue by GoodGame** [kaltura/nginx-vod-module#342]
In remote mode no range header set in request to upstream if proxy_cache directive setup.

`
http {

    upstream kalapi {
        server www.kaltura.com:80;
    }
    server {
      listen 80;
      ...
      proxy_cache xxx; <<<<<<<
      ...
      vod_mode remote;
      vod_upstream_location /kalapi;
      location ^~ /kalapi/ {
            internal;
            proxy_pass http://kalapi/;
            proxy_set_header Host $http_host;
        }
}
`

Why proxy_cache didn't work?

p.s. Markdown is broken.

**Comment by erankor** [comment]
Yup, this behavior is mentioned here as well https://github.com/kaltura/nginx-vod-module/issues/308.
That's how nginx's cache works - http://nginx.org/en/docs/http/ngx_http_proxy_module.html says:
`If caching is enabled, the header fields “If-Modified-Since”, “If-Unmodified-Since”, “If-None-Match”, “If-Match”, “Range”, and “If-Range” from the original request are not passed to the proxied server.`
You may be able to make it work by adding something like `proxy_set_header Range $http_range`, but you will also need to add the range to the cache key, so it probably won't be too effective (btw, also need to handle the cache in which the original request did not specify a range)

**Comment by aamir2007** [comment]
I have tried this method added $http_range into the the cache key as well as in Range header however after doing so I get this error in my log files. 

> ngx_http_vod_get_async_read_result: not enough room for null terminator
and if I turn proxy_cache off, it increases inbound traffic almost equal to the outbound traffic, that means all the requests are fetched from remote server hence eating out bandwidth. 
I have temporarily resolved this issue by downloading the file manually on first request via php, curl and exec methods however this should have been handled by the NGINX proxy cache.
