### ISSUE TITLE
Questions about this code.

### ISSUE THREAD

**Issue by einthusan** [kaltura/nginx-vod-module#345]
Hi,

It seems that you have developed a module for HLS streaming that works with the free version of nginx? If so, I am super glad to come across this and we can surely help your efforts by donating a fairly decent amount of money.

However, I have 2 questions.

1. Is HLS support only for mp4 files encoded with h.265 or will it also work for video files encoded using h.264?

2. Will this work in FreeBSD, and if so, has the underlying system calls been optimized for FreeBSD?

Thanks in advance.

**Comment by erankor** [comment]
1. The module supports h264 in all 4 protocols (HLS, HDS, MSS, DASH).
2. We are testing it only on Linux, but there are folks who, I believe, ran it on FreeBSD. Since the module runs on top of nginx, and it does not interface with the operating system directly (everything is done using nginx's APIs), I expect it to work well.

**Comment by einthusan** [comment]
@erankor Wow, thanks for the info. This is perfect. Cheers!!! :D Keep up the awesome work. Let me know if we can donate somewhere.
