### ISSUE TITLE
is support live mpeg-ts input

### ISSUE THREAD

**Issue by alexliyu** [kaltura/nginx-vod-module#358]
you did a great job, this module is great!
but i want to know that is support live mpeg-ts input?
because i need input http mepg-ts stream, and response to hls or other type.

if you do not wanna to support it, please tell me how to edit the source code to support this.

thanks!

**Comment by erankor** [comment]
This is not supported. 
We have some work in progress on a separate project for pulling an HLS live stream and then normalizing it to the input expected by this module (MP4 chunks + JSON manifest). This will enable us to repackage the live stream to all protocols, DRM etc. but this is quite preliminary, and will probably take a few months until it becomes production ready.
The feature as you described it, will most likely never be an integral part of this module, for the simple reason that the module is completely stateless, and we have no intention to change that since it provides many advantages. The way to implement such a feature is to follow the approach I explained above, and to write some connector that takes an MPEG-TS live stream, and transforms it to a JSON that this module can understand.
Btw, if you need only HLS, you can take a shortcut - since you already have the stream in MPEG-TS format, you just need to chunk it every X seconds and generate the appropriate manifest, it may be easier than transforming the stream to MP4/JSON.
