### ISSUE TITLE
how to limit 1 movie per ip ?

### ISSUE THREAD

**Issue by momkin** [kaltura/nginx-vod-module#368]
Hello
i want to limit 1 watching per movie ( i want the visitors to be able to only watch 1 movie at the some time )

**Comment by erankor** [comment]
you can probably build it with ngx_lua and maybe memcached for holding the state - 
1. extract the video id from the segment request (can be done using nginx regex location variable capture)
2. use access_by_lua and check whether there is already a key in memcache for the user ip address
3. if there is a key and it points to a different video id, deny the request
4. otherwise, set the key in memcache to the id of the video. if you use segments of 10 sec, set the memcache expiration to 20 sec, for example

**Comment by erankor** [comment]
can this be closed ?

**Comment by momkin** [comment]
can you please tell me how to do that ? :(

**Comment by erankor** [comment]
I'm sorry but this is really out of the scope of this module, you can the docs of ngx_lua for more info
