### ISSUE TITLE
merging remote and mapped mode

### ISSUE THREAD

**Issue by eminden** [kaltura/nginx-vod-module#369]
I am investigating this module to check out the possibilities, on thing I would like to know, on remote mode; module fetching mp4 files from remote http server, is it possible to fetch mp4 files from remote http server on mapped mode also?

As I understand on mapped mode module fetches a json object from remote http server, and parses it and tries to find the files on the **local** disk, could it be possible to fetch the mp4 files which is found in the json object from remote http server?

**Comment by erankor** [comment]
Currently no, we thought about adding support for this in the past, but it never got a high enough priority.

**Comment by eminden** [comment]
I would like to use this feature, seems that you are not interested on developing this, even though I don't have enough experience on nginx module development, could I try to dive into this if you support me?

**Comment by erankor** [comment]
I'll be completely honest here - 
1. I don't have much time for mentoring, if you are a strong C developer and you just need a couple of pointers for getting started, that can out work fine. Otherwise, I wouldn't recommend it
2. If you decide to take this task, you should be aware that I'm quite a code nazi. While the conventions of this module have never been formalized in some document, the code is, to a high degree, consistent, and no code will be merged unless it follows the existing coding standard

**Comment by eminden** [comment]
understand your concerns, I am not totally hopeless for this, if you could give me how to start and  how to design of this feature,  I would like to try my best in spare times.

**Comment by erankor** [comment]
Here are my initial thoughts on this -

As see it, there are two ways to tackle this:
1. Pass some kind of flag, either in the conf or in the json, that will indicate whether to use files of http
	for all source clips referenced by the json
2. Support the selection of file/http per source clip in the mapping json, so that it will be possible to create a json that references both local and remote files

If we are changing this, my preference is to with the more generic solution (2), even though I don't find the capability to mix remote and local on the same json extremely useful.

Regarding the implementation, for solution 1:
- ngx_http_vod_module.c: in ngx_http_vod_map_source_clip_done, check some conf value / value that was parsed from the json, in order to decide
	whether to read from file or http, and initialize the reader accordingly (similar to what is done in ngx_http_vod_mapped_request_handler)

For solution 2:
- media_set_parser.c: add a new string field "uri" to media_clip_source_params
	the string can be saved to mapped_uri (like "path"), but will use some wrapper function to media_set_parse_null_term_string to update a new enum "type" on the source object that will indicate whether the value should be treated as a uri or path

- ngx_http_vod_module.c: bundle all the read-related fields of ngx_http_vod_ctx_t with media_clip_source_t::reader_context - move the fields - read, alloc_params_index, alignment to ngx_http_vod_reader_t, and add some new 'reader' pointer on media_clip_source_t, that will be used instead of ctx->reader. before each call to reader->open, initialize the reader pointer on the source according to the source type (file / uri)

In both cases, I think it makes sense to add a new conf setting vod_remote_upstream_location that will enable using one upstream location for the mapping (usually some internal server) and a different location for the remote files (probably some external server)

That's how I see this feature now, it is very possible that after seeing/playing with the code a somewhat more elegant solution will appear.

**Comment by erankor** [comment]
@eminden, this can be closed, right ?

**Comment by eminden** [comment]
sure, thank you very much for your help.
