### ISSUE TITLE
cache invalidation for single mp4 file

### ISSUE THREAD

**Issue by danielegobbetti** [kaltura/nginx-vod-module#415]
Our current configuration is this module working on a system with:
- mp4 files that are on the local disk
- served in "mapped" mode as HLS

The settings related to caching are:
```
        vod_metadata_cache metadata_cache 512m;
        vod_mapping_cache mapping_cache 64m;
        vod_response_cache response_cache 64m;
        open_file_cache max=1000 inactive=5m;
        open_file_cache_valid 2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors on;
        aio on;
```

Sometimes we need to "swap" an existing mp4 file with a new one (i.e. the file name remains the same but the content changes), after this has been done the clients are not able to play the stream unless we restart nginx.

My guess is that the problem lies in the cache that isn't being invalidated when the file changes. Is there something we are missing in the configuration for this to happen?

**Comment by erankor** [comment]
The cache is one problem, but also consider that if a user is playing the video, and you change the file, he may get, for example, segments 1-10 from video 1 and segments 11-20 from video 2. Unless the videos are encoded exactly the same, the user will get some error / green screen (note that even using the same ffmpeg command line is not enough). And, other than that, most deployments use CDN / caching proxies, and they will be caching the segments as well.
So, my point is - replacing a file in place is not a good idea. It would be far better to use a new file, and provide a new URL to the users. In our URLs we have a version parameter that gets incremented every time the video is replaced, and we are using it when mapping the request to a specific MP4 file on disk. Whenever a user starts playing a video, we provide him with a URL that contains the latest version.

**Comment by danielegobbetti** [comment]
@erankor thanks for the fast reply.
I do understand your point, but our use case (probably smaller and simpler than yours) requires us to act as described. I also believe that dealing with modified files would not hurt the scenario you described, but I want to ask you if a pull request from us that adds a check on the original file modification time in the caching logic is something you would merge or something you exclude.

**Comment by erankor** [comment]
I'm afraid it's not that simple, a couple of problems that I can think of here:
1. you need to invalidate 2 caches - the metadata (moov atom) cache and the response cache. In both cases, the file is not yet open when the cache is being checked, so you don't know the file modification there. this means you'd need to change the state machine of the module so that it first loads the file. however this is not a change we want for cases in which the modification time is not checked, since for example, manifest requests can currently be answered without opening the file at all. so you'd need to make the module support 2 different flows in the state machine, which is more complicated
2. the cache implementation in this module is built on a simple cyclic buffer, which means that if you invalidate some cache item, the space used by the item cannot be reused until the write pointer of the buffer reaches it again. with the response cache this is not so bad, but in the case of the metadata cache, the items can be large (10s even 100s of MBs). but other than that, the current implementation does not support overwriting an existing item, unless it is added, the module will not be able to use the cache at all for a specific request until the invalidated cache item gets purged.

due to the above (and possibly other complications I can't think of now) I prefer not to do it.
