### ISSUE TITLE
m3u8 direct download

### ISSUE THREAD

**Issue by arty777** [kaltura/nginx-vod-module#425]
Hi, 

 please provide working config , 
which does not allow eny hls downloader merge videos directly from m3u8 link ... is is possible? 
without DRM . HLS encryption ok, but downloader wok fine (merge video, download fine ((( )

very need protect video from direct download

**Comment by erankor** [comment]
there is no silver bullet solution to this problem, it depends on how the specific downloader is implemented. at the end, DRM is the maximum level of security in this regard, since the encryption key / clear content only exist in a secure execution environment, that the major vendors are working very hard to protect.
if what you want is to make sure only entitled users can watch the content, then this is a problem that has good solutions (like URL tokenization), but preventing a user that is allowed to watch the content from being able to download the stream is much more problematic.
even though i never really researched this subject, i'm guessing many downloaders are based on the assumption they can pull the video url from the page (by walking the DOM or something like that). if my guess is correct, you should be able to fool some of them by making sure the URL cannot be easily extracted this way, e.g. don't put it directly on the video tag, have some token on it that is computed by some JavaScript code, etc.
but even if you do that, a more sophisticated user will be able to use some web sniffer (like Fiddler) and capture the final URL from there. you can maybe add another layer of security by somehow making your URLs have a short expiration time or even have them work only once. but that will still be hackable, it's a cat / mouse game at the end...
