### ISSUE TITLE
WebM muxing

### ISSUE THREAD

**Issue by ThalysonR** [kaltura/nginx-vod-module#427]
I'd like to know if there's support for webm vod streaming, i have no problem streaming mp4 files but if i request a webm i get this error: 
`30596#30596: *11 ngx_http_vod_identify_format: failed to identify the file format while reading media header, client: 127.0.0.1, server: localhost, request: "GET /content/grav_..x720_1500k.webm/manifest.mpd HTTP/1.1", host: "localhost"`

**Comment by erankor** [comment]
there is experimental support for webm (=matroska), it's currently disabled by default, you need to uncomment the following line to enable it:
https://github.com/kaltura/nginx-vod-module/blob/1.10/ngx_http_vod_module.c#L220
there are some open todos with regards to webm (e.g. support for clipping) but for simple cases it will probably work fine. 
the main motivation behind adding webm support was in order to use the vp9 codec, but since latest ffmpeg supports packaging vp9 in mp4, I never took the time to fully close this feature (btw, support for vp9 in mp4 was added to nginx-vod-module several months ago)

**Comment by ThalysonR** [comment]
Didn't know i could package vp9 in mp4... I'm trying to generate a video using vp9 in mp4 but it seems it's an experimental feature in ffmpeg and generates a vp09 format instead of VP9, so the client can't decode it. 
My ffmpeg line: 
`ffmpeg -i Gravity.mp4 -c:v libvpx-vp9 -strict -2 -vf "scale=-2:90" -b:v 300k -keyint_min 48 -g 48 -tile-columns 4 -frame-parallel 1 -an -f mp4 -dash 1 gravp9_..x90_300k.mp4
`
Is there a correct way to generate vp9 in mp4 so i can use it on nginx vod module?

**Comment by jessp01** [comment]
Hi,

In container formats VP9 streams are marked with the FourCC VP90 (or in the future possibly VP91, ...) or VP09. So VP09 is not a different format.. just a way to mark the VP9 stream in a container.
Not sure why your client cannot decode it but checkout the commands and documentation here:
http://wiki.webmproject.org/ffmpeg/vp9-encoding-guide

**Comment by erankor** [comment]
here is the command line I used when I added this feature to nginx-vod:
```
ffmpeg -i /tmp/test.mp4 -t 30 -c:v libvpx-vp9 -b:v 1000K -force_key_frames "expr:gte(t,n_forced*2)" -an -strict -2 -f mp4 -y /tmp/vp9.mp4
```
maybe it doesn't work for you because you pass the `dash` ffmpeg parameter, I'm not sure what this parameter does, but you need to generate a regular mp4 for nginx-vod-module.

**Comment by ThalysonR** [comment]
Thank you, that worked for me
