### ISSUE TITLE
I have a question for "Audio only/video only files" feature.

### ISSUE THREAD

**Issue by cxnam** [kaltura/nginx-vod-module#430]
Hello guys,
I don't understand clearly this feature "Audio only/video only files". I think nginx_vod_module only support audio file and video file seperately. Can someone explain it for me, please?
And I have a example file .m3u8 (http://pastebin.com/R3vLHZX2), how can I do it by using this module?
Thank you, guys.

**Comment by erankor** [comment]
The module supports practically all combinations of audio / video:
1. generating a video only stream from a video only file
2. generating an audio only stream from an audio only file
3. generating a muxed stream from a video+audio file (HLS/HDS only, in DASH/MSS the streams are always delivered separately)
4. muxing together an audio file and a video file

Regarding the manifest you referenced, it has multiple audio tracks as well as captions, both features are supported:
1. If you input an MP4 file that has multiple audio tracks that are tagged with different language codes, the module will automatically generate a multi-audio master manifest
2. Otherwise, you will need to use a mapping JSON and indicate the language there (the language / label fields here - https://github.com/kaltura/nginx-vod-module/#sequence)
3. For captions, you need to input a WebVTT/SRT file and it will be added to the manifest

**Comment by cxnam** [comment]
Tks for your reply.

"1. If you input an MP4 file that has multiple audio tracks that are tagged with different language codes, the module will automatically generate a multi-audio master manifest"
This mean nginx-vod-module does not currently support the creation of a multi audio track master m3u8?

"2. Otherwise, you will need to use a mapping JSON and indicate the language there (the language / label fields here - https://github.com/kaltura/nginx-vod-module/#sequence)"
=> I config follow thís guide https://github.com/kaltura/nginx-vod-module/#mapped-configuration but i don't understand test it with file mp4. Can you help me pls?

Tks and best regards.

**Comment by erankor** [comment]
Regarding 1, I don't understand how you came to this conclusion, I already wrote that it is supported.  
The point is this - to create a multi audio master m3u8, nginx-vod-module needs to know the language of the audio tracks, it can't guess that track 1 is English and track 2 is Spanish. 
The language has to come from either:
1. The mp4 file itself - it is possible to denote the language of each track in MP4 (in the mdhd atom). I don't know how you generate these files, but ffmpeg for example has the ability to set these tags.
2. When working in mapped mode, nginx-vod-module gets a JSON from some backend server that contains the "instructions" about the stream that should be generated. You can specify the language in the JSON if you don't already have it in the MP4 file. The JSON structure is documented here: https://github.com/kaltura/nginx-vod-module/#mapping-response-format

**Comment by cxnam** [comment]
@erankor tks 👍
