### ISSUE TITLE
Is there any commercial license available?

### ISSUE THREAD

**Issue by shintaroid** [kaltura/nginx-vod-module#434]
We'd like to add this project to our product which make use of several DRM technologies. Do you provide any commercial license?

**Comment by erankor** [comment]
In my understanding, with our AGPL license, there is no problem to use this project for commercial purposes. However, if you make any changes to the code (e.g. add features) you have to contribute them back.
If that does not work for you, let me know, and I'll check internally what can be done. I believe we can provide this with a commercial license, but only to Kaltura customers.

**Comment by shintaroid** [comment]
Thank you.

We are concerned with DRM technology. If we use this package, are we still be able to totally control our DRM? Since it's open source, I'm afraid we may not be able to restrict anyone who want to decrypt contents protected by DRM (say Widevine)?

By the way, if you do provide commercial license, is it possible for us to only use this package? For the time being we are not considering any other Kaltura's product.

**Comment by erankor** [comment]
Regarding DRM, only the encryption part is implemented by this module, licenses should be generated by your servers. The fact it's open source is no security concern, since the way the streams are encrypted is no secret, there are open standards that define how it should be done.
Regarding the license, I can check internally, this is not something we normally do.

**Comment by shintaroid** [comment]
Alright, thank you very much. I'd like to discuss with my colleagues. Thank you again!

**Comment by erankor** [comment]
@shintaroid, can this be closed ?

**Comment by shintaroid** [comment]
Yes, please, thank you.
