### ISSUE TITLE
Question about bitrate calculation for MSS prototcl

### ISSUE THREAD

**Issue by utu2016** [kaltura/nginx-vod-module#438]

**Comment by utu2016** [comment]
Hi, I'd like to understand how the module calculate the bitrate present in Manifest file.

Looking xml, retrieved from .mp4 (with mp4box tool), I see:
.....
BitRateBox BufferSizeDB="79705" avgBitRate="702968" maxBitRate="1922464"
.....

When I start to play, the Manifest produced this report:
.....
    <QualityLevel Index="0" Bitrate="702464" FourCC="H264" MaxWidth="768" MaxHeight="432"
.....

attached the mp4 file (just renamed as txt)
[test_2.mp4.txt](https://github.com/kaltura/nginx-vod-module/files/547417/test_2.mp4.txt)

Thanks

**Comment by erankor** [comment]
The video bitrate is calculated by averaging the bitrate of the frames at the beginning of the file (the first 100k frames or less) - sum(frame size) * 8 / sum(frame duration).
Audio bitrate usually appears in the MP4 metadata, if it doesn't, it will be calculated like the video bitrate.
Specifically for MSS, the lowest 10 bits of the bitrate are used to encode the sequence and track indexes. This is needed because this module is stateless, so if it gets a request for some fragment in an XML that references 4 videos, it would need to calculate all their bitrates to figure out which video is being requested. Encoding these ids on the bitrate avoids this performance hit, and introduces only a negligible error of max 1024 bps in the bitrate value.

**Comment by erankor** [comment]
@utu2016, can we close this issue ?

**Comment by utu2016** [comment]
yes of courase !, 
thanks for the explaination.
