### ISSUE TITLE
AC3 audio in HLS/DASH

### ISSUE THREAD

**Issue by TroRg** [kaltura/nginx-vod-module#449]
Hello! Just a feature request. It will be good to see AC3 support in HLS/DASH streams.

**Comment by erankor** [comment]
Check out this branch - https://github.com/kaltura/nginx-vod-module/tree/hls-ac3-eac3
only hls for now.
When I test it on iPhone, the index.m3u8 plays with AC-3, but the master.m3u8 does not, this is most likely because iPhone does not officially support AC-3 (E-AC-3 does not play for me at all on iPhone).
It will probably be fine on AppleTV.

**Comment by TroRg** [comment]
Hello. Excelent! Checked on ATV and it works. Thank you very much.

**Comment by erankor** [comment]
Great, merged to master, better recompile from there, since I found a couple of bugs as I was merging this change

**Comment by erankor** [comment]
Regarding dash, I enabled it on branch dash-ac3-support, the output looks ok to me, but I don't have anywhere to test it. I tried to play a couple of Dolby test vectors in Shaka and Dashif on Chrome and I'm not getting any audio.
Do you/anyone else here have some device that support it?

**Comment by TroRg** [comment]
This is complicated task. Tried on android+ExoPlayer, but get "Media includes audio tracks, but none are playable by this device."

**Comment by erankor** [comment]
Ok, I decided to merge this change even though we can test it, it can't do any harm...

**Comment by erankor** [comment]
Small update, regarding dash/ac3, just found out that Edge can play ac3 (at least on Win10) - verified this feature is working using Dashif v2.3.0
