### ISSUE TITLE
Does nginx-vod-module work with NGINX Plus as well ?

### ISSUE THREAD

**Issue by suuhas** [kaltura/nginx-vod-module#451]
Hi team, 
We were using the module for a couple of weeks with NGINX and it's been awesome so far. 
Have anyone installed nginx-vod-module with NGINX plus ?

**Comment by erankor** [comment]
We haven't tested with nginx plus, we are using the open source version. 
However, we recently added support for compiling this module as a dynamic nginx module, so it should work with latest nginx plus.

**Comment by suuhas** [comment]
Hey @erankor 
I have compiled with nginx plus and tested it, works without any issues. Thanks
Are you guys planning to have a release nginx-vod-module bundled with dynamic nginx module changeset.

**Comment by erankor** [comment]
Great, thanks for the update.
If you are asking about a pre-compiled DSO, the problem is that afaik there is a large set of parameters that have to match the core nginx build exactly, in order for the module to load (e.g. aio yes/no, threads yes/no, ...). And it will be problematic for us to release many versions with all the different combinations.

**Comment by denji** [comment]
@erankor I think adding/testing of such units should be engaged kaltura/nginxinc in cooperation, nginx-plus is not supported platform for community CI build modules, to the nginx-plus. Nginxinc must do testing and support. Well, the question of extra costs for the purchase nginx-plus only for build community modules.

**Comment by suuhas** [comment]
@erankor @denji  Thanks for replying.
What I was asking about is right now "kaltura/nginx-vod-modlule" master branch has the support for dynamic module. Is this dynamic-module support will be part of the upcoming release of "kaltura/nginx-vod-modlule" ?

**Comment by erankor** [comment]
@suuhas, I don't understand, isn't that what I replied to above ? As I wrote, it's problematic to publish pre-compiled dynamic versions of the module, since there is a large set of parameters that has to match the core nginx.
@denji, regarding your comment, there are many more setups which can be tested and are not being tested now (e.g. 32 bit, other linux distros, FreeBSD). Personally, I don't see testing against nginx-plus as high priority. I would love to have a CI for 32 bit, for example, since that breaks often and some people use it, but unfortunately Travis only does 64 bit.

**Comment by denji** [comment]
@erankor https://hub.docker.com/r/multiarch/qemu-user-static/ and https://docs.travis-ci.com/user/docker/

```
language: bash
sudo: required
services:
    - docker
before_install:
    - docker pull multiarch/qemu-user-static:register
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
```

![qemu-user-static](https://cloud.githubusercontent.com/assets/3759759/20269564/65ef324a-aa8c-11e6-87db-ba7a7ffd7637.jpg)

**Comment by suuhas** [comment]
@erankor cool I got it now and I am closing the ticket.
