### ISSUE TITLE
Labels for languages are not inserted from .json into .mpd 

### ISSUE THREAD

**Issue by mazanov** [kaltura/nginx-vod-module#455]
When streaming ABR dash using .json file with links to several .mp4 files the Sequence->label tags from .json are not inserted into dash .mpd manifest file.

**Comment by erankor** [comment]
Hi, 
Yes, I'm aware of that, I did not find any attribute in DASH that seemed appropriate to contain the label. Checked the spec as well as the samples included with Shaka & Dashif players. There's a chance that putting the label as the `lang` attribute will work on some players, but that seems wrong, since it's supposed to be a language code.
If you have a sample manifest that has such a property, please send it and we'll be happy to add this feature

Eran
