### ISSUE TITLE
Sideways orientation of videos recorded with iPhone in portrait mode

### ISSUE THREAD

**Issue by quest2nest** [kaltura/nginx-vod-module#486]
If I stream (using nginx-vod-module) a video recorded with iPhone in portrait mode, the resulting HLS stream displays sideways. The .MOV (Quicktime) video was uploaded to the server as is, without conversion of any kind.

What would be the best way to handle such videos so that the resulting HLS stream is in the correct orientation? It looks to me the options are:

- preprocessing on iPhone before uploading to the server
- processing on the server (using ffmpeg) before streaming
- providing a configuration option to nginx-vod-module that rotates the video (not sure such an option exists)
- hacking nginx-vod-module's ffmpeg code and recompiling

Also wanted to thank the authors of this module; you guys are awesome!

**Comment by erankor** [comment]
If you play the mp4 directly in Safari (not using HLS), does it play in the correct orientation ?

**Comment by quest2nest** [comment]
Hi erankor,

Thanks for your reply!

It does on Mac (it's actually a MOV file but I guess the containers are similar enough).
But it doesn't play in the correct orientation when playing directly in Firefox on Linux.

I also found that if I simply run the file through `ffmpeg` like this:

```ffmpeg -i input.mov out.mov```

the resulting file plays correctly in all programs (and through HLS).

When looking at the input file (which was recorded on an iPhone) with `ffprobe`, I can see that it has the following metadata in it:
```
    Metadata:
      rotate          : 90
      creation_time   : 2016-12-05T19:39:11.000000Z
      handler_name    : Core Media Data Handler
      encoder         : H.264
    Side data:
      displaymatrix: rotation of -90.00 degrees
```
While the resulting file does not have it (and plays correctly).

Also, `ffplay` plays that original file correctly, while `mplayer` does not.

Apparently, iOS records videos directly with the orientation of the hardware camera and saves the orientation of the video in the transform matrix. Some players read and apply that matrix when playing, while others don't (apparently). What's strange is that `ffmpeg` does apply it when transcoding (as we can see above), but not when used in `nginx-vod-module`?

If this helps, here's the original file (straight from the iPhone):
https://s3-us-west-2.amazonaws.com/quest2nest/IMG_0011.MOV

**Comment by joaoserra** [comment]
iPhones don't rotate the video in portrait mode. They record at wide resolution and insert an 90' rotation matrix in the the tkhd MP4/MOV atom.

Since HLS is MPEG-TS based, and as far as know TS doesn't support rotation matrices, that information is simply lost during the transmux.

One possible workaround is to insert a NAL containing a Display Orientation SEI (SEI Type 47) in the beginning of the h.264 bitstream. But since the Display Orientation SEI was only introduced in the 2013 revision of the h.264 standard, the support can be limited. (But, at least in a browser environment with MSE support, it should be possible to read the flag and act accordingly with a little of effort)

**Comment by quest2nest** [comment]
So checking the transform matrix and rotating the video at the transmuxing stage is not an option?

**Comment by quest2nest** [comment]
Incidentally, if anybody else has this problem and is in control of the iPhone recording process, this example might help:

https://github.com/scottcarter/VideoExport

**Comment by erankor** [comment]
@quest2nest, as @joaoserra wrote, what happens here is that the rotation data is lost in the transform to HLS. When you executed ffmpeg on this file, it decoded the video, applied the rotation, and then re-encoded it. The resulting file had the correct video orientation without the use of a rotation matrix.
While it may be possible to somehow retain the rotation info in the repackaging (e.g. the NAL unit mentioned by @joaoserra), since you already saw that some environments don't respect the rotation info, even in a simple progressive download scenario, I don't think it's worth the effort.
I believe the only way to support this across all devices, is to transcode the file to remove the rotation info (as you did with ffmpeg)

**Comment by quest2nest** [comment]
Thank you for your help guys. Closing the ticket then.

**Comment by joaoserra** [comment]
@quest2nest Direct ABR streaming of mobile encoded videos is not a good idea anyway... Videos from mobiles normally have very high bitrates(in part because they want to allow you to edit the video, but mostly because mobile encoders can't encode decent quality video at low bitrates), variable frame rates, awkward GOP sizes, etc 
The video that you posted has a 17.2 Mb/s bitrate, variable framerate a a 1second GOP size...

@erankor I can't test it right now, but In case of DASH/SS, which are ISOBFF based, are your preserving the rotation matrix?

**Comment by erankor** [comment]
I assume we are talking about the matrix in the tkhd atom, I am not preserving it. I used to pass this atom as-is in the past, but since the module now supports the concatenation of multiple videos into a single stream, it makes less sense to do it. For example, I may need to update the timescale/duration etc., so it was easier to build this atom from scratch than to take the existing one and update it. 
That said, it is possible to add some code to retain specifically the rotation matrix, but as I wrote above, don't think it will be too useful.
Btw, what I just wrote refers only to DASH, in MSS there is no 'init segment', and this atom is not returned to the client. Don't know if there's any way to pass this info in this protocol.
