### ISSUE TITLE
Clipping isue with MP4 files

### ISSUE THREAD

**Issue by lelikg** [kaltura/nginx-vod-module#508]
Hi, when using clipFrom and clipTo with msec accuracy the first few frames of the result clip are stuck.
An example can be seen here
http://vod.panda-os.com/pandaMp4/106/content/entry/data/0/835/0_frk5h77r_0_ea5qnexr_2.mp4/clipFrom/112400/clipTo/116000

Is there anything that can be done? 

The source clip can be found here:
http://s3cdn.panda-os.com/106/content/entry/data/0/835/0_frk5h77r_0_ea5qnexr_2.mp4
Thanks!

**Comment by erankor** [comment]
Since the clipping is performed on-the-fly without any transcoding, you have to start on a key frame. In this case, the clipFrom position does not point to a keyframe, and the player can't decode the video before it reaches a keyframe. 
When using clipping with streaming protocols (HLS, HDS etc., but not progressive) if you enable `vod_align_segments_to_key_frames`, the module will push the clipFrom position forward to the closest keyframe. So, you won't get such a freeze, but naturally the start position will be different than what you requested. It is simply not possible to start from any frame, without retranscoding.

**Comment by lelikg** [comment]
Thanks @erankor I figured it has something to do with the keyframes. This kind of kills the feature, in the sense where you can't use this feature to cut a scene unless it's perfectly on a keyframe, which is not always the case.
How complicated is it to re-encode the first segment on-the-fly in order to have more accurate clipping?

**Comment by erankor** [comment]
not easy, the video would need to be re-encoded exactly the same as the original, and for a high resolution video, even those few seconds of video may take a considerable amount of time to transcode.
btw, we are always forcing key frames every 2 sec, so clipFrom values that are a multiple of 2 sec should be fine.

**Comment by lelikg** [comment]
Maybe I’ll look at a hybrid solution of encoding the first two(or less) seconds via ffmpeg first, up until the keyframe, and join them with the rest of the video.
2 sec keyframes are fine for long-form content, but for some use-cases like sports we need frame-accurate clipping.
