### ISSUE TITLE
Segment N not found

### ISSUE THREAD

**Issue by sergiyshutov** [kaltura/nginx-vod-module#511]
Dear erankor. I have problem with some files. 
Example this: https://yadi.sk/i/KiFtlefY37Tj2x
Player: hls.js (last version)
Nginx vod module version: 1.12

config:
```
vod hls;
vod_segment_duration 10000;
vod_align_segments_to_key_frames on;
vod_manifest_segment_durations_mode accurate;
```
Last segment not found: http://localhost.lc/hls/13.mp4/seg-640-v1-a1.ts

I check Nimble Streamer and all works fine.
Can you please check this problem?! :)
Thanks.

**Comment by sergiyshutov** [comment]
ps: I check Nimble Streamer and all works fine.

**Comment by erankor** [comment]
The end of this file has a crazy audio frame rate - 
```
/web/content/shared/bin/ffmpeg-3.2-bin/ffprobe.sh -i shutov.mp4 -show_packets -select_streams a | grep dts_time= > /tmp/audiots.txt
grep -c dts_time=640[0-4] /tmp/audiots.txt
87486
```
There are 87K frame audio frames in 4-5 sec, which is close to 20Kfps.
The module has a hardcoded limit of 64K frames per segment, so it fails the request.
You can patch the code to have a larger limit if you want:
https://github.com/kaltura/nginx-vod-module/blob/master/ngx_http_vod_module.c#L1398
but I don't think such a high frame rate makes sense, something is wrong with this file.

Btw, for next time, it could have been very helpful to paste the error from the error log, I could have told you what the problem is without having to download the file.

**Comment by sergiyshutov** [comment]
erankor you right. its my mistake.
Tenk yu veri mach :D
