### ISSUE TITLE
HSS streaming problem: 5sec with large pixel

### ISSUE THREAD

**Issue by utu2016** [kaltura/nginx-vod-module#518]
Hi, 
We have some problems streaming the HSS contents.
The first 5 seconds are not good (large pixels are showed); but if we play these contents using HLS protocol all works fine from the begining.
We’re using clear version for both protocols.
The module version used is 1.10
Attached the zipped content folder and the configuration used.

Could you help us to understand where is the problem?

[nginx.conf.txt](https://github.com/kaltura/nginx-vod-module/files/735561/nginx.conf.txt)

https://www.wetransfer.com/downloads/99c2d54b5325333522866716598597de20170127152410/316d842dca0ac21e076ef34523ac26a620170127152410/54c13a

**Comment by erankor** [comment]
I see you have multiple renditions, lowest one is 384x216 and highest is 1920x1080, most probable cause of what you describe is that MSS starts with the lowest bitrate, and HLS starts with some other bitrate.
I suggest you will test with one rendition at a time, in order to validate if this is indeed the cause (you can simply use `manifest-f1` in MSS or `master-f1.m3u8` in HLS to get only the first rendition)

**Comment by utu2016** [comment]
Hi, 
we checked the single renditions, and we found that only the two highest haven't the problem on the first 5 sec.
We have test all renditions with  IIS and all works fine (it's seems that the MP4 are ok); but if we use this module we have problems.

Could you help us to understand where is the problem?

**Comment by erankor** [comment]
can you send two manifest URLs of a single bitrate, one from IIS one from nginx-vod-module, where nginx-vod-module has the pixelation and IIS does not ?

**Comment by utu2016** [comment]
Hi, 
in the zipped file it contain these folders:
1-IIS_OUTPUT: with .ism/.ismc and .ismv produced by IIS
2-MP4_MODULE: with .mp4 used as input for kaltura module. The configuration file is the one I sent you before.
These data are related to lower rendition (300bitrate).

[KALTURA_SINGLE_REND.zip](https://github.com/kaltura/nginx-vod-module/files/747415/KALTURA_SINGLE_REND.zip)

Unfortunatelly I have no way to give the url to you because we have not exposed our IIS environment.
thanks for your help.

**Comment by utu2016** [comment]
Hi Erankor, 
do you have any news for me?
thanks

**Comment by erankor** [comment]
I'm sorry, didn't have a chance to check it out yet, but if you have some way to set up an IIS (maybe on some other environment) it can really help, since I'll be able to see the visual differences and compare the outputs.

**Comment by utu2016** [comment]
Hi, 
here is the IIS.
please use this url for test:
http://52.30.197.38/Kaltura/sample_x_nginx.ism/Manifest

We've checked with akamai (http://support.akamai.com/silverlight/) and the streaming is ok.

**Comment by erankor** [comment]
I compared your stream to one I created with nginx-vod-module, and I have to say I don't see any visual difference. Please check out this URL - http://lbd.kaltura.com:8001/local/mss/content/test_nginx_HD_300.mp4/manifest
Btw, the Akamai test player didn't work for me, I used http://playready.directtaps.net/pr/doc/slee/ instead (with Firefox)

Also, I compared the manifest and the first video segment of the stream you provided to the ones generated by nginx-vod-module, none of the difference look relevant:
1. your stream has MSS version 2.1, nginx-vod return 2.0
2. your stream has FourCC="AVC1", nginx-vod returns FourCC="H264" (according to the spec, H264 is the right one)
3. the audio is different, you have 2 languages with half the sampling rate (since the problem was in the video, this doesn't seem relevant)
4. the representation of the frames in the trun atom is different, your stream uses a more compact representation, and it's using a signed pts delay (this is wrong btw, since the trun atom reports version 0) but are than that they are equivalent
5. nginx-vod returns a tfxd atom, your stream doesn't have it
6. your stream has an sdtp atom, while nginx-vod doesn't

**Comment by utu2016** [comment]
Hi, 
very strange....btw..I suppose you're using last module version, is it right?
We have done test with 1.10 version; now we'll try with the last ver. to check if the problem disappears.

Thanks for your analysis.

**Comment by erankor** [comment]
Yes, latest version, though I don't recall changing anything in MSS lately.
The stream I provided is working well for you?

**Comment by utu2016** [comment]
yes your URL works.
Could you check using the 1.10 version? :-D
So we compare the result ....

**Comment by utu2016** [comment]
Hi Erankor, 
could you explain me how kaltura produce the CodecPrivateData ?
thanks

**Comment by utu2016** [comment]
thanks for the explaination & your support.
