### ISSUE TITLE
Is there a way to find out the play time?

### ISSUE THREAD

**Issue by massoudAfrashteh** [kaltura/nginx-vod-module#538]
I mean when you are viewing at 1:25 of video can I catch the time inside Nginx?

**Comment by erankor** [comment]
I'm not sure what you mean, but if you use mapped mode, you can configure notifications for certain timestamps (https://github.com/kaltura/nginx-vod-module/#set-top-level-object-in-the-mapping-json) So, for example, if you set a notification for time 0:55 and you use 10 sec segments, when the 6th segment is requested, nginx-vod-module will make an HTTP request to some upstream with a configured URL.
Note however that this way of tracking progress is very inaccurate, since the player usually buffers a few segments ahead.

**Comment by erankor** [comment]
@massoudAfrashteh, can we close this issue?
