### ISSUE TITLE
failed to identify the file format while reading media header

### ISSUE THREAD

**Issue by TadeoArmenta** [kaltura/nginx-vod-module#549]
I'm getting an error about the format on mkv files
ngx_http_vod_identify_format: failed to identify the file format while reading media header

i' m using mkvmerge 8.8 with no headers compression; this isn't happened on the original mp4 before the repack to mkv

how can i solve it?

====== UPDATE ======
i've just tested repacking the working mp4 with ffmpeg, without transcoding, and get the same error.

**Comment by erankor** [comment]
mkv support is disabled by default, to enable it you need to uncomment this line:
https://github.com/kaltura/nginx-vod-module/blob/master/ngx_http_vod_module.c#L235
The reason it's disabled is that mkv support is not as complete as mp4, for simple cases it will probably work fine, but some features are missing (e.g. clipping). Our main motivation for supporting mkv in the first place was for the vp9 codec, but since it can now be packaged in mp4, this has become lower priority for us.

**Comment by TadeoArmenta** [comment]
Many thanks, i'm compiling it right now

**Comment by aditya-vadlamani** [comment]
>  Our main motivation for supporting mkv in the first place was for the vp9 codec, but since it can now be packaged in mp4, this has become lower priority for us.

Correct me if I'm wrong. I've googled but didn't find any ways to encode an mp4 video in VP9 codec.  What I understood is that VP9 codec is exclusive to WebM videos. Any help regarding this conversion would be greatly appreciated.

**Comment by erankor** [comment]
Latest ffmpeg has support for packaging vp9 in mp4, here is a command line I used to test this long time ago:
`ffmpeg -i /tmp/test.mp4 -t 30 -c:v libvpx-vp9 -b:v 1000K -force_key_frames "expr:gte(t,n_forced*2)" -an -strict -2 -f mp4 -y /tmp/vp9.mp4`

**Comment by aditya-vadlamani** [comment]
Unable to convert. It says `Unknown encoder 'libvpx-vp9'`

**Comment by erankor** [comment]
Maybe your version of ffmpeg was compiled without this codec, or maybe they now use a different VP9 codec now (it's been a while since I tried it). Btw, if you already have a file encoded with VP9, you don't need it, you can use `-vcodec copy`.
But anyway, this is not an ffmpeg support forum...
