### ISSUE TITLE
is dash working with mkv files?

### ISSUE THREAD

**Issue by TadeoArmenta** [kaltura/nginx-vod-module#550]
May be i'm doing something wrong

```
location /vod/dash {
	alias /home/nginx/vod;
	vod_mode local;

	vod dash;
	
	add_header Access-Control-Allow-Headers '*';
	add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
	add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
	add_header Access-Control-Allow-Origin '*';
	expires 100d;
}
```

it retrieves the mpd file with no problems, but when start playing, trhows:

mkv_parse_frame: unsupported frame flags 0x1

==========UPDATE==========

it seems that is not only dash problem, hls says :

mkv_parse_frame: unsupported frame flags

if you can point me in the right direction, maybe can help expanding a little the mkv support

**Comment by erankor** [comment]
I checked the spec - https://www.matroska.org/technical/specs/index.html#simpleblock_structure
this flag simply means that the frame can be discarded, so you can add 'case 1:' next to 'case 0:' here - 
https://github.com/kaltura/nginx-vod-module/blob/master/vod/mkv/mkv_format.c#L1310
The samples I tested with so far didn't use this flag, and I preferred to be strict about the flags since some flags (lacing) require specific handling.

**Comment by TadeoArmenta** [comment]
case 1 works perfectly!! now i'm reading the especification for the flags 0x82 and 0x86. it seems to be lacing flags, using --disable-lacing on mkvmerge, removes this flags on de mkv file and play with no problems.

Also,  i found a set of mkv files for testing, so the goal will be to run the whole set without errors.

**Comment by erankor** [comment]
Thanks for the update, I merged this change

**Comment by erankor** [comment]
@TadeoArmenta, closing this for now, let me know if you encounter any additional issues
