### ISSUE TITLE
vod_hls_align_frames for DASH

### ISSUE THREAD

**Issue by siriusboehm** [kaltura/nginx-vod-module#551]
Hello,

I have a good amount of mp4s, which are used for normal html5 video, and want to serve a DASH version too. Works great, except for some files where the video and/or audio track have a `Start Time / PTS != 0`. Then sometimes video didnt start using shaka-player, but I fixed that by simply jumping directly to the Start Time.
I also tried Adaptive Bitrate, and if 2 Representations have a different PTS, an adaptation fails between those and the video stops, at least when using the DASH IF or Shaka Player.

So I was wondering if something like `vod_hls_align_frames` for DASH would be possible? Or should I somehow add an presentationTimeOffset to the Representation? (or maybe the right way is just to convert all files so that they have PTS=0?)

**Comment by erankor** [comment]
`vod_hls_align_frames` is not related to timestamps, it's about aligning the frames to mpeg ts packets.
But anyway, if you are on latest version, the module is compensating for the PTS/DTS diff in DASH and starts with PTS 0. If you are not getting PTS 0 on the first fragment with latest, it may be because of edit list, you can try to disable it with `vod_ignore_edit_list on`.
If that doesn't solve the issue, another thing worth trying is the branch `dash-validator-fixes`, this branch changes the DASH packager to use signed pts delay in the trun atom, and may solve this issue. This is a change we want to make anyway, but has been lingering for quite some time since we need to test it on all devices.

**Comment by siriusboehm** [comment]
Thanks, with new version 99% of the files work great. However some had still overlapping segments ( which makes the video stuck when switching). The DASH IF-Validator shows the following ( `vod_ignore_list on;` or using dash-validator-fixes branch did not make difference)

For each representation validation I get many of those errors 
```Warning: Media Header language code of 0 not strictly legit -- 'und' preferred
### error: moov-1:trak-1:mdia-1:minf-1:stbl-1:stsd-1 
### Validate_AVCConfigRecord: -2020
### error: 
### tfdt base media decode time 8.967289 not equal to accumulated decode time 8.967278 for track 1 for sequence_number 4 (fragment absolute count 5)
```

Cross Representation Validation shows many of those: 
```
Error: Overlapping segment: EPT of leaf 0.000000 for leaf number 2 for representation id ".." is <= the latest presentation time 8.925578 corresponding leaf for representation id ".."
```

Is there an issue with the source files?

**Comment by siriusboehm** [comment]
Sorry for trouble, seeems it was some caching issue, now all it works fine, thannks for the module!
