### ISSUE TITLE
Feature to store chunk length in seconds in variable

### ISSUE THREAD

**Issue by vs-adm** [kaltura/nginx-vod-module#573]
Hello.

Is it possible to implement the feature of storing requested chunk length in seconds of video content into nginx variable? I'd like to add this information into access log.

Thanks!

**Comment by erankor** [comment]
It is fairly easy to add this, but why do you need it? what do you want to do with this info?
Other than the last segment which may be shorter than configured, the duration of each chunk is known in advance.

**Comment by vs-adm** [comment]
I'll pass this information into aggregation system such as Elasticsearch and calculate various metrics on it such as application performance index and relative chunk serving time. Also with `vod_manifest_segment_durations_mode accurate` the segment length can't be known in advance.

Thanks.

**Comment by erankor** [comment]
Check out this branch https://github.com/kaltura/nginx-vod-module/pull/579
Note that this provides the rough segment duration, e.g. if the segment duration is 10 sec, and you have a 14.5 sec video, it will evaluate to 10000 in the first segment and 4500 in the second segment. It may be different than what you get with duration_mode=accurate, since the later takes into account frames that fall on segment boundary and keyframe alignment.

**Comment by vs-adm** [comment]
It is working. At least I am able to see segments duration in my logs. Thank you very much!

**Comment by vs-adm** [comment]
Is it possible to store accurate segment duration if `duration_mode: accurate` is set? Always having 10 seconds here gives a huge error on variable key frames interval streams.

Thank you in advance!

**Comment by erankor** [comment]
Sorry for the late reply... it is possible to implement this feature, but it's currently low priority for us, I will leave this issue open

**Comment by valyukov** [comment]
Hi there,
@erankor i've just started to work on this issue. Could you please give me some advice or guide me with the better way to implement this feature? I guess you have a vision which part of this module should be changed for evaluate correct and accurate duration of the segment. So that could help me save a lot of time on introducing myself with this codebase.

**Comment by erankor** [comment]
Try this pull - https://github.com/kaltura/nginx-vod-module/pull/806
Was easier to write than to explain...

**Comment by valyukov** [comment]
That works pretty accurate, thank you!

I wrote almost the same code for solve this, but summing frame duration one by one.

**Comment by erankor** [comment]
Thanks, merged
