### ISSUE TITLE
First frame duplicated with DASH VOD

### ISSUE THREAD

**Issue by ugljesas** [kaltura/nginx-vod-module#574]
We are making an application which requires frame accurate playback of DASH VOD streams. For some reason the first frame is displayed for the length of 3 frames and there is an offset that affects all the others.

Here is the configuration we are using:
vod_mode remote;
vod_upstream_location /s3;
vod dash;
vod_segment_duration 4019;
vod_align_segments_to_key_frames on;
vod_segment_count_policy last_rounded;
vod_dash_manifest_format segmenttimeline;
vod_manifest_segment_durations_mode accurate;
vod_last_modified_types *;

The example that demonstrates this: https://d180b6k3x2i95i.cloudfront.net/dash/58ebb7c19f7de16b83a72037/manifest.mpd
Tested with Shaka and Dash If players and both have the same issue - when seeking there's a ~0.1s (2 frames) offset between the timestamp in the MP4 and the stream.

HLS works fine with the same backing MP4.

Do you have any idea why this is happening?

**Comment by erankor** [comment]
I looked at the stream, all frames have the same duration (3600), my guess is that it happens because of the pts delay - the first frame has a pts delay of 7200, which matches what you write exactly.
I suggest you try with latest master, in the latest version the module outputs signed pts delays - it always aligns the pts delay of the first frame to zero. That may solve this issue.

**Comment by ugljesas** [comment]
It works with the latest master!

Thanks man, you're really amazing!

**Comment by erankor** [comment]
Great! thanks for the update
