### ISSUE TITLE
403 when using external file URLs

### ISSUE THREAD

**Issue by mrcatman** [kaltura/nginx-vod-module#599]
I want to organize a playlist with getting external JSON and using full URLs in it. But the server returns a 403 error.
 **`2017/05/13 12:17:54 [error] 2978#0: *108 ngx_file_reader_update_state_file_info: open() "http://playlist.myowntv.org/content/dummy.mp4" failed (13: Permission denied) while sending to client, client: 37.194.211.159, server: , request: "GET /content/playlist.json/seg-1-v1-a1.ts HTTP/1.1", host: "62.109.30.160"`**

The playlist:
`{
	"durations": [ 10000, 15000 ],
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "http://playlist.myowntv.org/content/dummy.mp4"
				},
				{
					"type": "source",
					"path": "http://playlist.myowntv.org/content/dummy.mp4"
				}
			]
		}
	]
}`

The server configuration:

http {
	upstream api {
		server playlist.myowntv.org:80;
	}
	
	server {
		# vod settings
		vod_mode remote;
		vod_upstream_location /api;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		vod_metadata_cache metadata_cache 512m;
		vod_response_cache response_cache 128m;
		
		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;
		
		location ^~ /api/ {
			internal;
			proxy_pass http://playlist.myowntv.org/;
		}
		

		location ~ /content {
			vod hls;
			vod_mode mapped;
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
	}
}

So, what am I doing wrong? Is there a possibility to do what I want?

**Comment by erankor** [comment]
It is possible to do it, but not like this :)
The reason is that nginx-vod-module does not issue http requests by itself, it uses nginx's proxy module for that. So you'd need an additional proxy_pass location that will be used to fetch the mp4 files. 
Another implication of this is that the paths in the JSON need to be relative URLs, nginx-vod-module will use these to create the internal nginx subrequest to the proxy_pass location.
If you are fetching files from a single domain, then it can be configured similarly to your existing `api` location. 
If you need to support multiple domain, you can use this trick:
```
	location ~ /remote/([^/]+)/([^/]+)/(.*) {
		internal;
		proxy_pass $2://$3?$args;
	}
```
In this case, instead of `http://playlist.myowntv.org/content/dummy.mp4` you'd set the path to `/http/playlist.myowntv.org/content/dummy.mp4` in the JSON. The regex in the location will separate the scheme and the domain name, and send them to proxy_pass. Note that if your server is publicly facing, such a configuration makes it possible for anyone to make your server pull arbitrary resources from arbitrary domains, which may not be ideal in terms of security.
Finally, you will need to add `vod_remote_upstream_location /remote`, this will tell nginx-vod to treat the paths in the JSON as relative URLs, by default it treats them as file paths (that is the reason you get error 403, it tries to open a local file called `http://playlist...`)
