### ISSUE TITLE
Live example

### ISSUE THREAD

**Issue by ut0mt8** [kaltura/nginx-vod-module#611]
Hello,

I am quite new on this module. I am hacking for some time the nginx-rtmp module.

Does it is possible to use nginx-vod module with nginx-rtmp to serve live content ? (dash)
My use was to send rtmp from elemental live server to nginx-rtmp and package it in dash with DRM.
(nginx-rtmp does not handle DRM for now, I work on it but it is rather complex).

And if so an example of nginx configuration (or pointer will be welcome).

**Comment by erankor** [comment]
We haven't integrated with nginx-rtmp, we are currently using Wowza as our live ingest point. The HLS output from Wowza is then transformed to nginx-vod input format using this project https://github.com/kaltura/livedvr. It should be possible to make it work with nginx-rtmp, but will most likely require some changes (e.g. livedvr currently requires that the HLS stream has ID3 tags with absolute timestamps). Also, unfortunately, livedvr is not well documented, so may not be easy to set it up.

**Comment by suxonca** [comment]
Hi,
Please,
 Could you post a simple example of configuration for HLS from a local file and from a http file server?
Thanks a lot.

**Comment by erankor** [comment]
there are sample configurations for local and remote here - https://github.com/kaltura/nginx-vod-module/#sample-configurations
also, please avoid using existing issues for unrelated questions

**Comment by suxonca** [comment]
ok. thanks

**Comment by joaoserra** [comment]
One feature I would like to see is support for re-streaming live DASH streams, it would work more or less like the Continuous live Playlist feature. The use-case would be to receive a DASH stream from "stateful" packagers like shaka-packager/Wowza/mod-rtmp that support a multitude of inputs like live MPEG-TS or RTMP and use nginx-vod-module to do the final SS/DASH/HLS packaging and DRM. 

The Continuous live Playlist features uses a playlist of MP4 files, the idea would be the same here, the only differences would be the audibility read MPDs instead of JSON, and f-MP4's instead of "normal" MP4s

**Comment by erankor** [comment]
Thanks @joaoserra, that's basically what we do in the project I mentioned above (https://github.com/kaltura/livedvr), the differences being:
1. We take an HLS stream as input (not DASH)
2. Instead of having nginx-vod-module read additional formats, we repackage the segments from MPEG-TS to regular MP4
3. Instead of having nginx-vod-module parse a manifest, as the segments are being downloaded, livedvr updates a JSON file that uses nginx-vod-module format.

**Comment by joaoserra** [comment]
@erankor Do you guys have an ETA for livedvr documentation?

I'm guessing livedvr does more that simply re-streaming live HLS do regular MP4 fragments, given it's name, i'm assuming it does things like NDVR/live2vod functionality.

But i'm a bit curious of why do you choose that architecture for live streaming scenarios.
Let's imagine a simple live streaming scenario from a muticast MPEG-TS source: FOSS software like Google's  shaka-packager already does MPEG-TS->DASH and i guess nginx-vod-module codebase already supports 95% of the functionality i'm proposing (It just needs to parse MPDs and support f-MP4 input)  
It feels strange to use another piece of software basically as a proxy only...

**Comment by ut0mt8** [comment]
Thanks for your response. The thread is interesting.
If I understand the only possible input is mp4 file.
I am thinking of repackaging dash mp4 from nginx-rtmp (or other) with nginx-vod to add DRM.

I think I really had to implement it by myself.

**Comment by erankor** [comment]
@ut0mt8, the input is either mp4 or mkv (partial support)
@joaoserra, the main motivation behind the livedvr project was (as the name suggests :)) to add DVR to the stream. By DVR I don't mean live2vod, but rather returning a larger live window to the user, and enabling him/her to be a certain amount of minutes/hours behind real time. 
When we started with live, we used Wowza's DVR capabilities, but had lots of problems with it, while regular (non DVR) streams worked well. Adding DVR to a live stream requires state, it is not something that can be done on-demand as nginx-vod-module works.
So, we decided to pull the DVR out of Wowza, and then the livedvr project was born. The first phase simply saved the TS segments in disk and returned a larger m3u8 manifest (it supported only HLS). But then we wanted to support DASH, DRM, tokenization etc. Since we had all these features for VOD based on nginx-vod-module, we decided to reuse the existing code and change livedvr so that instead of producing HLS output, it will produce an output in the format nginx-vod-module expects.
That's the history & reasoning behind this architecture, it is working well for us on production for several months now.
It is true that if all you need is to convert a DASH stream to HLS or DASH with DRM or some other format, it is something that can be efficiently done on demand/stateless, but as I just explained that wasn't enough for us.
Regarding documentation, I'm not working on this project (livedvr) but no ETA as far as I know.

**Comment by joaoserra** [comment]
Thanks for the explanation!

Just a quick question: What problem did you had with Wowza's DVR? I've used it with no problems.

**Comment by ut0mt8** [comment]
Thks for all your comment. I am digging in the code of nginx-vod (as you already pointed me in a mail) to understand common encryption implementation.
Not very easy ; but fun to understand.

**Comment by kalturaguy** [comment]
Wowza DVR had many issues at the past and also wasn't supported with DASH
