### ISSUE TITLE
Recommended ffmpeg settings for dash streaming?

### ISSUE THREAD

**Issue by frutality** [kaltura/nginx-vod-module#622]
Hello!

I'm encountering one problem at playback DASH videos. Not sure why — probably it's because of ffmpeg encoding options, but maybe something else. I would appreciate any help and hints with investigating.

I have `webm` files from media server. Then I convert them to `mp4` with following command: `ffmpeg -i input.webm -fflags +genpts -crf 23 -preset veryfast -r 24 -g 48 output.mp4`.

Playing it with `video.js` + `dash.js plugin`. Also tried to play it with http://dashif.org/reference/players/javascript/v2.5.0/samples/dash-if-reference-player/index.html

**Problem:** when I click at random points at timeline, playback sometimes stuck. However, `Network` tab at devtools shows that `m4s` fragments are loading all the time with 200 code. I mean, I see stucked video and a lot of loaded fragments. No errors at console, no errors in logs.

My ideas:
1. Something wrong with `ffmpeg` command. Maybe you have some perfect mp4 file which I could test with my server? Or maybe you have ideas what to change.
2. Something wrong with server itself. Maybe it has too low RAM or CPU? It's 1 gb Digital Ocean droplet. But it also has php, mysql, redis, centrifugo installed and running. `top` shows 226 mb free RAM however.
3. Something wrong with nginx config? I pasted it here https://github.com/kaltura/nginx-vod-module/issues/620

I'm pretty sure `nginx-vod-module` is fine, but I really need some hints because I'm stuck now. It should be something simple.

**Comment by frutality** [comment]
Wow, after posting this issue, I see 404 error at 741th fragment. It's first time when I see 404. Kinda strange.

**Comment by erankor** [comment]
Hard to say without checking the stream, but I would guess the key frames are too far apart. If that is the case (gop size > segment duration) some segments return empty, and some players don't like that.
If that is not the case, please send a URL

**Comment by frutality** [comment]
How do you prepare mp4 files? 

I'm using `ffmpeg`. And I can say, it's not very simple, when I try to set correct GOP size. 

According to docs, there is `-force_key_frames "expr:gte(t,n_forced*4)"` option, where `4` is `key frame every 4 seconds`. I just tried it, and playback became even worse. (I'm using `vod_segment_duration 4000`). Am I understanding something wrong, or there may be ffmpeg bug?

**Comment by erankor** [comment]
yes, that's the param we use to force keyframes. 
we prepare the videos using our platform :) - https://github.com/kaltura/server/
you can open a trial account on our SaaS platform, upload the source video there and check whether the resulting video plays as expected.
alternatively, you can send URLs to the mp4 file and stream and I can check if I see anything problematic there.

**Comment by frutality** [comment]
Ok, thanks, I'll try your platform anyway.

There is video: https://ipoedinki.ru/storage/videos/nego133-merge-1495257731000.mp4/manifest.mpd

You didn't mention server requirements. I guess our droplet is fine for vod-streaming? I mean, if we don't have many users. Right now it's only me.

**Comment by erankor** [comment]
I can't play this stream at all, if you take play the MP4 directly in the browser does it work ok?
Regarding server requirements, the module is very light weight, if you have enough RAM (to keep the video metadata) the limiting factor will most likely be the server network.

**Comment by frutality** [comment]
No, it doesn't play too.

I reencoded video with other settings and reuploaded file (same link). Could you check again, please? It seems to work for me. However, sometimes, in Firefox video stucks when I timeseeking. But I'm pretty sure this is player or browser problem.

>if you have enough RAM (to keep the video metadata)
Is this related to `vod_metadata_cache` and/or `vod_response_cache` settings?

And there is another question. What do you recommend as GOP size, if `vod_segment_duration` is 4000ms?
1. 4s
2. 2s
3. 8s
4. Your option

**Comment by erankor** [comment]
The stream looks ok to me, also tried seeking a bit in Firefox/Shaka and didn't have any problems.
Regarding RAM, the way this module works when processing a video, it loads all its metadata (moov atom) to memory, it can't process the metadata in chunks. Usually this metadata isn't very large, but for long videos it can be (I've seen extreme cases of videos with ~200MB of metadata). You must have enough RAM to fit the metadata of all active requests in memory.
The vod_metadata_cache directive that you mentioned enables the caching of this metadata in shared memory. This is a significant optimization since without it the module will have to reload the metadata for each segment request of the same video. Therefore, it's recommended to have few GB of this cache (you can check the hit/miss ratio in the status URL to know whether you need a larger cache or not)
Regarding GOP, we use 2 seconds, we're currently using segments of 4 sec in DASH, 6 sec in HDS and 10 sec in HLS (with several 2 sec bootstrap segments). If you aim for segment duration of 4 sec, then use either 2 sec or 4 sec.

**Comment by frutality** [comment]
Thank you very much. You are very helpful.
