### ISSUE TITLE
How do you name the JSON file(s)?

### ISSUE THREAD

**Issue by adcprod** [kaltura/nginx-vod-module#630]
First off, thanks for this module.  This work seems really well done and documented!  We can't wait to fire it up and play with it.

Anyway, a partner and I are looking at the instructions for this module and trying figure out exactly what to call the JSON files for the mp4 segment playlists.  (To be clear, I'm not referring to the DASH/HLS manifests or any of that stuff.)  Does the system pick up multiple playlists (perhaps with some regex prefix or postfix)?

Also, where would you put the JSON(s) or state where you put it/them?

Thanks so much in advance!

**Comment by erankor** [comment]
The JSONs can be loaded either from local files or from a remote server (by having nginx-vod-module issue an HTTP request). From your question, I assume you are referring to the first option. 
Let's say the location in nginx.conf looks like:
```
location /hls/ {
    vod hls;
    alias /web/;
}
```
For the request `http://domain/hls/some/path/video.json/index.m3u8` nginx-vod-module will try load `/web/some/path/video.json`. You can also use nginx's `root` directive instead of `alias` and then the path will be `/web/hls/some/path/video.json`.
Regarding the location of the files, in our case, we build the JSONs dynamically (we use the second option I referred to), so we have no JSON files on disk. For the video files, we use the path `/web` (historically, this is where our shared storage is mounted on all servers)

**Comment by erankor** [comment]
@adcprod, can we close this issue?
