### ISSUE TITLE
PPA / repo for libnginx-mod-vod

### ISSUE THREAD

**Issue by matclayton** [kaltura/nginx-vod-module#633]
It would be fantastic to provide an official PPA for the nginx module this produces to save everyone from having to compile it from source.

**Comment by jessp01** [comment]
Hi @matclayton,

We already do provide kaltura-nginx deb packages in our own repos.
For Ubuntu 12.04/14.04, see:
https://github.com/kaltura/nginx-vod-module#debianubuntu-deb-package

For 16.04, see my comment here:
https://github.com/kaltura/nginx-vod-module/issues/628#issuecomment-309233454

Thanks,

**Comment by matclayton** [comment]
I meant specifically the dynamic lib, not the whole of nginx+lib, or did I misunderstand what you guys provide there?

See. https://www.nginx.com/blog/creating-installable-packages-dynamic-modules/

**Comment by jessp01** [comment]
Hi @matclayton,

No, you understood correctly. However, we do support building only the DSO. This is documented here:
https://github.com/kaltura/nginx-vod-module#build

When we first started this project, Nginx didn't support DSO at all and so, we HAD to package the full server. Now, since most stable distros still have a version of Nginx that is older than 1.9.11, where DSO was first introduced, we still can't give up on a full package and use the Nginx package from the distro. 
In the future, once all distros we need to support include a higher Nginx version, we could provide a package that only consists of the DSO. For now, if that's what you need, you'll have to build it yourself.

If you have any issues, feel free to post them,

**Comment by matclayton** [comment]
Thanks, makes sense.

FYI or for future folk who find this issue, we've since managed to compile VOD 1.18 with nginx 1.12.0 using the build_module.sh referenced on https://www.nginx.com/blog/creating-installable-packages-dynamic-modules/ and are expecting to host a local apt repo to deal with this.

**Comment by jessp01** [comment]
Hi @matclayton,

I looked at the build_module.sh script by the Nginx team. It's a nice script but as with everything in life, there are things to be aware of:

- Depending on whether you passed -v or -r It creates a dep on the nginx or nginx-plus package.
This can be seen in the control file for the package under ~/debuild
in my case for example:
/home/jess/debuild/nginx-1.13.1/debian/debuild-module-vod/nginx-1.13.1/debian/control
```
Depends: ${misc:Depends},
         ${shlibs:Depends},
         nginx (= 1.13.1-1~xenial)
```
However, the official Xenial repo has:
```
root@jessex:/tmp# apt-cache policy nginx
nginx:
  Installed: (none)
  Candidate: 1.10.0-0ubuntu0.16.04.4
  Version table:
     1.10.0-0ubuntu0.16.04.4 500
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages

```
So a higher version of the Nginx deb package must be fetched [from a PPA repo for instance] and installed in order for this to work.
Of course, one can manually edit the control file to set a dep on a different deb package that provides Nginx or else just drop this dep entirely in the event some self compiled Nginx is used and rebuild the package but it is something to be aware of. For ABI compatibility reasons, it is very important to compile against headers from the same version you intend to use at runtime

- The VOD module has several features that require the use of ffmpeg. 
These are described here:
https://github.com/kaltura/nginx-vod-module#dependencies
If you intend to use any of these, you must have the ffmpeg shared objects/static archives as well as the headers on the build machine. Our repo includes a kaltura-ffmpeg package that can be used but note that it does not include libfdk due to licensing issues and so, if you want to utilise the audio filtering capabilities, you'll need to compile your own ffmpeg.
