### ISSUE TITLE
Force unmuxed hls playlists

### ISSUE THREAD

**Issue by mazanov** [kaltura/nginx-vod-module#644]
Sometimes in mapping mode I pass json with several video tracks but with only one audio track.
In this case nginx vod module generate master playlist with muxed (audio + video) index playlists.
Is it possible to force nginx vod module to generate hls master playlist with separated (unmuxed) audio and video index playlists (hls revision 7 from September 30, 2011 - or later)?
It's good solution for improving CDN caching (usually I need to have multiple audios in playlist, but sometimes _I had to have_ only one audio).

**Comment by erankor** [comment]
This is currently not supported, but it's a very simple change in case someone wants to submit a pull. Need to:
1. add some param for it in m3u8_config_t
2. use the param to decide whether to send ADAPTATION_SETS_FLAG_MUXED in m3u8_builder_build_master_playlist
3. in m3u8_builder, need to change the `count[ADAPTATION_TYPE_AUDIO] > 1` ifs to `count[ADAPTATION_TYPE_AUDIO] > 0 && total_count > 1` (so that EXT-X-MEDIA will be used when there's a single audio as well)

**Comment by mazanov** [comment]
Thanks! Will try to do this.

**Comment by erankor** [comment]
Closing, following @tim-lansen's pull
