### ISSUE TITLE
Chunk request parameters

### ISSUE THREAD

**Issue by mazanov** [kaltura/nginx-vod-module#648]
When requesting DASH chunks I get fragment url something like this:
`fragment-5-f1-v1-x2.m4s`
I understand that -f means file id, -v means video id and -a means audio id. But what does mean -x? Does it really required? It seems that nothing changes when I change or delete -x parameter.
Also, can you please describe what additional parameters can be used (besides -v, -a and -x)?
Thank you!

**Comment by erankor** [comment]
I'll add a todo to add this to the readme... 

Anyway:
'i' - segment index shift - the "real" segment index is sum of this value and the segment index. Used in dash playlist with segment template format. The segment index in this case is $Number$ which starts at zero for all clips, the -i parameter keeps the real index continuous.
'c' - select clip by index - used in init segments & subtitles in dash playlist
'f' - select file/sequence by index - f1 is the first url in a urlset, f2 is the second etc. *
's' - select file/sequence by id - same as 'f' except that the sequence is identified by the `id` sent in the JSON *
'v' - select video track by index (0 = all) *
'a' - select audio track by index (0 = all) *
'p' - extra pts delay - was used in the past to align the pts of different renditions in dash, not in use since the code was changed to use signed pts offsets
'l' - select language by 3 letter code (ISO639-2) - useful for alternative audio tracks/subtitles *
'x' - format version - used in order to safely deploy breaking changes. e.g. when deploying the timestamp change i mentioned above, if a client would pull segment 1 in the old format and segment 2 in the new format, it won't play. And, since we use a CDN, it can remain like that for a long time (it's not temporary during the transition...). Incrementing the -x version produces a new URL - clients who got a manifest with -x2 will play only version 2 while clients who got -x3 will play only version 3.

A couple of comments:
1. items marked with * can repeat multiple times (v1-v2 = first & second video tracks)
2. a/v can be combined with f/s, e.g. f1-v1-f2-a1 = video1 of file1 + audio1 of file2, f1-f2-v1 = video1 of file1 + video1 of file2

**Comment by mazanov** [comment]
Can you please provide an example, when I'll get -x2 and when -x3?

**Comment by erankor** [comment]
For a given source version + protocol, the number is fixed (to put it differently - it's hardcoded). 
If in the future I will need to apply some breaking change to HLS, for example, I will update the code to add -x2. During the upgrade, clients who got the manifest from the old version will continue making requests without -x2 and will get segments in the 'old' format, while clients who got a manifest from the new version will have -x2 and will get segments in the new format.

**Comment by mazanov** [comment]
Now I got it, thanks!
