### ISSUE TITLE
Add EXT-X-SESSION-KEY to FairPlay HLS playlists

### ISSUE THREAD

**Issue by mazanov** [kaltura/nginx-vod-module#674]
EXT-X-SESSION-KEY is needed for offline FairPlay HLS playback.
As I can understand for now, EXT-X-SESSION-KEY attributes are similar to EXT-X-KEY attributes:
`#EXT-X-SESSION-KEY:METHOD=...,URI="...",KEYFORMAT="...",KEYFORMATVERSIONS="..."`
Is it possible to make configuration directives for adding EXT-X-SESSION-KEY?

**Comment by erankor** [comment]
It's problematic, because EXT-X-KEY is returned per rendition, so it can have different URL / different keys on the same set. Depending on configuration, it may return invalid URL / one that does not match the EXT-X-KEYs. While it can work in some cases, my concern is that it's very prone to miconfiguration.
Also, from our experience, while it is recommended to have this tag, it works perfectly fine without it.

**Comment by mazanov** [comment]
> EXT-X-KEY is returned per rendition, so it can have different URL / different keys on the same set.

That's clear for me

> Depending on configuration, it may return invalid URL / one that does not match the EXT-X-KEYs. While it can work in some cases, my concern is that it's very prone to miconfiguration.

Can you please give examples when it wouldn't work? 
As I see, logic of adding EXT-X-SESSION-KEY should work same as adding EXT-X-KEY. So if EXT-X-KEY is working now for any rendition, why EXT-X-SESSION-KEY should not work?

> while it is recommended to have this tag, it works perfectly fine without it.

iOS can natively play hls offline (first - download, second - play at any time offline without internet connection) only with EXT-X-SESSION-KEY

**Comment by erankor** [comment]
1. The sample configuration for HLS AES-128 is an example - https://github.com/kaltura/nginx-vod-module/#mapped-configuration the secret key seed depends on $vod_filepath, it is different for each URL in the urlset. I'm not sure whether this variable will even evaluate to anything in the context of master.m3u8.
2. I checked with our iOS team, and it works for them, including iOS 11. However, they did mention that iOS 11 added a new API which they didn't test yet (they use the iOS 10 API so that it will work on both versions)

**Comment by mazanov** [comment]
Thanks for answer!
We are checking how downloading works without this tag.

**Comment by mazanov** [comment]
It seems to work fine, thanks!
Closing this. Maybe will return in future (new iOS version, etc)

**Comment by samizas** [comment]
Hello,
I've got to make downloading work, but my Server (Wowza) doesn't use the EXT-X-SESSION-KEY tag for now. Did you manage to make it work without this tag? Then how?
Thx!
