### ISSUE TITLE
Dash DRM, how to use different KID per asset?

### ISSUE THREAD

**Issue by AquileaSFX** [kaltura/nginx-vod-module#690]
Hello, 

first of all, thank you for this marvellous module, I get very excited each time I use it and work with it, thank you very much.

ok, I enabled DRM, the resulting manifest uses the same KID for audio and video, my question is, it is possible to set different KID per asset?

I tried with the following json with no results:
[{
		"type": "SD",
        "pssh": [{
                        "data": "aDM0aDM0MjNrMDAyODVtbW1tZ2dnZzMyNDM0MmRmYWRm",
                        "uuid": "edef8ba979d64acea3c827dcd51d21ed"
                }],
        "key_id": "MTIzNDU4Nzg5MDAwMDAwMg==",
        "key": "MTIzNDU2Nzg5MDIyMjIyMg=="
        
},
{
		"type": "AUDIO",
        "pssh": [{
                        "data": "aDM0aDM0MjNrMDAyODVtbW1tZ2dnZzMyNDM0MmRmYWRm",
                        "uuid": "edef8ba979d64acea3c827dcd51d21ed"
                }],
        "key_id": "MTIzNDU2Nzg5MDMzMzMzMw=="",
        "key": "MTIzNDU6Nzg5MDAwMDAwMg=="
        
}]

thank you.

**Comment by erankor** [comment]
The DRM parameters are requested per sequence, not per track. The reason is that in HLS/HDS the module outputs by default muxed (audio+video) segments, and it is not possible to encrypt the two tracks with different keys.
If you are using only DASH/MSS, you can force the audio/video into separate sequences, and then you'll be able to set different DRM parameters for them. 
If you are using mapped mode, you can split each sequence object in two, one will have `"tracks": "v1"` and the other `"tracks": "a1"`.
If you are not using mapped mode, you can do it on the URL, e.g. if you have `/dash/some/video.mp4/manifest.mpd`, you can use - `/dash/some/video.mp4/tracks/,v1,a1,.urlset/manifest.mpd`. This will create two separate sequences and will therefore issue 2 requests to the DRM server. However, I don't think you'll be able to differentiate between the request for the audio and the request for the video. 
One way to solve that is to create some link in the file system, so that you'll be able to access each file with 2 paths, e.g. /video/file.mp4 and /audio/file.mp4 will point to the same file. Then you can use a URL like `/dash/,video/tracks/v1,audio/tracks/a1,/file.mp4/manifest.mpd` and you will get 2 different requests to the DRM server.

**Comment by AquileaSFX** [comment]
Hello @erankor,

thank you very much, I will try to create two locations pointing to the same file, and a third one to generate the final url, I will post my results later on.

Bryan

**Comment by erankor** [comment]
@AquileaSFX, can we close this issue?

**Comment by AquileaSFX** [comment]
yes please,

thank you very much.
