### ISSUE TITLE
Why is using the vod directive in a if case not allowed 

### ISSUE THREAD

**Issue by j-licht** [kaltura/nginx-vod-module#694]
When I write in my nginx conf: 
`location /content/ {
                        alias /path/to/files/;
                if ($foobar) {  vod hls;}
}`
nginx start say: `nginx: [emerg] "vod" directive is not allowed here in /etc/nginx/nginx.conf`

**Comment by erankor** [comment]
You can enable it by adding `| NGX_HTTP_LIF_CONF` here -
https://github.com/kaltura/nginx-vod-module/blob/master/ngx_http_vod_conf.c#L815
Never tried it, but it will probably work.

However, I prefer not to merge this change since, in general, use of `if` in nginx is discouraged.
We are using `if` only for very limited use cases such as -
1. `if (cond) { return 200 "body"; }`
2. `if (cond) { set $var value; }`

**Comment by erankor** [comment]
@j-licht, can we close this issue?

**Comment by j-licht** [comment]
I don't tried it.
But I read the If is Evil articel from NGINX.
