### ISSUE TITLE
Do I need to install nginx before installing kaltura-nginx ?

### ISSUE THREAD

**Issue by codegeek1001** [kaltura/nginx-vod-module#708]
Sorry for asking such a noob question but it wasn't clear to me from the readme. Do i do a generic nginx install before installing kaltura-nginx ?

**Comment by jessp01** [comment]
Hi @codegeek1001,

No, you do not. kaltura-nginx provides the nginx binary with the following Nginx modules statically linked into it:
- nginx-vod-module
- nginx-secure-token-module
- nginx-akamai-token-validate-module
- nginx-module-vts
- nginx-rtmp-module

At any rate, since we provide RPM and deb packages, even if that were not the case, nginx would have been declared as a dependency in the RPM/deb spec files and would have been fetched automatically when installing kaltura-nginx.
Our deb and RPM spec files are available here, in case you're interested:
https://github.com/kaltura/platform-install-packages/blob/Mercury-13.3.0/RPM/SPECS/kaltura-nginx.spec
https://github.com/kaltura/platform-install-packages/blob/Mercury-13.3.0/deb/kaltura-nginx/debian
