### ISSUE TITLE
Long playlist generation

### ISSUE THREAD

**Issue by mrcatman** [kaltura/nginx-vod-module#710]
I'm trying to implement playlist broadcasting on my site, including cycled playlists. At first, all went well, but I noticed that playlists have a maximum duration (about 2 weeks), and if a playlist exceeds it, the server just responses with 503's. Then I wrote a script that generates only a part of a playlist (2 clips before current video and ~10 after it) and uses absolute times (array of ClipTimes). But it's only working until current clip does not begin to come to an end, and then players (like videoJS) start to print errors, and after ~20 seconds the stream ends.

```
video.js:489 VIDEOJS: ERROR: TypeError: Cannot read property 'duration' of undefined
    at sumDurations (videojs-contrib-hls.js:4240)
    at SyncController.getExpiredTime (videojs-contrib-hls.js:6983)
    at MasterPlaylistController.onSyncInfoUpdate_ (videojs-contrib-hls.js:1880)
    at SegmentLoader.<anonymous> (videojs-contrib-hls.js:988)
```

Another parameters of a playlist are always the same:
`{"initialClipIndex":1,"initialSegmentIndex":1,"discontinuity":true,"playlistType":"live"`

Am I doing something wrong and are there another ways of solving that except recompiling the module with bigger maximum duration in source code?

**Comment by erankor** [comment]
If what you meant is that you are always sending initialSegmentIndex = 1 and initialClipIndex = 1 then it's definitely wrong, these values have to grow whenever you remove a video from the end of the playlist.
In general, it's not easy to get all the parameters correctly, it's complex is because nginx-vod-module is stateless. Therefore, I suggest you test with the sample script provided here - https://github.com/kaltura/nginx-vod-module/blob/master/test/playlist.php and match your logic to what is implemented there.

**Comment by erankor** [comment]
@mrcatman, can we close this issue?
