### ISSUE TITLE
Compability problem with ngx_aws_auth and nginx-vod-module

### ISSUE THREAD

**Issue by xird** [kaltura/nginx-vod-module#717]
Hi

Here's some background about our situation: We're running a VOD streaming service. We've been successfully using the ngx_aws_auth module (https://github.com/anomalizer/ngx_aws_auth/) to authenticate proxy_passed requests to S3 API end points with parts of our video platform.

Now, we decided to try using Nginx and the Kaltura nginx-vod-module (https://github.com/kaltura/nginx-vod-module) as our streamers. The idea was to proxy_pass the S3 requests like we've been doing. Note that we're not using the S3 "static website hosting" feature, but instead the S3 API end points. This is so that we can use signed requests for authentication(which is what ngx_aws_auth is for).

After installing both modules, we quickly discovered that we're getting nothing but 403s from S3. Further digging revealed that the AWS signature headers were missing from the requests sent to S3, even though the Nginx configuration had the "aws_sign" command in the appropriate location.

After debugging for a while, we found the problem at ngx_aws_auth/ngx_http_aws_auth.c:150 . The line in question calls "ngx_http_get_module_loc_conf", which, according to documentation, "..gets the module’s http location block configuration object from the request object". The returned conf object is then checked with "if(!conf->enabled) {". For requests that have been processed by the nginx-vod-module, this check returns true. In other words:

When a request has been processed with "vod hls;", the conf object returned for the request doesn't have the "module enabled" flag set for ngx_aws_auth. Since that's the case, ngx_aws_auth thinks it's not enabled, and won't sign the request.

Now I don't know anything about how Nginx modules work, so I don't know if this is a bug in ngx_aws_auth or nginx-vod-module. As such, this bug report has been added to both projects' issue queues. Please let me know your thoughts about which module is the cause of the problem, so we can continue the discussion in the appropriate ticket.

Relevant parts of the Nginx configuration follow. The "test" location is to confirm that the authentication works without nginx-vod-module.

```
server {
  listen     80;

  vod_mode remote;
  vod_upstream_location /s3;

  location /s3/ {
    aws_access_key "REDACTED";
    aws_key_scope "20171005/eu-west-1/s3/aws4_request";
    aws_signing_key "REDACTED";
    aws_s3_bucket my-example-video-bucket;
    aws_sign;

    rewrite ^/s3/hls/(.*) /$1 break;
    
    proxy_pass http://my-example-video-bucket.s3.amazonaws.com;    
  }

  location /hls/ {
    vod hls;
  }

  location /test/ {
    aws_sign;
    rewrite ^/test/(.*) /$1 break;
    proxy_pass http://my-example-video-bucket.s3.amazonaws.com;
  }
}
```

**Comment by erankor** [comment]
I'm only guessing here... but try to remove the rewrite - you can remove the `/s3/hls/` part of the url without rewrite by changing the location to `location /s3/hls/` and adding / at the end of the proxy_pass directive - `proxy_pass http://your-bucket.amazonaws.com/`

**Comment by xird** [comment]
Removing rewrites has no effect; still no signature headers. It seems to me that nginx-vod-module does something to the request object, after which the things ngx_aws_auth is looking for are no longer there.

**Comment by xird** [comment]
Here's the simplified configuration, where /test works fine, but /hls does not.

```
server {
  listen     80;

  vod_mode remote;
  vod_upstream_location /s3;

  location /s3/ {
    aws_access_key "REDACTED";
    aws_key_scope "20171005/eu-west-1/s3/aws4_request";
    aws_signing_key "REDACTED";
    aws_s3_bucket my-example-video-bucket;

    aws_sign;
    proxy_pass http://my-example-video-bucket.s3.amazonaws.com;
  }

  location /hls/ {
    vod hls;
  }

  location /test/ {
    aws_access_key "REDACTED";
    aws_key_scope "20171005/eu-west-1/s3/aws4_request";
    aws_signing_key "REDACTED";
    aws_s3_bucket my-example-video-bucket;

    aws_sign;
    proxy_pass http://my-example-video-bucket.s3.amazonaws.com;
  }
}
```

**Comment by erankor** [comment]
I checked it out, ngx_aws_auth is written as an access phase handler - when it runs, it adds the Amazon headers to the 'input headers' array of the request. This works since by default Nginx's proxy module forwards all input headers to the upstream. It doesn't work in this case, since it seems nginx subrequests (which is what nginx-vod-module uses to call the upstream) doesn't go through the same phases as regular requests.
I'm not sure the way ngx_aws_auth is written is the right way to do it - it may have been better to write the module so that it exposes nginx variables for the different headers that should be sent, and have the user do something like this:
```
    add_header x-amz-content-sha256 $aws_auth_signature;
    add_header x_amx-date $aws_auth_date;
    add_header authorization $aws_auth_authoriation;
```
This config is slightly more complex, but it's much more flexible, it would have enabled you, in this case, to set the headers using Nginx's proxy_set_header directive, and it doesn't have the hacky behavior of updating the origin request header.
But anyway, all that said... if you move all aws_xxx directives to the /hls location, it should work, since it will update the incoming headers of the main request, and nginx-vod-module takes care of copying the incoming headers to the subrequests it creates.

**Comment by xird** [comment]
Unfortunately, moving the aws_* directives won't work either, since the path used for signing is different during the signing and during the proxy pass. In this case, the vod module redirect adds the "/s3/" in the path, which causes a signature mismatch.

Anyway, thanks for looking into it! I'll add your findings in the ticket queue for ngx_aws_auth: https://github.com/anomalizer/ngx_aws_auth/issues/47

**Comment by erankor** [comment]
Ok, well, another option for solving this on ngx_aws_auth's side is to add a configuration directive for choosing the uri part to sign. By default it will be `$uri$is_args$args` (as currently done by the code there), but it will enable the user to override it. In this case, it will be set to a variable captured from a location regular expression.
The downside of this approach is that it won't work with nginx-vod-module uriset - since there a single incoming URL maps into multiple upstream URLs (the approach I detailed in the previous comment, on the other hand, will work for uriset).
Anyway, I'm closing this issue, since there is nothing I can do about it from my side.

**Comment by erankor** [comment]
@xird, I checked why the aws_auth handler doesn't run for subrequests, and saw that nginx doesn't call access phase handlers for subrequests, but other phase handlers are executed for subrequests.
So, a quick workaround for this issue is to move ngx_aws_auth from the access phase to the pre-access phase. New nginx versions have a pre-content phase, which is probably the most suitable here, but these versions currently don't work with nginx-vod-module.
Anyway, just change NGX_HTTP_ACCESS_PHASE to NGX_HTTP_PREACCESS_PHASE in ngx_aws_auth and you should be set.

**Comment by xird** [comment]
You, sir, are a gentleman and a scholar! This simple change fixed the issue, and we can now continue setting up our new streamer origins. Thanks!

I've also left a PR for ngx_aws_auth with the same change in it.

**Comment by erankor** [comment]
Great, thanks for the update!

**Comment by erankor** [comment]
All - fresh out of the oven - an alternative module for AWS authentication - 
https://github.com/kaltura/nginx-aws-auth-module

This module uses the approach I suggested 1.5 years ago, and it is IMHO a better solution, since -
1. It doesn't have the hacky side effect of changing the incoming request headers
2. It is easier to set up - no risk of mismatch between the host/uri that get signed and the ones that are sent on the request
3. It is written in strict nginx standards

@mlevkov - FYI - this new module can be used with role based authentication, a python script similar to the provided sample can be executed periodically, to generate the key. A file with the generated key can be `include`-ed from nginx.conf (requires a periodic reload, but since reload doesn't clear vod caches, don't think there's any problem with it...)

**Comment by mlevkov** [comment]
@erankor Thank you for sharing. I will look into this. Our S3-helper module automatically obtains credentials, and of course, it manipulates headers, however, this is certainly a viable consideration. Though, I was more looking for getting the fully integrated reload process whenever key expires.

**Comment by erankor** [comment]
@mlevkov, right, you will need to periodically update a portion of the conf file (btw, I suggest putting it on a separate file and `include`-ing it) and reload nginx. But, it will probably be much more efficient than the current solution, in which all the video data flows through another component.
