### ISSUE TITLE
Embed subtitles support

### ISSUE THREAD

**Issue by Pachini** [kaltura/nginx-vod-module#737]
Hello!

I have a thousands of m4v files with already embedded srt subtitles (with different languages): mp4box Type "sbtl:tx3g". Any chance to show them? Not in playlist, just keep them embedded

**Comment by erankor** [comment]
Please send a URL to a sample file. I don't think they can remain embedded, but depending on the exact format it may be a simple change to reuse the existing SRT parser and include them in the output.

**Comment by Pachini** [comment]
With 2 subtitles embedded: https://www.dropbox.com/s/ka99bhirmefbx13/subs_example.m4v?dl=1


```
Track # 3 Info - TrackID 3 - TimeScale 1000 - Media Duration 00:02:53.781
Media Info: Language "English" - Type "sbtl:tx3g" - 62 samples
Timed Text - Size 320 x 240 - Translation X=0 Y=0 - Layer 0
Alternate Group ID 2

Track # 4 Info - TrackID 4 - TimeScale 1000 - Media Duration 00:02:53.720
Track is disabled
Media Info: Language "Russian" - Type "sbtl:tx3g" - 44 samples
Timed Text - Size 320 x 240 - Translation X=0 Y=0 - Layer 0
Alternate Group ID 2
```

**Comment by erankor** [comment]
I checked it out, unfortunately it's not that simple to support it, each subtitle line is saved as a frame. There are two implications to that:
1. The module can't assume that it has all the subtitle lines in advance (as it does now), it will have to use some state machine to process them
2. Even if I write this code, it would be inefficient, since the subtitle frames are interleaved between the audio/video frames. In the worst case scenario (depending on how the frames are interleaved and the read buffer size) the entire file may be read 4 times - video, audio, subtitles-en, subtitles-ru

So, I think the best option for you is to extract these subtitles to external files, with ffmpeg or some other tool.

**Comment by Pachini** [comment]
Eh :|
Maybe there is any chance to use remote srt not in mapped mode (same domain *.sample.com)? I already have all this subtitles as separate files, but  its a bad idea to have a copy on each edge server. More than 90000 subtitles files now :)

**Comment by erankor** [comment]
I don't quite understand the question, you want to use local mp4 and remote SRT? 
If so, only way I can think of for doing that is to configure nginx-vod-module to use remote mode, but have some of the URLs actually be remote, and have some URLs proxy to a location on the same server that serves local files.
