### ISSUE TITLE
How to generate multi audio HLS and DASH manifests

### ISSUE THREAD

**Issue by mrbeni** [kaltura/nginx-vod-module#742]
Hey guys,
Thanks for the awesome module.
I have searched the whole issue section and could not find how to generate HLS and DASH manifests with multiple languages. A hint on how to make the proper call to generate multi-audio master playlist would be highly appreciated.

And BTW, should I store audio tracks in separate files, or could they be multiple tracks in the same mp4 as the video?

**Comment by erankor** [comment]
Both options (single file / multiple files) are supported. If you use a single file with properly tagged tracks, a URL like `/hls/path/to/your.mp4/master.m3u8` will return each language as a separate EXT-X-MEDIA tag (and similarly for DASH).
If you have multiple files, you need to somehow specify the language of each one. If you use mapped mode, you can use the language property in the JSON  (https://github.com/kaltura/nginx-vod-module/#sequence). If you don't use mapped mode, you can use the `lang` URL parameter, there's a sample for that here https://github.com/kaltura/nginx-vod-module/issues/456

**Comment by mrbeni** [comment]
Thanks for the quick reply. 
I could not get this one to work.
localhost:8001/local/hls/content/lang/,spa/test.vtt,bul/test.vtt,eng/test.mp4,.urlset/master.m3u8
domain/content/lang/audio1.mp4,eng/audio0.mp4,spa/file,1,2,3,4,5,.mp4.urlset/master.m3u8

**Comment by erankor** [comment]
The second URL looks invalid, /lang/ should be a 3 letter language code, while you send audio1.mp4 there.

To clarify - the sample URL from issue 456 (that you pasted) is interpreted as 3 URLs:
1. localhost:8001/local/hls/content/lang/spa/test.vtt.urlset/master.m3u8
2. localhost:8001/local/hls/content/lang/bul/test.vtt.urlset/master.m3u8
3. localhost:8001/local/hls/content/lang/eng/test.mp4.urlset/master.m3u8
(I used test.vtt for both spa & bul since it was just a test, in reality they will use different files...)

Your URL is parsed as:
1. domain/content/lang/audio1.mp4eng/audio0.mp4.mp4.urlset/master.m3u8
2. domain/content/lang/audio1.mp4spa/file.mp4.urlset/master.m3u8
3. domain/content/lang/audio1.mp41.mp4.urlset/master.m3u8
4. domain/content/lang/audio1.mp42.mp4.urlset/master.m3u8
...
Which doesn't make much sense...

The format is - `<common prefix>,<middle1>,<middle2>,...<middlen>,<common suffix>.urlset/...`

**Comment by mrbeni** [comment]
So given your example, localhost:8001/local/hls/content/lang/,spa/test.vtt,bul/test.vtt,eng/test.mp4,.urlset/master.m3u8

if I'm not wrong this should be the correct call for 2 audio languages and 5 video quality HLS manifest.
url.to.mu.domain/content/lang/,eng/audio0.mp4,bul/audio1.mp4/file,1,2,3,4,6,.mp4.urlset/master.m3u8

**Comment by erankor** [comment]
No, it's not, because if the lang param is before the first comma, it applies to ALL urls, while you want it only on the audio files.
You need something like this - url.to.my.domain/content/,lang/eng/audio0.mp4,lang/bul/audio1.mp4,file/1,file/2,file/3,file/4,file/5,.mp4.urlset/master.m3u8
Assuming the audio files are /content/audio0-1.mp4 and the video files are /content/file/1-5.mp4.
Again, the way to understand it is to split the URLs with comma, take the first and last items, and add them as the prefix + suffix of all 'middle' items. 
Also, if it doesn't work for you, check the error log, you should have an informative error there.

**Comment by mrbeni** [comment]
Thanks for the help.

**Comment by mrbeni** [comment]
Using your URL I get the following error on the nginx log. It parses the audio1.mp4 into audio1.mp4.mp4

My request in url.to.my.domain/contenbt/,lang/eng/audio0.mp4,lang/bul/audio1.mp4,file/1,file/2,file/3,file/4,file/5,.mp4.urlset/master.m3u8

[error] 15065#0: *1185 ngx_file_reader_update_state_file_info: open() "/var/www/html/content/audio1.mp4.mp4" failed (2: No such file or directory), client: ...., server: , request: "GET /content/,lang/eng/audio0.mp4,lang/bul/audio1.mp4,file/1,file/2,file/3,file/4,file/5,.mp4.urlset/master.m3u8 HTTP/1.1", host:

**Comment by erankor** [comment]
Right, since we have .mp4 following the last comma... need to remove it from the audio0/1:
url.to.my.domain/content/,lang/eng/audio0,lang/bul/audio1,file/1,file/2,file/3,file/4,file/5,.mp4.urlset/master.m3u8

**Comment by mrbeni** [comment]
Great, works fine now. Thanks for your patience! :)
