### ISSUE TITLE
Automatically derive segment Last-Modified from source media file?

### ISSUE THREAD

**Issue by fsouza** [kaltura/nginx-vod-module#749]
Would it be possible to uses the mp4 Last-Modified info to set the Last-Modified header?

This can help supporting Etag (as nginx derives Etag from Last-Modified + Content-Length). Today, when using etag, if the contents of a segment change but the size remains the same, the etag wouldn't change, which can yield unexpected results.

This could easily happen to captions (imagine a typo where you just change the order of two letters, the segment size wouldn't change). We were also (un)lucky enough to see it happening to an actual video segment 🥇 

I believe this can also happen to playlists, but I don't see how a playlist would have its content changed and retain the same length.

**Comment by erankor** [comment]
While it is possible to add such a feature, I'm not sure it makes sense. In general, updating a video file in place is very problematic. 
Consider a case of a user consuming segment 1 from the video 1 and segment 2 from video 2. If the videos are transcoded exactly the same, and segments are aligned to key frames the user will get a weird combination, otherwise, the player will most likely error out/ the user will get strange artifacts. 
In our system, we never update a file in place, when we need to update, we create a new version, which also implies a new URL. So - a user who started watching version 1 will continue receiving segments from version 1 (since the URL refers to version 1), even after version 2 is deployed.

**Comment by fsouza** [comment]
@erankor wouldn't the same argument apply to not supporting etag at all?

**Comment by erankor** [comment]
Yes, it would. As I wrote above, I think that in the case of video streaming, it's best to avoid changing the contents behind a specific URL, and use some kind of versioning scheme instead.

**Comment by fsouza** [comment]
@erankor cool, thank you! :D 

Unfortunately we can't really do that yet, but we've been talking about doing. For now, we'll disable etags :)
