### ISSUE TITLE
Add  iframe playlists to encrypted HLS streams

### ISSUE THREAD

**Issue by mazanov** [kaltura/nginx-vod-module#755]
When HLS streams are encrypted (vod_hls_encryption_method is not "none") the iframe playlists (EXT-X-I-FRAME-STREAM-INF) are not generated and included in to master.m3u8.
Why so?

**Comment by erankor** [comment]
That is intentional, for encrypted streams it's not possible to be able to generate the iframes list without having to read the data of the frames (which would be very inefficient). For AES-128, the module has no way to know the encryption IV of the key frame without encrypting everything that comes before it in the segment. For SAMPLE-AES, the layout of the segment (the position of each frame) is not known in advance since the frames have to go through emulation prevention after the encryption.
I thought in the past about building a solution that does not reuse the data of the video segments - return a URL like /.../frame-123.ts which will contain only the encrypted frame, and in this case, the problems explained above do not exist (1 - I can choose any IV I want, 2 - I don't need to provide accurate ranges). The downside is, of course, that the iframes will be cached separately by the CDN, and less likely to be a cache hit. Another possible workaround is to add support for AES-128, but take only iframes that appear first in their segment, this would solve the IV problem. Either way, these solutions are currently not implemented. 
What is probably a better solution at this point (and I may get to it if I have the time), is to add support for iframes list with fmp4 container. With fmp4, SAMPLE-AES/cbcs encryption does not alter the layout of the segment (some blocks get encrypted but all the rest is the same), so if the module will support iframes list for fmp4, it will immediately support it also for SAMPLE-AES/cbcs.
