### ISSUE TITLE
Multi url structure issue

### ISSUE THREAD

**Issue by zikoops** [kaltura/nginx-vod-module#767]
Hello, thanks for your great module!

I have read this introduction https://github.com/kaltura/nginx-vod-module/#multi-url-structure and do following but it doesn't work for me.
I have tested with bellow urls and they are working:
https://domain.com/85/4c/854cfc6d265a2909741b576c33ef7c22/480.mp4/playlist.m3u8
https://domain.com/85/4c/854cfc6d265a2909741b576c33ef7c22/720.mp4/playlist.m3u8
https://domain.com/85/4c/854cfc6d265a2909741b576c33ef7c22/1080.mp4/playlist.m3u8
But when i try to do with multi url structure it throw a 400 bad request error
My multi url structure is following:

`https://domain.com/85/4c/854cfc6d265a2909741b576c33ef7c22/,480,720,1080,.mp4.urlset/playlist.m3u8`

My nginx configuration is following:

`server {
	listen 443;
	
	ssl on;
    ssl_certificate /etc/nginx/sslcert/certificate.crt;
    ssl_certificate_key /etc/nginx/sslcert/private.key; 
	access_log /var/log/nginx/access_vod_1812.log;
	error_log /var/log/nginx/error_vod_1812;
	
    root   /home/
    index index.php index.html index.htm;
	

		# vod settings
		vod_mode local;
		#vod_fallback_upstream_location /fallback;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		#vod_metadata_cache metadata_cache 512m;
		#vod_response_cache response_cache 128m;
		
		# gzip manifests
		##gzip on;
		#gzip_types application/vnd.apple.mpegurl;

		# file handle caching / aio
		open_file_cache          max=5000 inactive=5m;
		open_file_cache_valid    2m;
		#open_file_cache_min_uses 1;
		open_file_cache_errors   on;
		aio on;
		

		location ~ ^/([^/]+)/(.*) {
			vod hls;
			vod_hls_absolute_index_urls off;
			vod_hls_index_file_name_prefix playlist;
			vod_segment_duration 5000;
			#vod_multi_uri_suffix .urlset;
			
			#secure_token_encrypt_uri on;
			#secure_token_encrypt_uri_key 000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f;
			#secure_token_encrypt_uri_iv 00000000000000000000000000000000;
			secure_token_encrypt_uri_part $1;
			#secure_token_types application/vnd.apple.mpegurl;
			#secure_token_types application/vnd.apple.mpegurl application/dash+xml text/xml;
			#secure_token $args;
			
			
			 add_header Access-Control-Allow-Headers '*';
			 add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			 add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			 add_header Access-Control-Allow-Origin '*';
			expires 100d;
			
		}
		
}`

Please help me to find what i'm doing wrong.

**Comment by erankor** [comment]
A media playlist (index.m3u8 or playlist.m3u8 in your configuration) can only be requested for a single URL, you need to request /master.m3u8 instead. 
In HLS, there are two types of manifests -
1. Master playlist - contains the definitions of the different renditions, and optionally alternative audio streams or subtitles.
2. Media playlist - contains the video segments of a specific rendition / audio stream / subtitles

Since a media playlist contains the actual video segments, it can't be requested for more than one audio/video stream (while MPEG TS/fMP4 allow arbitrary number of video/audio streams, this is not really supported by most players, and not a good idea in general...)

**Comment by zikoops** [comment]
Thank you for your details, it is really helpful for me @erankor
