### ISSUE TITLE
Continuos Live - probably invalid segment index

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#770]
Hi Eran,

We are trying for continuous live stream.

Inputs : Live udp stream is transcoded and segmented as 4sec mp4 files
output : Live stream in HLS/DASH with cenc encryption

We are executing set-up in mapped mode configuration. The JSON file will be updated every 4sec by using your sample playlist.php.

Files on server :
Inside Test folder, there will be segmented mp4 files, Test.json and Test.js. Mp4 files will keep on growing (s001.mp4,s002.mp4,s003.mp4 and so on). Test.json file will be updated every 4sec

Nginx config as below

location ~ ^/enc/([^-]+)-.* {
vod dash;
vod_mode mapped;
vod_media_set_map_uri enc/$1.json;

Issues we face :

Access Log - "GET /enc/Test/Test-/fragment-4-v1-x3.m4s HTTP/1.1" 404

Debug Log -
2017/12/27 14:54:36 [error] 17016#17016: *1052 ngx_http_vod_validate_streams: no matching streams were found,probably invalid segment index while sending to client, client: x.x.x.x, server: localhost, request: "GET /enc/Test/Test-/fragment-4-v1-x3.m4s HTTP/1.1", host: "y.y.y.y:8005"

URL for client - http://localhost:8005/enc/Test/Test-/manifest.mpd

Can you help us for live stream generation ? We are happy to share additional details also, if required

#320

**Comment by erankor** [comment]
Unfortunately, live is complicated, and continuous live, even more. For example, when you use short segments, you have to provide different timestamps for audio/video. If you just take the sample playlist.php and try to apply it to real live, you will probably get glitches in the mp4 boundaries, since nginx-vod-module will start both audio & video at the same timestamp for each mp4. 
Because of the above, I wouldn't recommend building continuous live yourself...
Specifically regarding the issue you reported, what probably happens is that the JSON is not updated properly, and fragment number 4 exists while the manifest is served, but no longer exists when the client tries to download it.

**Comment by Natarajan92** [comment]
Hi Eran, 

Thanks for your explanation. 


For now closing this ticket.
