### ISSUE TITLE
Timeout for reading mp4 file from disk

### ISSUE THREAD

**Issue by takid1412** [kaltura/nginx-vod-module#779]
Hi, 

We has got problem about streaming with local mode on hls. We used glusterfs for storage files over servers. Everything work beautiful with normal state. But we got some bug in glusterfs then partition that store streaming files become unmounted and inaccessible suddenly.

Problem is request that come after that time act like expect - return an 500 error. But request is reading file while glusterfs still alive lead nginx process to D state aka "uninterruptible sleep". We check stack of these processes and found that fuse_ function is waiting for I/O that never sign back. We have no choices other than reset sever to release these processes and related ports (that is really terrible).

I wonder if vod-module have some api like read timeout for reading file from disk to prevent same errors in future?

Many thanks.

**Comment by erankor** [comment]
Are you using aio? because with a hung read request is not supposed to make the process hang when aio is used.

**Comment by takid1412** [comment]
Yes, we are using `aio on` for vod streaming.

**Comment by erankor** [comment]
Well, currently, there is no timeout for reading files from disk, but even if there was, if I understand correctly what you're saying - the main nginx thread gets blocked when this happens. So even if we add a timeout, the thread won't be available to see that it fired. 
You can try to use remote mode instead of local, and have nginx-vod-module pull the files from a different nginx location on localhost. If you do that, you'll be able to use the proxy_xxx_timeout directives. But if this indeed makes the nginx thread hang, you'll still run out of workers...

**Comment by takid1412** [comment]
I thought about it before, but problem is dead process keep holding port and master nginx process, and i can't reload or restart nginx service.
As i expected we have an api to deep fuse_ function in system for i/o timeout if reading take too much time. But it seem not available at this time. I will take a research on it. But in general, maybe i should separate storage server with streaming server for better handling.
Anw, thanks for your support.
