### ISSUE TITLE
multiple audio renditions

### ISSUE THREAD

**Issue by samanmohamadi** [kaltura/nginx-vod-module#790]
Hi, Thanks so much for this great repo.

> Generation of manifest with different audio renditions, allowing selection on the client side

I want to use this feature but I don't understand how.
would you please write a simple example?

Currently I am serving videos similar to this:
`http://<domain>/<location>/video-,240,360,480,p.mp4.urlset/<filename>`

assuming I  have this files:
video-240p.mp4, video-360p.mp4, audio-en.ogg, and audio-fa.ogg

**Comment by erankor** [comment]
First of all, ogg format is not supported, you'll have to transcode the files to MP4/AAC (can be done using ffmpeg).
To have nginx-vod-module generate a multi-audio manifest, it needs to somehow know the language codes of the different audio files/tracks.
There are several options:
1. Set the language on the MP4 track metadata - since you will need to transcode the files anyway, this is probably the easiest for your scenario. From a quick search on ffmpeg documentation - this should probably do it `ffmpeg -i INPUT -metadata:s:a:0 language=eng OUTPUT` (I didn't try...)
2. Pass the language on the URL - for your sample URLs, it will look similar to this - `http://<domain>/<location>/,video-240p,video-360p,video-480p,lang/eng/audio-en,lang/fas/audio-fa,.mp4.urlset/master.m3u8`
3. Use mapped mode and pass the language on the mapping JSON

**Comment by samanmohamadi** [comment]
Thanks
