### ISSUE TITLE
playlist.php not generating correct json code

### ISSUE THREAD

**Issue by kolevgeorgie** [kaltura/nginx-vod-module#798]
Hi, 

When I try to generate a json using the sample playlist.php i get some errors which I hope you can help me resolve. First of all there is a memory allocation error:
`[Wed Feb 21 16:11:52.442070 2018] [:error] [pid 1129] [client 192.168.152.1:10094] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /var/www/html/playlist.php on line 127`
I "fixed" this one by increasing the memory limit of php

Then I was able to generate a json script using the following code, i'll post only the changes i've made from the original file:
```
// input params
$filePaths = array(
        // clip 1
        array(
                "/opt/media/edno.mp4",
#               "/path/to/subtitles1.srt",
        ),
        // clip 2
        array(
                "/opt/media/dve.mp4",
#               "/path/to/subtitles2.srt",
        ),
);

$ffprobeBin = '/usr/local/bin/ffprobe';
```

So when I try to directly open the file from browser I get the following code, notice the missing "dve.mp4" and that the first clip was added 4 times:
`{"firstClipTime":1519223792000,"segmentBaseTime":1519223792000,"discontinuity":false,"playlistType":"live","durations":[55080,55080,55080,55080],"sequences":[{"clips":[{"type":"source","path":"\/opt\/media\/edno.mp4"},{"type":"source","path":"\/opt\/media\/edno.mp4"},{"type":"source","path":"\/opt\/media\/edno.mp4"},{"type":"source","path":"\/opt\/media\/edno.mp4"}]},{"clips":[{"type":"source","path":null},{"type":"source","path":null},{"type":"source","path":null},{"type":"source","path":null}],"language":"eng"}]}`

I also found the following notice in apache error log:
```
[Wed Feb 21 16:38:22.267186 2018] [:error] [pid 41922] [client 192.168.152.1:12435] PHP Notice:  Undefined offset: 1 in /var/www/html/playlist.php on line 178
[Wed Feb 21 16:38:22.272007 2018] [:error] [pid 41922] [client 192.168.152.1:12435] PHP Notice:  Undefined offset: 1 in /var/www/html/playlist.php on line 178
[Wed Feb 21 16:38:22.272028 2018] [:error] [pid 41922] [client 192.168.152.1:12435] PHP Notice:  Undefined offset: 1 in /var/www/html/playlist.php on line 178
[Wed Feb 21 16:38:22.272036 2018] [:error] [pid 41922] [client 192.168.152.1:12435] PHP Notice:  Undefined offset: 1 in /var/www/html/playlist.php on line 178
```

**Comment by erankor** [comment]
It is very odd that you get a memory error, the script uses very little memory... 
Regarding the notice, you need to also comment the 'eng' element of the $languages array - this array has to match the number of sequences in the $filePaths array.

**Comment by kolevgeorgie** [comment]
Commenting 'eng' solved pretty much everything, except... When I play the following URL on hls.js player:
http://192.168.152.132:80/hls/playlist.php/disc/0/type/live/index.m3u8

I can only see the first file playing with duration increasing with 10 seconds on every 10 seconds and the content is seekable and not "live"?

**Comment by kolevgeorgie** [comment]
Playlist.php is still generating json with only one of the videos, any suggestions on that?

**Comment by erankor** [comment]
Regarding the stream being seekable - under default configuration, the module outputs a 30 sec window, the client may seek within these 30 sec. You can control it with `vod_live_window_duration`, but note that -
1. You should not have less than 3 segments in the manifest, which means - if you decrease the window size, also decrease the segment size
2. The window allows the client to buffer content in advance, if you use a shorter window, you are more prone to experience buffering in case of short network glitches.

Regarding the fact you see only one video - this is because you passed discontinuity=false on the URL. When not using discontinuity, the videos must have exactly the same encoding parameters. Usually that is not the case, unless special care is taken, therefore the script just uses a single video.
If you are sure your videos have exactly the same encoding parameters - you can comment out the line `$filePaths = array($filePaths[0], $filePaths[0]);` and you'll see both videos.
Otherwise, use /disc/1 on the URL.

**Comment by LoikMaksim** [comment]
i had same problem.
Whean i change type to vod - its work.Playlist has same order as i put.
When change to live - video play few second, than just stop playnig.And order is wrong.I had try a lot of option,change video etc.

When i use playlist.php - video starts from strange time.
{"firstClipTime":1519406636500,"segmentBaseTime":1519312889000,"discontinuity":false,"playlistType":"live","durations":[96250,96250,96250,96250],"sequences":[{"clips":[{ ......

**Comment by kolevgeorgie** [comment]
Actually changing disc to 1 solved the problem. 

Erankor, whilte playing the live stream if I add one more clip in playlist.php and save, nginx starts sending the signal from clip 1, is this something I need to change from the script or its the actual way nginx-vod works?

**Comment by erankor** [comment]
The php script does not support changing the clips of an active stream, it's just a sample to show how to create the different JSONs. A more advanced script needs to be developed in order to support that - it will need to keep some state on which clips were already returned to clients and should remain untouched.

**Comment by kolevgeorgie** [comment]
Alright, thanks! C
