### ISSUE TITLE
dublicated bitrate with dash

### ISSUE THREAD

**Issue by momkin** [kaltura/nginx-vod-module#826]
Hello ,
i have setup nginx with dash vod , but i have problem with bit rates being duplicated
screenshot 

https://screenshotscdn.firefoxusercontent.com/images/f4d04052-cd67-46a4-9764-0c1cce3f6dff.png

**Comment by erankor** [comment]
Maybe I'm missing something, but I don't see duplicate bitrates in the screenshot, duplicate resolutions yes, but not bitrates. But anyway, if there are duplicates, they are probably coming from the input - the module does not remove duplicate video tracks. Duplicate audio tracks are removed, since it's common to have the same audio bitrate in multiple video renditions.

**Comment by momkin** [comment]
Hi
how can i prevent that ?
i only want it to display 3 resolutions !

**Comment by erankor** [comment]
Maybe I'm missing something, don't you have each resolution in a separate file? because that is the usual setup, and in that case, just don't send the files you don't need. 
If you have all resolutions in a single file, you can ask the module to return a subset of the tracks, e.g. master-v1-v2.m3u8 (for HLS) will include only the first two video tracks. 
There is no feature to automatically remove duplicate resolutions.

**Comment by momkin** [comment]
Hi
No i only have 3 files , hls is working fine it only show 3 bitrates , but dash show 6 :(

**Comment by erankor** [comment]
Can you send a URL to the MPD + the mediainfo output of the 3 files?

**Comment by erankor** [comment]
@momkin, is this still relevant?
