### ISSUE TITLE
Track selection for progressive download

### ISSUE THREAD

**Issue by nzt4567** [kaltura/nginx-vod-module#832]
Hi,

is it possible to select specific audio tracks without using dash/hls/other-adaptive-bitrate-streaming-protocol? I have a situation in which I have mp4 files with multiple audio tracks and I would need to choose only one of them based on the type of client's device. Unfortunately, all the clients do not understand dash/hls, only simple mp4. I can see that the `clipFrom`/`clipTo` works well in local mode, however, I can't seem to get the `tracks` param working. Maybe I am just doing something wrong :)

Thank you!

**Comment by erankor** [comment]
This is indeed not supported, the reason is that in progressive download the module serves a continuous portion of the file. In the case of clipping, the module finds the min/max offsets of the first/last frame in the clip, and serves this continuous range (btw, this works exactly the same as nginx's builtin mp4 module). 
If I would just add a naive implementation of track selection for the mp4 metadata, it will work (=the client will see only the requested track/s) but there will be a lot of waste, since it will also be downloading all other tracks. To put it differently - if you will select only the audio track of some audio+video mp4, you will get an audio only mp4 back, but its bitrate will be the same as the original audio+video mp4.
It is technically possible to build a more complex solution where the module will serve only the relevant (and sparse) portions of the mp4, but this will require a far greater effort.

**Comment by nzt4567** [comment]
Thank you for your reply! 

I understand that in general use-case scenario the comlex solution would be more appropriate, however, for our current situation the naive implementation will work just fine. Do you think it would be possible to point me to right places where to look, so that I could try to create a working patch? :) I am well familiar with nginx's codebase, but I have never been studying the vod-module in a greater detail. 

Thank you very much!

**Comment by erankor** [comment]
Try this pull - https://github.com/kaltura/nginx-vod-module/pull/842

**Comment by erankor** [comment]
@nzt4567, did you try it?

**Comment by nzt4567** [comment]
Hi, sorry for the silence - as the project that I needed this patch for got canceled it kinda got out of my radar. My apologies. It works flawlessly and exactly as described. The mp4 does not seem to contain anything else besides selected tracks, which is exactly what was required. Again, thanks a lot for this patch, it saved the day on its very time ;)
