### ISSUE TITLE
How to all audios as EXT-X-MEDIA in HLS

### ISSUE THREAD

**Issue by benwilber** [kaltura/nginx-vod-module#840]
I have a "mosaic" video stream where there is a single video stream and 4 audio streams (that correspond to the 4 quadrants in the video stream).  How can I make it so that each audio stream is available as EXT-X-MEDIA

Example mp4 file:

https://ll-vods.s3.amazonaws.com/mosaic-test.mp4

I have tried `vod_hls_force_unmuxed_segments on` but it only creates it for the first audio stream (a1)

```
#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",LANGUAGE="en",NAME="default",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="1",URI="index-a1.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=668939,RESOLUTION=1280x720,FRAME-RATE=30.000,CODECS="avc1.64001f,mp4a.40.2",AUDIO="audio0"
index-v1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=235021,RESOLUTION=1280x720,CODECS="avc1.64001f",URI="iframes-v1.m3u8"
```

I am trying to make the playlist appear as this:

```
#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="en",NAME="quad-0,0",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="1",URI="index-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="en",NAME="quad-0,1",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="1",URI="index-a2.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="en",NAME="quad-1,0",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="1",URI="index-a3.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="en",NAME="quad-1,1",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="1",URI="index-a4.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=668939,RESOLUTION=1280x720,FRAME-RATE=30.000,CODECS="avc1.64001f,mp4a.40.2",AUDIO="audio"
index-v1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=235021,RESOLUTION=1280x720,CODECS="avc1.64001f",URI="iframes-v1.m3u8"
```

I have also tried various `/tracks/v1-a1-a2-a3-a4/` and `master-v0-a0.m3u8` but every time it always just has the first audio track and not all of them.

I'm using nginx-vod-module-1.22

Thanks!

**Comment by erankor** [comment]
The way it works is that module uses the 'label' of the track as key, and it will only output a multi-audio manifest if it sees several different labels. So you need to somehow pass different labels for the different tracks.
The label is determined as follows - 
1. In mapped mode, if the label property of the sequence object is set, it will be used
2. If `vod_parse_hdlr_name` is enabled, the module will use the name field in the MP4 hdlr atom as the label. Some mp4's use this field to identify the tracks, but many mp4's just put some generic string like 'VideoHandler' there (that's why the default is off)
3. If the language of the track is defined (and this too can come from the mp4 metadata or the mapping JSON) a default label will be assigned according the language code - e.g. en => English, it => Italiano.

**Comment by benwilber** [comment]
Thank you this was helpful!
