### ISSUE TITLE
nginx-vod-module not working

### ISSUE THREAD

**Issue by rumaovijay** [kaltura/nginx-vod-module#845]
I am just starting with nginx and nginx-vod module. I have put the configuration as mentioned but I am getting this error
2018/05/08 21:01:05 [error] 22144#22144: *3 open() "/usr/share/nginx/html/content/web/sample.mp4/index.m3u8" failed (20: Not a directory), client: 127.0.0.1, server: localhost, request: "GET /content/web/sample.mp4/index.m3u8 HTTP/1.0", host: "localhost:80"

Here is my configuration

http {

	
	server {
		# vod settings
		vod_mode local;
		vod_fallback_upstream_location /fallback;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		vod_metadata_cache metadata_cache 512m;
		vod_response_cache response_cache 128m;
		
		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;

		# file handle caching / aio
		open_file_cache          max=1000 inactive=5m;
		open_file_cache_valid    2m;
		open_file_cache_min_uses 1;
		open_file_cache_errors   on;
		#aio on;
		
		

		location /content/ {
			root /web/;
			vod hls;
			
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
	}
}

This is my url
http://localhost/content/web/sample.mp4/index.m3u8

I am using nginx-1.14.0 and with nginx-vod-module on ubuntu 16.04

**Comment by erankor** [comment]
I don't think what you pasted is the configuration that the server is running, either you edited the wrong file, didn't reload nginx after editing, or the reload failed.
I took your conf, removed the fallback directive (since the fallback is not set up here), and I'm getting -
`2018/05/09 02:35:51 [error] 8910#8910: *1 ngx_file_reader_update_state_file_info: open() "/web/content/web/sample.mp4" failed (2: No such file or directory),
 client: 127.0.0.1, server: , request: "GET /content/web/sample.mp4/index.m3u8 HTTP/1.1", host: "localhost:8001"`

Which is the expected error in this case (since I don't have the file), but the file name has the correct base path, and it doesn't have /index.m3u8.

**Comment by rumaovijay** [comment]
I suspect nginx is not loading in my case.

because if i put my file under /usr/share/nginx/html/content/sample.mp4

and hit the url http://localhost/content/sample.mp4 it works
but if I give  http://localhost/content/sample.mp4/index.m3u8

I tried putting the file in all the combinations including
/web/content , /content/web but when I append /index.m3u8 it gives (2: No such file or directory). If you don't mind can you tell me how to check if nginx vod module is running.

**Comment by rumaovijay** [comment]
Working perfectly Thank you very much Happy Wednesday :100:
