### ISSUE TITLE
Help, I want to modify NALU content before feed ts segment

### ISSUE THREAD

**Issue by wnpllrzodiac** [kaltura/nginx-vod-module#847]
I want to do some private process on NALU before feed ts segemnt in hls vod.
Such as modify NALU data from 0x11 0x22 0x33 0x44 -> 0x12 0x23 0x34 0x45

Can you give me some advise where to change the code?

**Comment by wnpllrzodiac** [comment]
Thank you for your reply. I will try.

**Comment by wnpllrzodiac** [comment]
hi, I have written a filter as you suggest.encrypt the first 64 bytes IDR nalu content and feed to hls. decrypt is the reverse way. Everything is good. But sometimes the frame is corrupt. I think the encrypt data has some data like 0001 which the same as the start code. I find that I should add special 0x03 to avoid parser failed to split nalu correctly。but it's NOT a easy job in decoder side. Any good and easy way to handle this？

**Comment by erankor** [comment]
If I understand you correctly, the filter I mentioned earlier (sample_aes_avc_filter) has a function for that - sample_aes_avc_write_emulation_prevention. This function wraps the write function of next filter in the chain, and outputs an extra 0x03 whenever it sees one of these sequences - 0,0,0 / 0,0,1 / 0,0,2 / 0,0,3.
The function can process the input in arbitrary chunks, and keeps state (zero run) in order to do that.
