### ISSUE TITLE
mapped mode

### ISSUE THREAD

**Issue by abdelazizk** [kaltura/nginx-vod-module#860]
is it possible to have more explanation on how to setup nginx-vod in mapped mode? maybe some more sample configurations?

**Comment by erankor** [comment]
Other than https://github.com/kaltura/nginx-vod-module#mapped-configuration, we have this template https://github.com/kaltura/nginx-vod-module/blob/master/conf/kaltura-nginx.conf.template that is used when installing the precompiled package (intended for use with Kaltura server).

You may want to start with local mode, which is easier to set up, and once you have that working, add the following directives in order to move to mapped - 
```
http {
  upstream map_upstream {
    server put-the-host-here;
  }
  vod_mode mapped;
  vod_upstream_location /map_proxy;

  server {
    location /map_proxy/ {
      internal;
      proxy_pass http://map_upstream/;
    }
  }
}
```
This is the minimum, for production, it's usually a good idea to also use vod_mapping_cache in order to cache the mapping responses.
If you have more specific questions, let me know

**Comment by abdelazizk** [comment]
in this configuration 
https://github.com/kaltura/nginx-vod-module#mapped-configuration
can you provide the following information:
-URL that the client has to send in order to get the video,
-the corresponding request that nginx will send to the upstream server,
-location of the videos that are stored in the nginx server.
Thank you !

**Comment by erankor** [comment]
1. This configuration uses our URL structure, for a single bitrate, it would look something like this - `http://yourserver/p/123/sp/123/serveFlavor/flavorId/123/a.mp4/master.m3u8`
This is just because of the regular expression in this example... you can probably use a simpler location, like `location /hls/ { ... }`
2. For the sample URL above, nginx-vod-module will call the upstream with `/p/123/sp/123/serveFlavor/flavorId/123/a.mp4` (removing the /master.m3u8)
3. The location of the video is determined by the JSON - you need to return full paths from the upstream

**Comment by wnpllrzodiac** [comment]
Please give a url sample for map mode continous live mode.

**Comment by erankor** [comment]
@wnpllrzodiac, not sure what you're asking, the URL structure for mapped mode depends on what the upstream is expecting. In this regard, there is nothing special about live vs. vod or continuous vs. non-continuous.
If you're using the sample php (https://github.com/kaltura/nginx-vod-module/blob/master/test/playlist.php) then it expects something like /playlist.php/type/live/disc/vod/master.m3u8

**Comment by wnpllrzodiac** [comment]
I have deployed mapped mode hls play sucessfully. Thank you for playlist.php.
One more question, how to use "Dynamic clip"? 
Can I use it to implement a dynamic insert ad function(15 second for example) at any arbitrary time when broadcast a live stream?

**Comment by erankor** [comment]
Dynamic clip was indeed added for dynamic ad insertion, unfortunately it's a bit complex.
To use it, you need to add the dynamic clip to the json at the position of the ad break, and assign some ID to it. In nginx.conf, you need to define vod_dynamic_clip_map_uri in order to tell the module what URL should be used to resolve the dynamic clip to a real file. This URL will usually reference $vod_clip_id which will evaluate to the ID you gave the dynamic clip in the JSON. The URL is expected to return a JSON of a "source" object, the minimum is simply - `{"path":"/path/to/mp4"}`
This is in very high level, there are additional complications for implementing ad stitching, e.g. making all users who got assigned with ad id X redirect to the same URL (to allow caching)
Btw, this was tested only in continuous vod mode (i.e. the ads were transcoded to match the main video), I never tested this feature with live/discontinuity.
