### ISSUE TITLE
Clip fails for long video

### ISSUE THREAD

**Issue by BrightSoul** [kaltura/nginx-vod-module#875]
Hello there, thanks for such a great module.
I'm having a problem clipping a 5-hour long video on progressive download.
This request succeeds, I see a nice 15-second clip playing in Google Chrome.
`http://localhost:88/pd/clipFrom/1000/clipTo/16000/five-hour-long-video.mp4`
This fails, I see a broken player image. It starts happening when I try to clip from 20 seconds or so.
`http://localhost:88/pd/clipFrom/40000/clipTo/55000/five-hour-long-video.mp4`

![long-video-issue](https://user-images.githubusercontent.com/1888641/42337009-b4004962-8085-11e8-9407-07dd42eed026.png)

However, if I attempt clipping a one-minute video, everything is fine and I see a 15 seconds clip.
`http://localhost:88/pd/clipFrom/40000/clipTo/55000/one-minute-long-video.mp4`

Any clue on what might be the problem? I see no errors in the error log and this is my pd configuration (I haven't modified it). I'm on Ubuntu on Windows 10.
```
                location /pd/ {
                        alias /var/video/;
                        vod none;

                        directio 512;
                        output_buffers 1 512k;

                        include /opt/kaltura/nginx/conf/cors.conf;
                }
```

Thanks in advance

**Comment by erankor** [comment]
Please provide a URL to the MP4 file

**Comment by BrightSoul** [comment]
Hi and thanks. Here's the URL:
[Five hour long video](https://ss1.civicam.it:44300/civitanova/civitanova.stream_aac.mp4)

And here's some encoding info as seen in VLC.
![image](https://user-images.githubusercontent.com/1888641/42375179-08a9dd76-811b-11e8-9e80-ac6f71f88445.png)

**Comment by erankor** [comment]
I checked it out, this file has frames with negative duration, the first one is at ~17.2 sec. Negative duration is invalid according to the spec (-`sample_delta` is defined as unsigned in `stts`). It seems that some players are allowing these negative durations, and that's why the full file is working for you.
When nginx-vod-module gets such a frame, it parses the duration as unsigned, and therefore gets a very large duration (~13 hours in this case). So, after the 17th seconds you have a gap that spans until the end of the video - any clip that starts after this position will not have any video frames, and will not play.
While it is possible to change the code to support negative durations, I prefer not to do it, since it's invalid according to spec, and may cause all sorts of side effects.

**Comment by BrightSoul** [comment]
> While it is possible to change the code to support negative durations, I prefer not to do it
That's reasonable. I'll try to correct those frames durations on my side and understand why they're there in the first place. Thank you so much, I now have a lead on how to solve the problem.
