### ISSUE TITLE
Get user count

### ISSUE THREAD

**Issue by danizord** [kaltura/nginx-vod-module#883]
Hey, thanks for the great work on this module :)

Just a question. Given I have nginx-vod-module (remote mode) running behind another nginx proxy for caching. How can I get the user count per minute for analytics?

I could not find any way to do that under these conditions:
- I don't have any control over the client, so I need to calculate the user count on server side.
- I can't count by IP, because it should work with multiple users behind a NAT.

**Comment by flavioribeiro** [comment]
You should try and process the request logs on the nginx proxy as it seems to be the component that talks to the players (this is called logs-based metrics).

**Comment by erankor** [comment]
What you may be able to do (depending on your setup) is to set it up so that the client gets a random query parameter on the segment URLs. You can use nginx-secure-token-module to propagate this random parameter from master.m3u8 => index.m3u8 => segments. 
The proxy will be configured so that:
1. The manifests are not cached
2. The query parameters will not be part of the cache key of the segments (so that the proxy will fetch a given segment only once from upstream)

If you do that, you can count the number of unique tokens in the logs of the proxy, and get the number of unique users.

**Comment by erankor** [comment]
I don't have a sample config of something like that, but -
1. No, nginx-secure-token-module does not generate tokens, but it can add an arbitrary nginx variable as a query param for all URLs in an m3u8. To generate the token, you can use $request_id (if you have a new enough nginx, this is builtin, otherwise, you can get it by adding another custom module - nginx_requestid)
2. You need to configure it so that if the request has a token, it will be used, otherwise a token will be allocated. You can do that with the map directive, something like - 
```
map $arg_token $output_token {
  "" $request_id;         # no token - allocate new one
  default $arg_token;  # already have a token - use it
}
...
secure_token $output_token;
```
3. This should work for live as well - since the client calls the master.m3u8 only once - the token will be allocated for him at this point. The token will be embedded in all index.m3u8 URLs inside the master (handled by nginx-secure-token-module), and subsequently in all segment URLs.

**Comment by danizord** [comment]
@erankor that works perfectly. Thank you :)
