### ISSUE TITLE
can this module be compiled on windows with visual studio 2015? how to do it?

### ISSUE THREAD

**Issue by zhengfish** [kaltura/nginx-vod-module#903]
Hello,
I can build it on Ubuntu however I cannot compile it on Windows with VS2015.
There are so many errors like this:

cl -c -O2  -W4 -WX -nologo -MT -Zi -DFD_SETSIZE=1024 -DNO_SYS_TYPES_H -Yungx_config.h -Fpobjs/ngx_config.pch -I src/core  -I src/event  -I src/event/modules  -I src/os/win32  -I ../pcre-8.42  -I ../openssl-1.1.0i/openssl/include  -I objs  -I src/http  -I src/http/modules  -I src/stream  -Foobjs/addon/nginx-vod-module/ngx_file_reader.obj  ../modules/nginx-vod-module/ngx_file_reader.c
ngx_file_reader.c
../modules/nginx-vod-module/ngx_file_reader.c(446): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "ngx_config.h"' to your source?
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

**Comment by erankor** [comment]
I never built the module on Windows, I have some MSVC project that I use for development, but it doesn't fully compile. 
If you managed to get nginx core to compile, it probably won't take a lot of changes to make this module compile as well. 
Specifically regarding the error you pasted, there are 2 ways to solve it -
1. Easiest solution - disable 'precompiled headers' in the project compiler settings, compilation will be a bit slower, but don't think it matters much.
2. Add '#include "ngx_config.h' to all C files of this module - for the files under the root folder of the module it's fine, but the files under the `vod` folder are currently abstracted from nginx, so that would be far from ideal.

**Comment by wnpllrzodiac** [comment]
I think nginx build on win32 is a hard core.
