### ISSUE TITLE
How to get all active connections

### ISSUE THREAD

**Issue by bounmed** [kaltura/nginx-vod-module#927]
Any solution to get all active connections and streamed files?

**Comment by erankor** [comment]
The question is how you can check which streams are currently playing?
If so, the answer is no, since -
1. In most deployments there will be some caching in front of this module, so the module won't "see" all active streams
2. Unlike protocols like RTMP, in HLS/DASH the client pulls individual segments of the video, the server doesn't know which clients are actually playing

However, you may be able to extract something by parsing the nginx access log - if you are using segments of 10 sec, for example, you can look for requests in the last 10 sec, and get some rough estimate of the active streams.

**Comment by bounmed** [comment]
Thank you
