### ISSUE TITLE
Feature request: buffer/cache configuration

### ISSUE THREAD

**Issue by DBezemer** [kaltura/nginx-vod-module#93]
It would be great to have more control over the buffer/cache configuration especially the following items:
- buffer size/time
- cache location (mem/disk)
- support for purging cache

**Comment by erankor** [comment]
1. Regarding buffer, you can use vod_cache_buffer_size to configure the size of the read buffer. A larger size means fewer disk reads, but it can also mean that the module reads data that is not used (past the requested segment). The default size of 256K was found to work well on our environment.
2. Regarding caches, the module uses several different caches:
  a. Path mapping - saves the mapping between URIs to paths (in mapped mode)
  b. Response - saves the results of manifest requests
  c. Drm info - saves the encryption parameters that should be used for a given URI
  d. Moov - saves the MP4 moov atom that contains the video metadata
The first 3 caches are small, so no reason not to use memory for them. The moov cache can be big, we're currently using 4G for it on our environment. The main idea of this cache is to save disk reads, so it would only make sense to store it on disk if it will be stored on a fast disk (e.g. local file system) while the main video store is slow (e.g. some NFS storage). However, an advantage of using memory is that a cache hit is zero copy, while a disk cache, even on a fast disk, will require some buffer copying. For this reason, I currently consider this feature low priority
3. Since the existing caches are all memory based, they can be purged simply by reloading nginx

I'm currently closing this issue, let's discuss it over skype/email if you think I missed anything

**Comment by supermasita** [comment]
Sorry, I know this is closed but I would like to express that I also feel like an option to choose disk cache its important. I been working for many years with media companies that have an enormous amount of videos and its impossible to have a fair amount of them in RAM. I had big success using Wowza + Mediacache on fast local disk (ssd and/or raid). Your approach its correct and I think it fits most needs, but disk cache could be a better option in some scenarios.

Thanks!
:)

**Comment by erankor** [comment]
I agree that caching large video libraries in memory is not realistic, but the module does not currently cache the video data at all, it only caches the video metadata, so the question is whether it's important to have the ability cache the video metadata on disk. As I wrote above, we are using a 4GB cache per server for the video metadata and we are getting a good hit ratio (about 90% last time I checked)
If caching of the video data is required (we are using a CDN so we don't have to do it ourselves) then I suggest setting up an nginx server (or nginx location on the same server) in front of nginx-vod-module with proxy_pass and proxy_cache. This is a built-in caching functionality of nginx and supports disk caching

**Comment by Georgisim** [comment]
Hi erankor,

I see you suggestion for purging cache by simply reloading nginx, but this is a little bit inefficient, especially if you have heavy traffic and frequent purge requests,

I did something, but I'm unsure if some race condition might occur and/or some data corruption due to not fully understand your code. I cannot completely understand the need of sh->reset flag, because everything regarding its setting, clearing and checking is surrounded by ngx_shmtx_lock() ngx_shmtx_unlock() critical section.


Here is what I suggest for removing entry as a part of purge code:

ngx_flag_t
ngx_remove_cache_entry(ngx_buffer_cache_t* cache,
		u_char* key)
{
	ngx_buffer_cache_entry_t* entry;
	ngx_buffer_cache_sh_t *sh = cache->sh;
	uint32_t hash;

	hash = ngx_crc32_short(key, BUFFER_CACHE_KEY_SIZE);

	ngx_shmtx_lock(&cache->shpool->mutex);

	entry = ngx_buffer_cache_rbtree_lookup(&sh->rbtree, key, hash);
	if (entry != NULL) {
		// update the state
		entry->state = CES_FREE;

		// remove from rb tree
		ngx_rbtree_delete(&sh->rbtree, &entry->node);

		// move from used_queue to free_queue
		ngx_queue_remove(&entry->queue_node);
		ngx_queue_insert_tail(&sh->free_queue, &entry->queue_node);

		if (ngx_queue_empty(&sh->used_queue)) {
			// queue is empty reset the read/write pointers
			sh->buffers_read = sh->buffers_end;
			sh->buffers_write = sh->buffers_end;
		} else {
			// update the read buffer pointer
			sh->buffers_read = entry->start_offset;
		}

		// update stats
		sh->stats.evicted++;
		sh->stats.evicted_bytes += entry->buffer_size;
	}

	ngx_shmtx_unlock(&cache->shpool->mutex);

	return entry ? NGX_OK : NGX_ERROR;
} 


I'll be happy if you can comment the approach

Thank you in advance,

George

**Comment by erankor** [comment]
You want to remove a specific cache entry? 
This won't work, the cached data is saved in a cyclic buffer, it is not possible to remove some item from the middle.

**Comment by Georgisim** [comment]
Thank you for fast reply.
Yes, I need to remove specific entry. So there are not so many alternatives: worst is to reset the whole cache, which will be slightly better then nginx reload. Other is to do memmove, assuming that purge operations are much more infrequent then cache fetch/store, but this looks complicated task. May be for me it will be a little bit easier to rewrite the whole code, but for sure I'll loose some performance, because it looks like you've optimized for this particular case. Hm, I have other idea - what do you think  about marking entry as a dirty and fetch op will not return a match, and then it will be naturally removed by ngx_buffer_cache_free_oldest_entry

**Comment by erankor** [comment]
This can work, but it's a bit delicate, you need to update the state + remove it from the rbtree, but leave it on the used queue. Naturally the space it occupies will be reclaimed only when it reaches the end of the cycle.

**Comment by Georgisim** [comment]
> Naturally the space it occupies will be reclaimed only when it reaches the end of the cycle.
that's good enough for purpose of purge op. 

May be something like that:

```
ngx_flag_t
ngx_remove_cache_entry(ngx_buffer_cache_t* cache,
		u_char* key)
{
	ngx_buffer_cache_entry_t* entry;
	ngx_buffer_cache_sh_t *sh = cache->sh;
	uint32_t hash;

	hash = ngx_crc32_short(key, BUFFER_CACHE_KEY_SIZE);

	ngx_shmtx_lock(&cache->shpool->mutex);

	entry = ngx_buffer_cache_rbtree_lookup(&sh->rbtree, key, hash);
	if (entry != NULL) {

		// update the state
		entry->state = CES_FREE; // do we really need this here?

		// remove from rb tree
		ngx_rbtree_delete(&sh->rbtree, &entry->node);

		// update stats
		sh->stats.evicted++;
		sh->stats.evicted_bytes += entry->buffer_size;
	}

	ngx_shmtx_unlock(&cache->shpool->mutex);

	return entry ? NGX_OK : NGX_ERROR;
}
```
event looks that `entry->state = CES_FREE`;  is not needed, because the entry->state is checked only when fetching function where ngx_buffer_cache_rbtree_lookup returns an entry. If I remove the entry from rbtree - there will be no entry :)

**Comment by erankor** [comment]
Yes, but you also need some changes in ngx_buffer_cache_free_oldest_entry - I don't think it's ok to call ngx_rbtree_delete twice (will probably crash) + you need to avoid updating the evicted counters twice.

**Comment by erankor** [comment]
Looks right

**Comment by Georgisim** [comment]
Thank you a lot! I hope this thread could help others who need to do purge.
