### ISSUE TITLE
Dynamic Mapping

### ISSUE THREAD

**Issue by jeffc030** [kaltura/nginx-vod-module#934]
Hello.  

This is a really great module.  It does so much of what I've been looking for (source switching, clipping, speed control).  Much appreciated.

My use-case calls for being able to update the mapping files regularly, with updates to clipping parameters, additional clips, additional bitrates, etc.  I've tried removing the vod_mapping_cache, but I still find myself having to restart nginx to have the new mappings pulled.  Any guidance on suggested approach to this would be much appreciated.

Again, thanks for a really great module.

**Comment by erankor** [comment]
The mapping JSON is read from files or some upstream server?
If files, maybe it can somehow be the open_file_cache, try to remove it as well.

However, I think that in most scenarios, updating the stream in-place is problematic, since the players may get some combination of manifests/segments that doesn't make sense. A simple solution to this is to use versioning - you never update the JSON in place, but rather create a new version of it, and start returning to clients a URL with the updated version. This way, players that started playing before the change will continue getting the version they started with, and nothing would break.

**Comment by jeffc030** [comment]
It is on an upstream server.  Keeping all the json files on S3 along with the media.  

I expect many frequent changes, so version every one wouldn't be practical.  Do you think a ping/pong style update makes sense for this?

**Comment by erankor** [comment]
Another thought - any chance you have vod_response_cache enabled? this cache holds manifest responses, and can be problematic in your scenario.
I think that with ping-pong update you could still have issues, if the concern is accumulating all these JSONs, you can just keep the last N versions.

**Comment by jeffc030** [comment]
It was indeed the vod_response_cache.  mpd refreshed as expected now.  Thanks!
