### ISSUE TITLE
Feature request: log aggregration

### ISSUE THREAD

**Issue by DBezemer** [kaltura/nginx-vod-module#94]
Instead of logging each fragment individually it would be great if there was some sort of aggregration on the entry level combining the bandwidth of a configurable amount of fragments, this would reduce the amount of logging and associated disk access, especially at high concurrency.

**Comment by etameran** [comment]
David,

The logging isn't only for bw calculation . It's used for debugging and analysis . Like any webserver , it's expected to log is operation :)

Eran

Sent from my iPhone

On 9 ???? 2015, at 14:05, David Bezemer <notifications@github.com<mailto:notifications@github.com>> wrote:


Instead of logging each fragment individually it would be great if there was some sort of aggregration on the entry level combining the bandwidth of a configurable amount of fragments, this would reduce the amount of logging and associated disk access, especially at high concurrency.

-

**Comment by DBezemer** [comment]
Eran,

I'm not saying it shouldn't log its operations, but instead of displaying each served fragment it could aggregate it, and only show fragments every x amount of seconds. This would reduce the log output by a lot, and not impact debugging and analysis as it only affects the chunks.

Manifest and other metadata related calls would be logged as usual, just chunks would be aggregrated. This is the same option that nginx plus offers in it's streaming module.

**Comment by etameran** [comment]
I wouldn't use this option ;-)

We are logging massive amounts of data for statistics and postmortem investigation in our api servers . This seem as a relative small amount of logs compared to statistics event for example.


Eran


________________________________

**Comment by erankor** [comment]
I agree with @etameran, also if disk space / disk IO is a concern, it is possible to enable nginx's builtin access log compression.

Closing this issue for now
