### ISSUE TITLE
Remove the load from the disks

### ISSUE THREAD

**Issue by keiskar** [kaltura/nginx-vod-module#990]
Hello,
faced with the problem of disk speed, tell me how you can make a cache of frequently requested files, for example, in RAM, currently almost every server has 16-24 GB of RAM, I think this place is just enough for hot cache to remove the load on disks

**Comment by erankor** [comment]
The module has support for caching the metadata of the video files, to avoid having to read it multiple times (for each segment). If you what you are asking for is caching of the video data itself, this is not handled by this module - the assumption is that there are some caching proxies/CDN in front of it. 
You can use, for example, an nginx server with proxy_cache.

**Comment by keiskar** [comment]
I use the configuration like this [https://github.com/kaltura/nginx-vod-module/issues/923](url)
when trying to use proxy_cache, the module gives 403 to the m3u8 and ts files

**Comment by erankor** [comment]
Probably something breaks the token, and that's why you get 403. But, from a quick look, this configuration seems problematic for caching, the segment base URL has the token in it, which means it's changing all the time, and cannot be cached. It may be possible to work around it with some specific caching configuration, but the more common solution is to have static paths, with the token in a query param. 
You can look at https://github.com/kaltura/nginx-secure-token-module/ for embedding such query param tokens in returned manifests.
